// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"toggo/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFileServiceInterface creates a new instance of MockFileServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileServiceInterface {
	mock := &MockFileServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileServiceInterface is an autogenerated mock type for the FileServiceInterface type
type MockFileServiceInterface struct {
	mock.Mock
}

type MockFileServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileServiceInterface) EXPECT() *MockFileServiceInterface_Expecter {
	return &MockFileServiceInterface_Expecter{mock: &_m.Mock}
}

// CheckS3Connection provides a mock function for the type MockFileServiceInterface
func (_mock *MockFileServiceInterface) CheckS3Connection(ctx context.Context) (*models.S3HealthCheckResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CheckS3Connection")
	}

	var r0 *models.S3HealthCheckResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*models.S3HealthCheckResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *models.S3HealthCheckResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.S3HealthCheckResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileServiceInterface_CheckS3Connection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckS3Connection'
type MockFileServiceInterface_CheckS3Connection_Call struct {
	*mock.Call
}

// CheckS3Connection is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFileServiceInterface_Expecter) CheckS3Connection(ctx interface{}) *MockFileServiceInterface_CheckS3Connection_Call {
	return &MockFileServiceInterface_CheckS3Connection_Call{Call: _e.mock.On("CheckS3Connection", ctx)}
}

func (_c *MockFileServiceInterface_CheckS3Connection_Call) Run(run func(ctx context.Context)) *MockFileServiceInterface_CheckS3Connection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileServiceInterface_CheckS3Connection_Call) Return(s3HealthCheckResponse *models.S3HealthCheckResponse, err error) *MockFileServiceInterface_CheckS3Connection_Call {
	_c.Call.Return(s3HealthCheckResponse, err)
	return _c
}

func (_c *MockFileServiceInterface_CheckS3Connection_Call) RunAndReturn(run func(ctx context.Context) (*models.S3HealthCheckResponse, error)) *MockFileServiceInterface_CheckS3Connection_Call {
	_c.Call.Return(run)
	return _c
}

// GetBulkPresignedURLs provides a mock function for the type MockFileServiceInterface
func (_mock *MockFileServiceInterface) GetBulkPresignedURLs(ctx context.Context, req models.BulkPresignedURLRequest) (*models.BulkPresignedURLResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetBulkPresignedURLs")
	}

	var r0 *models.BulkPresignedURLResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.BulkPresignedURLRequest) (*models.BulkPresignedURLResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.BulkPresignedURLRequest) *models.BulkPresignedURLResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.BulkPresignedURLResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.BulkPresignedURLRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileServiceInterface_GetBulkPresignedURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBulkPresignedURLs'
type MockFileServiceInterface_GetBulkPresignedURLs_Call struct {
	*mock.Call
}

// GetBulkPresignedURLs is a helper method to define mock.On call
//   - ctx context.Context
//   - req models.BulkPresignedURLRequest
func (_e *MockFileServiceInterface_Expecter) GetBulkPresignedURLs(ctx interface{}, req interface{}) *MockFileServiceInterface_GetBulkPresignedURLs_Call {
	return &MockFileServiceInterface_GetBulkPresignedURLs_Call{Call: _e.mock.On("GetBulkPresignedURLs", ctx, req)}
}

func (_c *MockFileServiceInterface_GetBulkPresignedURLs_Call) Run(run func(ctx context.Context, req models.BulkPresignedURLRequest)) *MockFileServiceInterface_GetBulkPresignedURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.BulkPresignedURLRequest
		if args[1] != nil {
			arg1 = args[1].(models.BulkPresignedURLRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileServiceInterface_GetBulkPresignedURLs_Call) Return(bulkPresignedURLResponse *models.BulkPresignedURLResponse, err error) *MockFileServiceInterface_GetBulkPresignedURLs_Call {
	_c.Call.Return(bulkPresignedURLResponse, err)
	return _c
}

func (_c *MockFileServiceInterface_GetBulkPresignedURLs_Call) RunAndReturn(run func(ctx context.Context, req models.BulkPresignedURLRequest) (*models.BulkPresignedURLResponse, error)) *MockFileServiceInterface_GetBulkPresignedURLs_Call {
	_c.Call.Return(run)
	return _c
}
