// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"toggo/internal/models"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSearchServiceInterface creates a new instance of MockSearchServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSearchServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSearchServiceInterface {
	mock := &MockSearchServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSearchServiceInterface is an autogenerated mock type for the SearchServiceInterface type
type MockSearchServiceInterface struct {
	mock.Mock
}

type MockSearchServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSearchServiceInterface) EXPECT() *MockSearchServiceInterface_Expecter {
	return &MockSearchServiceInterface_Expecter{mock: &_m.Mock}
}

// SearchActivities provides a mock function for the type MockSearchServiceInterface
func (_mock *MockSearchServiceInterface) SearchActivities(ctx context.Context, tripID uuid.UUID, query string, limit int, offset int) (*models.SearchActivitiesResult, error) {
	ret := _mock.Called(ctx, tripID, query, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for SearchActivities")
	}

	var r0 *models.SearchActivitiesResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int, int) (*models.SearchActivitiesResult, error)); ok {
		return returnFunc(ctx, tripID, query, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int, int) *models.SearchActivitiesResult); ok {
		r0 = returnFunc(ctx, tripID, query, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SearchActivitiesResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, int, int) error); ok {
		r1 = returnFunc(ctx, tripID, query, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSearchServiceInterface_SearchActivities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchActivities'
type MockSearchServiceInterface_SearchActivities_Call struct {
	*mock.Call
}

// SearchActivities is a helper method to define mock.On call
//   - ctx context.Context
//   - tripID uuid.UUID
//   - query string
//   - limit int
//   - offset int
func (_e *MockSearchServiceInterface_Expecter) SearchActivities(ctx interface{}, tripID interface{}, query interface{}, limit interface{}, offset interface{}) *MockSearchServiceInterface_SearchActivities_Call {
	return &MockSearchServiceInterface_SearchActivities_Call{Call: _e.mock.On("SearchActivities", ctx, tripID, query, limit, offset)}
}

func (_c *MockSearchServiceInterface_SearchActivities_Call) Run(run func(ctx context.Context, tripID uuid.UUID, query string, limit int, offset int)) *MockSearchServiceInterface_SearchActivities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockSearchServiceInterface_SearchActivities_Call) Return(searchActivitiesResult *models.SearchActivitiesResult, err error) *MockSearchServiceInterface_SearchActivities_Call {
	_c.Call.Return(searchActivitiesResult, err)
	return _c
}

func (_c *MockSearchServiceInterface_SearchActivities_Call) RunAndReturn(run func(ctx context.Context, tripID uuid.UUID, query string, limit int, offset int) (*models.SearchActivitiesResult, error)) *MockSearchServiceInterface_SearchActivities_Call {
	_c.Call.Return(run)
	return _c
}

// SearchTripMembers provides a mock function for the type MockSearchServiceInterface
func (_mock *MockSearchServiceInterface) SearchTripMembers(ctx context.Context, tripID uuid.UUID, query string, limit int, offset int) (*models.SearchMembersResult, error) {
	ret := _mock.Called(ctx, tripID, query, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for SearchTripMembers")
	}

	var r0 *models.SearchMembersResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int, int) (*models.SearchMembersResult, error)); ok {
		return returnFunc(ctx, tripID, query, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int, int) *models.SearchMembersResult); ok {
		r0 = returnFunc(ctx, tripID, query, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SearchMembersResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, int, int) error); ok {
		r1 = returnFunc(ctx, tripID, query, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSearchServiceInterface_SearchTripMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchTripMembers'
type MockSearchServiceInterface_SearchTripMembers_Call struct {
	*mock.Call
}

// SearchTripMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - tripID uuid.UUID
//   - query string
//   - limit int
//   - offset int
func (_e *MockSearchServiceInterface_Expecter) SearchTripMembers(ctx interface{}, tripID interface{}, query interface{}, limit interface{}, offset interface{}) *MockSearchServiceInterface_SearchTripMembers_Call {
	return &MockSearchServiceInterface_SearchTripMembers_Call{Call: _e.mock.On("SearchTripMembers", ctx, tripID, query, limit, offset)}
}

func (_c *MockSearchServiceInterface_SearchTripMembers_Call) Run(run func(ctx context.Context, tripID uuid.UUID, query string, limit int, offset int)) *MockSearchServiceInterface_SearchTripMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockSearchServiceInterface_SearchTripMembers_Call) Return(searchMembersResult *models.SearchMembersResult, err error) *MockSearchServiceInterface_SearchTripMembers_Call {
	_c.Call.Return(searchMembersResult, err)
	return _c
}

func (_c *MockSearchServiceInterface_SearchTripMembers_Call) RunAndReturn(run func(ctx context.Context, tripID uuid.UUID, query string, limit int, offset int) (*models.SearchMembersResult, error)) *MockSearchServiceInterface_SearchTripMembers_Call {
	_c.Call.Return(run)
	return _c
}

// SearchTrips provides a mock function for the type MockSearchServiceInterface
func (_mock *MockSearchServiceInterface) SearchTrips(ctx context.Context, userID uuid.UUID, query string, limit int, offset int) (*models.SearchTripsResult, error) {
	ret := _mock.Called(ctx, userID, query, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for SearchTrips")
	}

	var r0 *models.SearchTripsResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int, int) (*models.SearchTripsResult, error)); ok {
		return returnFunc(ctx, userID, query, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int, int) *models.SearchTripsResult); ok {
		r0 = returnFunc(ctx, userID, query, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SearchTripsResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, int, int) error); ok {
		r1 = returnFunc(ctx, userID, query, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSearchServiceInterface_SearchTrips_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchTrips'
type MockSearchServiceInterface_SearchTrips_Call struct {
	*mock.Call
}

// SearchTrips is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - query string
//   - limit int
//   - offset int
func (_e *MockSearchServiceInterface_Expecter) SearchTrips(ctx interface{}, userID interface{}, query interface{}, limit interface{}, offset interface{}) *MockSearchServiceInterface_SearchTrips_Call {
	return &MockSearchServiceInterface_SearchTrips_Call{Call: _e.mock.On("SearchTrips", ctx, userID, query, limit, offset)}
}

func (_c *MockSearchServiceInterface_SearchTrips_Call) Run(run func(ctx context.Context, userID uuid.UUID, query string, limit int, offset int)) *MockSearchServiceInterface_SearchTrips_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockSearchServiceInterface_SearchTrips_Call) Return(searchTripsResult *models.SearchTripsResult, err error) *MockSearchServiceInterface_SearchTrips_Call {
	_c.Call.Return(searchTripsResult, err)
	return _c
}

func (_c *MockSearchServiceInterface_SearchTrips_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, query string, limit int, offset int) (*models.SearchTripsResult, error)) *MockSearchServiceInterface_SearchTrips_Call {
	_c.Call.Return(run)
	return _c
}
