// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"
	"toggo/internal/models"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockImageRepository creates a new instance of MockImageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImageRepository {
	mock := &MockImageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockImageRepository is an autogenerated mock type for the ImageRepository type
type MockImageRepository struct {
	mock.Mock
}

type MockImageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImageRepository) EXPECT() *MockImageRepository_Expecter {
	return &MockImageRepository_Expecter{mock: &_m.Mock}
}

// CleanupPendingUploads provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) CleanupPendingUploads(ctx context.Context, olderThan time.Duration) (int64, error) {
	ret := _mock.Called(ctx, olderThan)

	if len(ret) == 0 {
		panic("no return value specified for CleanupPendingUploads")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration) (int64, error)); ok {
		return returnFunc(ctx, olderThan)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration) int64); ok {
		r0 = returnFunc(ctx, olderThan)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Duration) error); ok {
		r1 = returnFunc(ctx, olderThan)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageRepository_CleanupPendingUploads_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanupPendingUploads'
type MockImageRepository_CleanupPendingUploads_Call struct {
	*mock.Call
}

// CleanupPendingUploads is a helper method to define mock.On call
//   - ctx context.Context
//   - olderThan time.Duration
func (_e *MockImageRepository_Expecter) CleanupPendingUploads(ctx interface{}, olderThan interface{}) *MockImageRepository_CleanupPendingUploads_Call {
	return &MockImageRepository_CleanupPendingUploads_Call{Call: _e.mock.On("CleanupPendingUploads", ctx, olderThan)}
}

func (_c *MockImageRepository_CleanupPendingUploads_Call) Run(run func(ctx context.Context, olderThan time.Duration)) *MockImageRepository_CleanupPendingUploads_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageRepository_CleanupPendingUploads_Call) Return(n int64, err error) *MockImageRepository_CleanupPendingUploads_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockImageRepository_CleanupPendingUploads_Call) RunAndReturn(run func(ctx context.Context, olderThan time.Duration) (int64, error)) *MockImageRepository_CleanupPendingUploads_Call {
	_c.Call.Return(run)
	return _c
}

// ConfirmAllUploads provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) ConfirmAllUploads(ctx context.Context, imageID uuid.UUID) ([]*models.Image, error) {
	ret := _mock.Called(ctx, imageID)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmAllUploads")
	}

	var r0 []*models.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*models.Image, error)); ok {
		return returnFunc(ctx, imageID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*models.Image); ok {
		r0 = returnFunc(ctx, imageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, imageID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageRepository_ConfirmAllUploads_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmAllUploads'
type MockImageRepository_ConfirmAllUploads_Call struct {
	*mock.Call
}

// ConfirmAllUploads is a helper method to define mock.On call
//   - ctx context.Context
//   - imageID uuid.UUID
func (_e *MockImageRepository_Expecter) ConfirmAllUploads(ctx interface{}, imageID interface{}) *MockImageRepository_ConfirmAllUploads_Call {
	return &MockImageRepository_ConfirmAllUploads_Call{Call: _e.mock.On("ConfirmAllUploads", ctx, imageID)}
}

func (_c *MockImageRepository_ConfirmAllUploads_Call) Run(run func(ctx context.Context, imageID uuid.UUID)) *MockImageRepository_ConfirmAllUploads_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageRepository_ConfirmAllUploads_Call) Return(images []*models.Image, err error) *MockImageRepository_ConfirmAllUploads_Call {
	_c.Call.Return(images, err)
	return _c
}

func (_c *MockImageRepository_ConfirmAllUploads_Call) RunAndReturn(run func(ctx context.Context, imageID uuid.UUID) ([]*models.Image, error)) *MockImageRepository_ConfirmAllUploads_Call {
	_c.Call.Return(run)
	return _c
}

// ConfirmUpload provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) ConfirmUpload(ctx context.Context, imageID uuid.UUID, size models.ImageSize) (*models.Image, error) {
	ret := _mock.Called(ctx, imageID, size)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmUpload")
	}

	var r0 *models.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.ImageSize) (*models.Image, error)); ok {
		return returnFunc(ctx, imageID, size)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.ImageSize) *models.Image); ok {
		r0 = returnFunc(ctx, imageID, size)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, models.ImageSize) error); ok {
		r1 = returnFunc(ctx, imageID, size)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageRepository_ConfirmUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmUpload'
type MockImageRepository_ConfirmUpload_Call struct {
	*mock.Call
}

// ConfirmUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - imageID uuid.UUID
//   - size models.ImageSize
func (_e *MockImageRepository_Expecter) ConfirmUpload(ctx interface{}, imageID interface{}, size interface{}) *MockImageRepository_ConfirmUpload_Call {
	return &MockImageRepository_ConfirmUpload_Call{Call: _e.mock.On("ConfirmUpload", ctx, imageID, size)}
}

func (_c *MockImageRepository_ConfirmUpload_Call) Run(run func(ctx context.Context, imageID uuid.UUID, size models.ImageSize)) *MockImageRepository_ConfirmUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 models.ImageSize
		if args[2] != nil {
			arg2 = args[2].(models.ImageSize)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockImageRepository_ConfirmUpload_Call) Return(image *models.Image, err error) *MockImageRepository_ConfirmUpload_Call {
	_c.Call.Return(image, err)
	return _c
}

func (_c *MockImageRepository_ConfirmUpload_Call) RunAndReturn(run func(ctx context.Context, imageID uuid.UUID, size models.ImageSize) (*models.Image, error)) *MockImageRepository_ConfirmUpload_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePendingImages provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) CreatePendingImages(ctx context.Context, imageID uuid.UUID, fileKey string, sizes []models.ImageSize) ([]*models.Image, error) {
	ret := _mock.Called(ctx, imageID, fileKey, sizes)

	if len(ret) == 0 {
		panic("no return value specified for CreatePendingImages")
	}

	var r0 []*models.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, []models.ImageSize) ([]*models.Image, error)); ok {
		return returnFunc(ctx, imageID, fileKey, sizes)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, []models.ImageSize) []*models.Image); ok {
		r0 = returnFunc(ctx, imageID, fileKey, sizes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, []models.ImageSize) error); ok {
		r1 = returnFunc(ctx, imageID, fileKey, sizes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageRepository_CreatePendingImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePendingImages'
type MockImageRepository_CreatePendingImages_Call struct {
	*mock.Call
}

// CreatePendingImages is a helper method to define mock.On call
//   - ctx context.Context
//   - imageID uuid.UUID
//   - fileKey string
//   - sizes []models.ImageSize
func (_e *MockImageRepository_Expecter) CreatePendingImages(ctx interface{}, imageID interface{}, fileKey interface{}, sizes interface{}) *MockImageRepository_CreatePendingImages_Call {
	return &MockImageRepository_CreatePendingImages_Call{Call: _e.mock.On("CreatePendingImages", ctx, imageID, fileKey, sizes)}
}

func (_c *MockImageRepository_CreatePendingImages_Call) Run(run func(ctx context.Context, imageID uuid.UUID, fileKey string, sizes []models.ImageSize)) *MockImageRepository_CreatePendingImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []models.ImageSize
		if args[3] != nil {
			arg3 = args[3].([]models.ImageSize)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockImageRepository_CreatePendingImages_Call) Return(images []*models.Image, err error) *MockImageRepository_CreatePendingImages_Call {
	_c.Call.Return(images, err)
	return _c
}

func (_c *MockImageRepository_CreatePendingImages_Call) RunAndReturn(run func(ctx context.Context, imageID uuid.UUID, fileKey string, sizes []models.ImageSize) ([]*models.Image, error)) *MockImageRepository_CreatePendingImages_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByID provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) DeleteByID(ctx context.Context, imageID uuid.UUID) error {
	ret := _mock.Called(ctx, imageID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, imageID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageRepository_DeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByID'
type MockImageRepository_DeleteByID_Call struct {
	*mock.Call
}

// DeleteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - imageID uuid.UUID
func (_e *MockImageRepository_Expecter) DeleteByID(ctx interface{}, imageID interface{}) *MockImageRepository_DeleteByID_Call {
	return &MockImageRepository_DeleteByID_Call{Call: _e.mock.On("DeleteByID", ctx, imageID)}
}

func (_c *MockImageRepository_DeleteByID_Call) Run(run func(ctx context.Context, imageID uuid.UUID)) *MockImageRepository_DeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageRepository_DeleteByID_Call) Return(err error) *MockImageRepository_DeleteByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageRepository_DeleteByID_Call) RunAndReturn(run func(ctx context.Context, imageID uuid.UUID) error) *MockImageRepository_DeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) FindByID(ctx context.Context, imageID uuid.UUID) ([]*models.Image, error) {
	ret := _mock.Called(ctx, imageID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 []*models.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*models.Image, error)); ok {
		return returnFunc(ctx, imageID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*models.Image); ok {
		r0 = returnFunc(ctx, imageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, imageID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockImageRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - imageID uuid.UUID
func (_e *MockImageRepository_Expecter) FindByID(ctx interface{}, imageID interface{}) *MockImageRepository_FindByID_Call {
	return &MockImageRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, imageID)}
}

func (_c *MockImageRepository_FindByID_Call) Run(run func(ctx context.Context, imageID uuid.UUID)) *MockImageRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageRepository_FindByID_Call) Return(images []*models.Image, err error) *MockImageRepository_FindByID_Call {
	_c.Call.Return(images, err)
	return _c
}

func (_c *MockImageRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, imageID uuid.UUID) ([]*models.Image, error)) *MockImageRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDAndSize provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) FindByIDAndSize(ctx context.Context, imageID uuid.UUID, size models.ImageSize) (*models.Image, error) {
	ret := _mock.Called(ctx, imageID, size)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDAndSize")
	}

	var r0 *models.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.ImageSize) (*models.Image, error)); ok {
		return returnFunc(ctx, imageID, size)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.ImageSize) *models.Image); ok {
		r0 = returnFunc(ctx, imageID, size)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, models.ImageSize) error); ok {
		r1 = returnFunc(ctx, imageID, size)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageRepository_FindByIDAndSize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDAndSize'
type MockImageRepository_FindByIDAndSize_Call struct {
	*mock.Call
}

// FindByIDAndSize is a helper method to define mock.On call
//   - ctx context.Context
//   - imageID uuid.UUID
//   - size models.ImageSize
func (_e *MockImageRepository_Expecter) FindByIDAndSize(ctx interface{}, imageID interface{}, size interface{}) *MockImageRepository_FindByIDAndSize_Call {
	return &MockImageRepository_FindByIDAndSize_Call{Call: _e.mock.On("FindByIDAndSize", ctx, imageID, size)}
}

func (_c *MockImageRepository_FindByIDAndSize_Call) Run(run func(ctx context.Context, imageID uuid.UUID, size models.ImageSize)) *MockImageRepository_FindByIDAndSize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 models.ImageSize
		if args[2] != nil {
			arg2 = args[2].(models.ImageSize)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockImageRepository_FindByIDAndSize_Call) Return(image *models.Image, err error) *MockImageRepository_FindByIDAndSize_Call {
	_c.Call.Return(image, err)
	return _c
}

func (_c *MockImageRepository_FindByIDAndSize_Call) RunAndReturn(run func(ctx context.Context, imageID uuid.UUID, size models.ImageSize) (*models.Image, error)) *MockImageRepository_FindByIDAndSize_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDIncludingPending provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) FindByIDIncludingPending(ctx context.Context, imageID uuid.UUID) ([]*models.Image, error) {
	ret := _mock.Called(ctx, imageID)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDIncludingPending")
	}

	var r0 []*models.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*models.Image, error)); ok {
		return returnFunc(ctx, imageID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*models.Image); ok {
		r0 = returnFunc(ctx, imageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, imageID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockImageRepository_FindByIDIncludingPending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDIncludingPending'
type MockImageRepository_FindByIDIncludingPending_Call struct {
	*mock.Call
}

// FindByIDIncludingPending is a helper method to define mock.On call
//   - ctx context.Context
//   - imageID uuid.UUID
func (_e *MockImageRepository_Expecter) FindByIDIncludingPending(ctx interface{}, imageID interface{}) *MockImageRepository_FindByIDIncludingPending_Call {
	return &MockImageRepository_FindByIDIncludingPending_Call{Call: _e.mock.On("FindByIDIncludingPending", ctx, imageID)}
}

func (_c *MockImageRepository_FindByIDIncludingPending_Call) Run(run func(ctx context.Context, imageID uuid.UUID)) *MockImageRepository_FindByIDIncludingPending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockImageRepository_FindByIDIncludingPending_Call) Return(images []*models.Image, err error) *MockImageRepository_FindByIDIncludingPending_Call {
	_c.Call.Return(images, err)
	return _c
}

func (_c *MockImageRepository_FindByIDIncludingPending_Call) RunAndReturn(run func(ctx context.Context, imageID uuid.UUID) ([]*models.Image, error)) *MockImageRepository_FindByIDIncludingPending_Call {
	_c.Call.Return(run)
	return _c
}

// MarkFailed provides a mock function for the type MockImageRepository
func (_mock *MockImageRepository) MarkFailed(ctx context.Context, imageID uuid.UUID, size models.ImageSize) error {
	ret := _mock.Called(ctx, imageID, size)

	if len(ret) == 0 {
		panic("no return value specified for MarkFailed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.ImageSize) error); ok {
		r0 = returnFunc(ctx, imageID, size)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockImageRepository_MarkFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkFailed'
type MockImageRepository_MarkFailed_Call struct {
	*mock.Call
}

// MarkFailed is a helper method to define mock.On call
//   - ctx context.Context
//   - imageID uuid.UUID
//   - size models.ImageSize
func (_e *MockImageRepository_Expecter) MarkFailed(ctx interface{}, imageID interface{}, size interface{}) *MockImageRepository_MarkFailed_Call {
	return &MockImageRepository_MarkFailed_Call{Call: _e.mock.On("MarkFailed", ctx, imageID, size)}
}

func (_c *MockImageRepository_MarkFailed_Call) Run(run func(ctx context.Context, imageID uuid.UUID, size models.ImageSize)) *MockImageRepository_MarkFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 models.ImageSize
		if args[2] != nil {
			arg2 = args[2].(models.ImageSize)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockImageRepository_MarkFailed_Call) Return(err error) *MockImageRepository_MarkFailed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockImageRepository_MarkFailed_Call) RunAndReturn(run func(ctx context.Context, imageID uuid.UUID, size models.ImageSize) error) *MockImageRepository_MarkFailed_Call {
	_c.Call.Return(run)
	return _c
}
