/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  HealthcheckQueryResponse,
  Healthcheck500,
} from "../../types/types.gen.ts";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const healthcheckQueryKey = () => [{ url: "/healthcheck" }] as const;

export type HealthcheckQueryKey = ReturnType<typeof healthcheckQueryKey>;

/**
 * @description Returns OK if the server is running and database is healthy
 * @summary Healthcheck endpoint
 * {@link /healthcheck}
 */
export async function healthcheck(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    HealthcheckQueryResponse,
    ResponseErrorConfig<Healthcheck500>,
    unknown
  >({ method: "GET", url: `/healthcheck`, ...requestConfig });
  return res.data;
}

export function healthcheckQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = healthcheckQueryKey();
  return queryOptions<
    HealthcheckQueryResponse,
    ResponseErrorConfig<Healthcheck500>,
    HealthcheckQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return healthcheck(config);
    },
  });
}

/**
 * @description Returns OK if the server is running and database is healthy
 * @summary Healthcheck endpoint
 * {@link /healthcheck}
 */
export function useHealthcheck<
  TData = HealthcheckQueryResponse,
  TQueryData = HealthcheckQueryResponse,
  TQueryKey extends QueryKey = HealthcheckQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        HealthcheckQueryResponse,
        ResponseErrorConfig<Healthcheck500>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? healthcheckQueryKey();

  const query = useQuery(
    {
      ...healthcheckQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Healthcheck500>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
