/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  HealthcheckQueryResponse,
  Healthcheck500,
} from "../../types/types.gen.ts";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const healthcheckSuspenseQueryKey = () =>
  [{ url: "/healthcheck" }] as const;

export type HealthcheckSuspenseQueryKey = ReturnType<
  typeof healthcheckSuspenseQueryKey
>;

/**
 * @description Returns OK if the server is running and database is healthy
 * @summary Healthcheck endpoint
 * {@link /healthcheck}
 */
export async function healthcheckSuspense(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    HealthcheckQueryResponse,
    ResponseErrorConfig<Healthcheck500>,
    unknown
  >({ method: "GET", url: `/healthcheck`, ...requestConfig });
  return res.data;
}

export function healthcheckSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = healthcheckSuspenseQueryKey();
  return queryOptions<
    HealthcheckQueryResponse,
    ResponseErrorConfig<Healthcheck500>,
    HealthcheckQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return healthcheckSuspense(config);
    },
  });
}

/**
 * @description Returns OK if the server is running and database is healthy
 * @summary Healthcheck endpoint
 * {@link /healthcheck}
 */
export function useHealthcheckSuspense<
  TData = HealthcheckQueryResponse,
  TQueryKey extends QueryKey = HealthcheckSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        HealthcheckQueryResponse,
        ResponseErrorConfig<Healthcheck500>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? healthcheckSuspenseQueryKey();

  const query = useSuspenseQuery(
    {
      ...healthcheckSuspenseQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Healthcheck500>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
