/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  GetTripActivityFeedQueryResponse,
  GetTripActivityFeedPathParams,
  GetTripActivityFeed400,
  GetTripActivityFeed401,
  GetTripActivityFeed500,
} from "../../types/types.gen.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getTripActivityFeedQueryKey = (
  tripID: GetTripActivityFeedPathParams["tripID"],
) =>
  [
    { url: "/api/v1/trips/:tripID/activity", params: { tripID: tripID } },
  ] as const;

export type GetTripActivityFeedQueryKey = ReturnType<
  typeof getTripActivityFeedQueryKey
>;

/**
 * @description Returns all unread events in the caller's trip feed. Events persist until explicitly dismissed via the mark-read endpoint.
 * @summary Get trip activity feed
 * {@link /api/v1/trips/:tripID/activity}
 */
export async function getTripActivityFeed(
  tripID: GetTripActivityFeedPathParams["tripID"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetTripActivityFeedQueryResponse,
    ResponseErrorConfig<
      GetTripActivityFeed400 | GetTripActivityFeed401 | GetTripActivityFeed500
    >,
    unknown
  >({
    method: "GET",
    url: `/api/v1/trips/${tripID}/activity`,
    ...requestConfig,
  });
  return res.data;
}

export function getTripActivityFeedQueryOptions(
  tripID: GetTripActivityFeedPathParams["tripID"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getTripActivityFeedQueryKey(tripID);
  return queryOptions<
    GetTripActivityFeedQueryResponse,
    ResponseErrorConfig<
      GetTripActivityFeed400 | GetTripActivityFeed401 | GetTripActivityFeed500
    >,
    GetTripActivityFeedQueryResponse,
    typeof queryKey
  >({
    enabled: !!tripID,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getTripActivityFeed(tripID, config);
    },
  });
}

/**
 * @description Returns all unread events in the caller's trip feed. Events persist until explicitly dismissed via the mark-read endpoint.
 * @summary Get trip activity feed
 * {@link /api/v1/trips/:tripID/activity}
 */
export function useGetTripActivityFeed<
  TData = GetTripActivityFeedQueryResponse,
  TQueryData = GetTripActivityFeedQueryResponse,
  TQueryKey extends QueryKey = GetTripActivityFeedQueryKey,
>(
  tripID: GetTripActivityFeedPathParams["tripID"],
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetTripActivityFeedQueryResponse,
        ResponseErrorConfig<
          | GetTripActivityFeed400
          | GetTripActivityFeed401
          | GetTripActivityFeed500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getTripActivityFeedQueryKey(tripID);

  const query = useQuery(
    {
      ...getTripActivityFeedQueryOptions(tripID, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      GetTripActivityFeed400 | GetTripActivityFeed401 | GetTripActivityFeed500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
