/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  MarkActivityEventReadMutationResponse,
  MarkActivityEventReadPathParams,
  MarkActivityEventRead400,
  MarkActivityEventRead401,
  MarkActivityEventRead500,
} from "../../types/types.gen.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const markActivityEventReadMutationKey = () =>
  [{ url: "/api/v1/trips/:tripID/activity/:eventID" }] as const;

export type MarkActivityEventReadMutationKey = ReturnType<
  typeof markActivityEventReadMutationKey
>;

/**
 * @description Removes a specific event from the caller's trip activity feed.
 * @summary Mark activity event as read
 * {@link /api/v1/trips/:tripID/activity/:eventID}
 */
export async function markActivityEventRead(
  tripID: MarkActivityEventReadPathParams["tripID"],
  eventID: MarkActivityEventReadPathParams["eventID"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    MarkActivityEventReadMutationResponse,
    ResponseErrorConfig<
      | MarkActivityEventRead400
      | MarkActivityEventRead401
      | MarkActivityEventRead500
    >,
    unknown
  >({
    method: "DELETE",
    url: `/api/v1/trips/${tripID}/activity/${eventID}`,
    ...requestConfig,
  });
  return res.data;
}

export function markActivityEventReadMutationOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const mutationKey = markActivityEventReadMutationKey();
  return mutationOptions<
    MarkActivityEventReadMutationResponse,
    ResponseErrorConfig<
      | MarkActivityEventRead400
      | MarkActivityEventRead401
      | MarkActivityEventRead500
    >,
    {
      tripID: MarkActivityEventReadPathParams["tripID"];
      eventID: MarkActivityEventReadPathParams["eventID"];
    },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ tripID, eventID }) => {
      return markActivityEventRead(tripID, eventID, config);
    },
  });
}

/**
 * @description Removes a specific event from the caller's trip activity feed.
 * @summary Mark activity event as read
 * {@link /api/v1/trips/:tripID/activity/:eventID}
 */
export function useMarkActivityEventRead<TContext>(
  options: {
    mutation?: UseMutationOptions<
      MarkActivityEventReadMutationResponse,
      ResponseErrorConfig<
        | MarkActivityEventRead400
        | MarkActivityEventRead401
        | MarkActivityEventRead500
      >,
      {
        tripID: MarkActivityEventReadPathParams["tripID"];
        eventID: MarkActivityEventReadPathParams["eventID"];
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? markActivityEventReadMutationKey();

  const baseOptions = markActivityEventReadMutationOptions(
    config,
  ) as UseMutationOptions<
    MarkActivityEventReadMutationResponse,
    ResponseErrorConfig<
      | MarkActivityEventRead400
      | MarkActivityEventRead401
      | MarkActivityEventRead500
    >,
    {
      tripID: MarkActivityEventReadPathParams["tripID"];
      eventID: MarkActivityEventReadPathParams["eventID"];
    },
    TContext
  >;

  return useMutation<
    MarkActivityEventReadMutationResponse,
    ResponseErrorConfig<
      | MarkActivityEventRead400
      | MarkActivityEventRead401
      | MarkActivityEventRead500
    >,
    {
      tripID: MarkActivityEventReadPathParams["tripID"];
      eventID: MarkActivityEventReadPathParams["eventID"];
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    MarkActivityEventReadMutationResponse,
    ResponseErrorConfig<
      | MarkActivityEventRead400
      | MarkActivityEventRead401
      | MarkActivityEventRead500
    >,
    {
      tripID: MarkActivityEventReadPathParams["tripID"];
      eventID: MarkActivityEventReadPathParams["eventID"];
    },
    TContext
  >;
}
