/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  GoogleMapsHealthQueryResponse,
  GoogleMapsHealth500,
} from "../../types/types.gen.ts";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const googleMapsHealthSuspenseQueryKey = () =>
  [{ url: "/api/v1/search/places/health" }] as const;

export type GoogleMapsHealthSuspenseQueryKey = ReturnType<
  typeof googleMapsHealthSuspenseQueryKey
>;

/**
 * @description Checks if Google Maps API is connected and accessible
 * @summary Google Maps health check
 * {@link /api/v1/search/places/health}
 */
export async function googleMapsHealthSuspense(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GoogleMapsHealthQueryResponse,
    ResponseErrorConfig<GoogleMapsHealth500>,
    unknown
  >({ method: "GET", url: `/api/v1/search/places/health`, ...requestConfig });
  return res.data;
}

export function googleMapsHealthSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = googleMapsHealthSuspenseQueryKey();
  return queryOptions<
    GoogleMapsHealthQueryResponse,
    ResponseErrorConfig<GoogleMapsHealth500>,
    GoogleMapsHealthQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return googleMapsHealthSuspense(config);
    },
  });
}

/**
 * @description Checks if Google Maps API is connected and accessible
 * @summary Google Maps health check
 * {@link /api/v1/search/places/health}
 */
export function useGoogleMapsHealthSuspense<
  TData = GoogleMapsHealthQueryResponse,
  TQueryKey extends QueryKey = GoogleMapsHealthSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GoogleMapsHealthQueryResponse,
        ResponseErrorConfig<GoogleMapsHealth500>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? googleMapsHealthSuspenseQueryKey();

  const query = useSuspenseQuery(
    {
      ...googleMapsHealthSuspenseQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<GoogleMapsHealth500>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
