/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  GetPlaceDetailsMutationRequest,
  GetPlaceDetailsMutationResponse,
  GetPlaceDetails400,
  GetPlaceDetails500,
} from "../../types/types.gen.ts";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const getPlaceDetailsMutationKey = () =>
  [{ url: "/api/v1/search/places/details" }] as const;

export type GetPlaceDetailsMutationKey = ReturnType<
  typeof getPlaceDetailsMutationKey
>;

/**
 * @description Retrieves detailed information about a specific place using Google Maps Places API. Accepts either a place_id (from typeahead results) or input text for direct search. Returns address, coordinates, photos, ratings, opening hours, and more.
 * @summary Get detailed information about a place
 * {@link /api/v1/search/places/details}
 */
export async function getPlaceDetails(
  data?: GetPlaceDetailsMutationRequest,
  config: Partial<RequestConfig<GetPlaceDetailsMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    GetPlaceDetailsMutationResponse,
    ResponseErrorConfig<GetPlaceDetails400 | GetPlaceDetails500>,
    GetPlaceDetailsMutationRequest
  >({
    method: "POST",
    url: `/api/v1/search/places/details`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function getPlaceDetailsMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<GetPlaceDetailsMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = getPlaceDetailsMutationKey();
  return mutationOptions<
    GetPlaceDetailsMutationResponse,
    ResponseErrorConfig<GetPlaceDetails400 | GetPlaceDetails500>,
    { data?: GetPlaceDetailsMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return getPlaceDetails(data, config);
    },
  });
}

/**
 * @description Retrieves detailed information about a specific place using Google Maps Places API. Accepts either a place_id (from typeahead results) or input text for direct search. Returns address, coordinates, photos, ratings, opening hours, and more.
 * @summary Get detailed information about a place
 * {@link /api/v1/search/places/details}
 */
export function useGetPlaceDetails<TContext>(
  options: {
    mutation?: UseMutationOptions<
      GetPlaceDetailsMutationResponse,
      ResponseErrorConfig<GetPlaceDetails400 | GetPlaceDetails500>,
      { data?: GetPlaceDetailsMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<GetPlaceDetailsMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? getPlaceDetailsMutationKey();

  const baseOptions = getPlaceDetailsMutationOptions(
    config,
  ) as UseMutationOptions<
    GetPlaceDetailsMutationResponse,
    ResponseErrorConfig<GetPlaceDetails400 | GetPlaceDetails500>,
    { data?: GetPlaceDetailsMutationRequest },
    TContext
  >;

  return useMutation<
    GetPlaceDetailsMutationResponse,
    ResponseErrorConfig<GetPlaceDetails400 | GetPlaceDetails500>,
    { data?: GetPlaceDetailsMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    GetPlaceDetailsMutationResponse,
    ResponseErrorConfig<GetPlaceDetails400 | GetPlaceDetails500>,
    { data?: GetPlaceDetailsMutationRequest },
    TContext
  >;
}
