/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  TypeaheadPlacesQueryResponse,
  TypeaheadPlacesQueryParams,
  TypeaheadPlaces400,
  TypeaheadPlaces500,
} from "../../types/types.gen.ts";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const typeaheadPlacesSuspenseQueryKey = (
  params: TypeaheadPlacesQueryParams,
) =>
  [
    { url: "/api/v1/search/places/typeahead" },
    ...(params ? [params] : []),
  ] as const;

export type TypeaheadPlacesSuspenseQueryKey = ReturnType<
  typeof typeaheadPlacesSuspenseQueryKey
>;

/**
 * @description Quick typeahead/autocomplete endpoint for real-time place search as users type. Returns a list of place predictions with place IDs that can be used to fetch detailed information.
 * @summary Typeahead search for places
 * {@link /api/v1/search/places/typeahead}
 */
export async function typeaheadPlacesSuspense(
  params: TypeaheadPlacesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    TypeaheadPlacesQueryResponse,
    ResponseErrorConfig<TypeaheadPlaces400 | TypeaheadPlaces500>,
    unknown
  >({
    method: "GET",
    url: `/api/v1/search/places/typeahead`,
    params,
    ...requestConfig,
  });
  return res.data;
}

export function typeaheadPlacesSuspenseQueryOptions(
  params: TypeaheadPlacesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = typeaheadPlacesSuspenseQueryKey(params);
  return queryOptions<
    TypeaheadPlacesQueryResponse,
    ResponseErrorConfig<TypeaheadPlaces400 | TypeaheadPlaces500>,
    TypeaheadPlacesQueryResponse,
    typeof queryKey
  >({
    enabled: !!params,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return typeaheadPlacesSuspense(params, config);
    },
  });
}

/**
 * @description Quick typeahead/autocomplete endpoint for real-time place search as users type. Returns a list of place predictions with place IDs that can be used to fetch detailed information.
 * @summary Typeahead search for places
 * {@link /api/v1/search/places/typeahead}
 */
export function useTypeaheadPlacesSuspense<
  TData = TypeaheadPlacesQueryResponse,
  TQueryKey extends QueryKey = TypeaheadPlacesSuspenseQueryKey,
>(
  params: TypeaheadPlacesQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        TypeaheadPlacesQueryResponse,
        ResponseErrorConfig<TypeaheadPlaces400 | TypeaheadPlaces500>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? typeaheadPlacesSuspenseQueryKey(params);

  const query = useSuspenseQuery(
    {
      ...typeaheadPlacesSuspenseQueryOptions(params, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<TypeaheadPlaces400 | TypeaheadPlaces500>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
