/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  ErrsAPIError,
  ModelsCreateUserRequest,
  ModelsUpdateUserRequest,
  ModelsUser,
  CreateUser201,
  CreateUser400,
  CreateUser422,
  CreateUser500,
  CreateUserMutationRequest,
  CreateUserMutationResponse,
  GetUserPathParams,
  GetUser200,
  GetUser400,
  GetUser404,
  GetUser500,
  GetUserQueryResponse,
  DeleteUserPathParams,
  DeleteUser204,
  DeleteUser400,
  DeleteUser404,
  DeleteUser500,
  DeleteUserMutationResponse,
  UpdateUserPathParams,
  UpdateUser200,
  UpdateUser400,
  UpdateUser404,
  UpdateUser422,
  UpdateUser500,
  UpdateUserMutationRequest,
  UpdateUserMutationResponse,
  GetHealthcheck200,
  GetHealthcheckQueryResponse,
} from "./types.gen.ts";
import { z } from "zod/v4";

export const errsAPIErrorSchema = z.object({
  message: z.optional(z.any()),
  statusCode: z.optional(z.int()),
}) as unknown as z.ZodType<ErrsAPIError>;

export const modelsCreateUserRequestSchema = z.object({
  email: z.string(),
  name: z.string(),
}) as unknown as z.ZodType<ModelsCreateUserRequest>;

export const modelsUpdateUserRequestSchema = z.object({
  email: z.optional(z.string()),
  name: z.optional(z.string().min(1)),
}) as unknown as z.ZodType<ModelsUpdateUserRequest>;

export const modelsUserSchema = z.object({
  email: z.optional(z.string()),
  id: z.optional(z.string()),
  name: z.optional(z.string()),
}) as unknown as z.ZodType<ModelsUser>;

/**
 * @description Created
 */
export const createUser201Schema = z.lazy(
  () => modelsUserSchema,
) as unknown as z.ZodType<CreateUser201>;

/**
 * @description Bad Request
 */
export const createUser400Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<CreateUser400>;

/**
 * @description Unprocessable Entity
 */
export const createUser422Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<CreateUser422>;

/**
 * @description Internal Server Error
 */
export const createUser500Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<CreateUser500>;

/**
 * @description Create user request
 */
export const createUserMutationRequestSchema = z.lazy(
  () => modelsCreateUserRequestSchema,
) as unknown as z.ZodType<CreateUserMutationRequest>;

export const createUserMutationResponseSchema = z.lazy(
  () => createUser201Schema,
) as unknown as z.ZodType<CreateUserMutationResponse>;

export const getUserPathParamsSchema = z.object({
  userID: z.string().describe("User ID"),
}) as unknown as z.ZodType<GetUserPathParams>;

/**
 * @description OK
 */
export const getUser200Schema = z.lazy(
  () => modelsUserSchema,
) as unknown as z.ZodType<GetUser200>;

/**
 * @description Bad Request
 */
export const getUser400Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<GetUser400>;

/**
 * @description Not Found
 */
export const getUser404Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<GetUser404>;

/**
 * @description Internal Server Error
 */
export const getUser500Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<GetUser500>;

export const getUserQueryResponseSchema = z.lazy(
  () => getUser200Schema,
) as unknown as z.ZodType<GetUserQueryResponse>;

export const deleteUserPathParamsSchema = z.object({
  userID: z.string().describe("User ID"),
}) as unknown as z.ZodType<DeleteUserPathParams>;

/**
 * @description No Content
 */
export const deleteUser204Schema =
  z.any() as unknown as z.ZodType<DeleteUser204>;

/**
 * @description Bad Request
 */
export const deleteUser400Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<DeleteUser400>;

/**
 * @description Not Found
 */
export const deleteUser404Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<DeleteUser404>;

/**
 * @description Internal Server Error
 */
export const deleteUser500Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<DeleteUser500>;

export const deleteUserMutationResponseSchema = z.lazy(
  () => deleteUser204Schema,
) as unknown as z.ZodType<DeleteUserMutationResponse>;

export const updateUserPathParamsSchema = z.object({
  userID: z.string().describe("User ID"),
}) as unknown as z.ZodType<UpdateUserPathParams>;

/**
 * @description OK
 */
export const updateUser200Schema = z.lazy(
  () => modelsUserSchema,
) as unknown as z.ZodType<UpdateUser200>;

/**
 * @description Bad Request
 */
export const updateUser400Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<UpdateUser400>;

/**
 * @description Not Found
 */
export const updateUser404Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<UpdateUser404>;

/**
 * @description Unprocessable Entity
 */
export const updateUser422Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<UpdateUser422>;

/**
 * @description Internal Server Error
 */
export const updateUser500Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<UpdateUser500>;

/**
 * @description Update user request
 */
export const updateUserMutationRequestSchema = z.lazy(
  () => modelsUpdateUserRequestSchema,
) as unknown as z.ZodType<UpdateUserMutationRequest>;

export const updateUserMutationResponseSchema = z.lazy(
  () => updateUser200Schema,
) as unknown as z.ZodType<UpdateUserMutationResponse>;

/**
 * @description ok
 */
export const getHealthcheck200Schema =
  z.string() as unknown as z.ZodType<GetHealthcheck200>;

export const getHealthcheckQueryResponseSchema = z.lazy(
  () => getHealthcheck200Schema,
) as unknown as z.ZodType<GetHealthcheckQueryResponse>;
