/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  ErrsAPIError,
  ModelsImageSize,
  ModelsConfirmUploadRequest,
  ModelsConfirmUploadResponse,
  ModelsCreateMembershipRequest,
  ModelsCreateTripRequest,
  ModelsCreateUserRequest,
  ModelsGetFileResponse,
  ModelsGetFileAllSizesResponse,
  ModelsMembership,
  ModelsGetTripMembersResponse,
  ModelsNotificationError,
  ModelsNotificationResponse,
  ModelsS3HealthCheckResponse,
  ModelsSendBulkNotificationRequest,
  ModelsSendNotificationRequest,
  ModelsSizedUploadURL,
  ModelsTrip,
  ModelsTripCursorPageResult,
  ModelsUpdateMembershipRequest,
  ModelsUpdateTripRequest,
  ModelsUpdateUserRequest,
  ModelsUploadURLRequest,
  ModelsUploadURLResponse,
  ModelsUser,
  ConfirmUpload200,
  ConfirmUpload400,
  ConfirmUpload404,
  ConfirmUpload422,
  ConfirmUpload500,
  ConfirmUploadMutationRequest,
  ConfirmUploadMutationResponse,
  CheckS3Health200,
  CheckS3Health503,
  CheckS3HealthQueryResponse,
  CreateUploadURLs201,
  CreateUploadURLs400,
  CreateUploadURLs422,
  CreateUploadURLs500,
  CreateUploadURLsMutationRequest,
  CreateUploadURLsMutationResponse,
  GetFileAllSizesPathParams,
  GetFileAllSizes200,
  GetFileAllSizes400,
  GetFileAllSizes404,
  GetFileAllSizes500,
  GetFileAllSizesQueryResponse,
  GetFilePathParams,
  GetFile200,
  GetFile400,
  GetFile404,
  GetFile500,
  GetFileQueryResponse,
  AddMember201,
  AddMember400,
  AddMember422,
  AddMember500,
  AddMemberMutationRequest,
  AddMemberMutationResponse,
  SendNotification200,
  SendNotification400,
  SendNotification422,
  SendNotification500,
  SendNotificationMutationRequest,
  SendNotificationMutationResponse,
  SendBulkNotification200,
  SendBulkNotification400,
  SendBulkNotification422,
  SendBulkNotification500,
  SendBulkNotificationMutationRequest,
  SendBulkNotificationMutationResponse,
  GetAllTripsQueryParams,
  GetAllTrips200,
  GetAllTrips400,
  GetAllTrips500,
  GetAllTripsQueryResponse,
  CreateTrip201,
  CreateTrip400,
  CreateTrip422,
  CreateTrip500,
  CreateTripMutationRequest,
  CreateTripMutationResponse,
  GetTripPathParams,
  GetTrip200,
  GetTrip400,
  GetTrip404,
  GetTrip500,
  GetTripQueryResponse,
  DeleteTripPathParams,
  DeleteTrip204,
  DeleteTrip400,
  DeleteTrip404,
  DeleteTrip500,
  DeleteTripMutationResponse,
  UpdateTripPathParams,
  UpdateTrip200,
  UpdateTrip400,
  UpdateTrip404,
  UpdateTrip422,
  UpdateTrip500,
  UpdateTripMutationRequest,
  UpdateTripMutationResponse,
  GetTripMembersPathParams,
  GetTripMembers200,
  GetTripMembers400,
  GetTripMembers500,
  GetTripMembersQueryResponse,
  GetMembershipPathParams,
  GetMembership200,
  GetMembership400,
  GetMembership404,
  GetMembership500,
  GetMembershipQueryResponse,
  RemoveMemberPathParams,
  RemoveMember204,
  RemoveMember400,
  RemoveMember404,
  RemoveMember500,
  RemoveMemberMutationResponse,
  UpdateMembershipPathParams,
  UpdateMembership200,
  UpdateMembership400,
  UpdateMembership404,
  UpdateMembership422,
  UpdateMembership500,
  UpdateMembershipMutationRequest,
  UpdateMembershipMutationResponse,
  DemoteFromAdminPathParams,
  DemoteFromAdmin200,
  DemoteFromAdmin400,
  DemoteFromAdmin404,
  DemoteFromAdmin500,
  DemoteFromAdminMutationResponse,
  PromoteToAdminPathParams,
  PromoteToAdmin200,
  PromoteToAdmin400,
  PromoteToAdmin404,
  PromoteToAdmin500,
  PromoteToAdminMutationResponse,
  CreateUser201,
  CreateUser400,
  CreateUser422,
  CreateUser500,
  CreateUserMutationRequest,
  CreateUserMutationResponse,
  GetCurrentUser200,
  GetCurrentUser401,
  GetCurrentUser404,
  GetCurrentUser500,
  GetCurrentUserQueryResponse,
  GetUserPathParams,
  GetUser200,
  GetUser400,
  GetUser404,
  GetUser500,
  GetUserQueryResponse,
  DeleteUserPathParams,
  DeleteUser204,
  DeleteUser400,
  DeleteUser404,
  DeleteUser500,
  DeleteUserMutationResponse,
  UpdateUserPathParams,
  UpdateUser200,
  UpdateUser400,
  UpdateUser404,
  UpdateUser422,
  UpdateUser500,
  UpdateUserMutationRequest,
  UpdateUserMutationResponse,
  GetUserTripsPathParams,
  GetUserTrips200,
  GetUserTrips400,
  GetUserTrips500,
  GetUserTripsQueryResponse,
  Healthcheck200,
  Healthcheck500,
  HealthcheckQueryResponse,
} from "./types.gen.ts";
import { z } from "zod/v4";

export const errsAPIErrorSchema = z.object({
  message: z.optional(z.any()),
  statusCode: z.optional(z.int()),
}) as unknown as z.ZodType<ErrsAPIError>;

export const modelsImageSizeSchema = z.enum([
  "large",
  "medium",
  "small",
]) as unknown as z.ZodType<ModelsImageSize>;

export const modelsConfirmUploadRequestSchema = z.object({
  imageId: z.string(),
  get size() {
    return modelsImageSizeSchema
      .describe("Optional: if nil, confirm all sizes")
      .optional();
  },
}) as unknown as z.ZodType<ModelsConfirmUploadRequest>;

export const modelsConfirmUploadResponseSchema = z.object({
  confirmed: z.optional(z.int()),
  imageId: z.optional(z.string()),
  status: z.optional(z.string()),
}) as unknown as z.ZodType<ModelsConfirmUploadResponse>;

export const modelsCreateMembershipRequestSchema = z.object({
  budget_max: z.int().min(0),
  budget_min: z.int().min(0),
  is_admin: z.optional(z.boolean()),
  trip_id: z.string(),
  user_id: z.string(),
}) as unknown as z.ZodType<ModelsCreateMembershipRequest>;

export const modelsCreateTripRequestSchema = z.object({
  budget_max: z.int().min(0),
  budget_min: z.int().min(0),
  name: z.string().min(1),
}) as unknown as z.ZodType<ModelsCreateTripRequest>;

export const modelsCreateUserRequestSchema = z.object({
  name: z.string().min(1),
  phone_number: z.string(),
  username: z.string(),
}) as unknown as z.ZodType<ModelsCreateUserRequest>;

export const modelsGetFileResponseSchema = z.object({
  contentType: z.optional(z.string()),
  imageId: z.optional(z.string()),
  get size() {
    return modelsImageSizeSchema.optional();
  },
  url: z.optional(z.string()),
}) as unknown as z.ZodType<ModelsGetFileResponse>;

export const modelsGetFileAllSizesResponseSchema = z.object({
  get files() {
    return z.array(modelsGetFileResponseSchema).optional();
  },
  imageId: z.optional(z.string()),
}) as unknown as z.ZodType<ModelsGetFileAllSizesResponse>;

export const modelsMembershipSchema = z.object({
  availability: z.optional(z.object({}).catchall(z.any())),
  budget_max: z.optional(z.int()),
  budget_min: z.optional(z.int()),
  created_at: z.optional(z.string()),
  is_admin: z.optional(z.boolean()),
  trip_id: z.optional(z.string()),
  updated_at: z.optional(z.string()),
  user_id: z.optional(z.string()),
}) as unknown as z.ZodType<ModelsMembership>;

export const modelsGetTripMembersResponseSchema = z.object({
  get data() {
    return z.array(modelsMembershipSchema).optional();
  },
}) as unknown as z.ZodType<ModelsGetTripMembersResponse>;

export const modelsNotificationErrorSchema = z.object({
  message: z.optional(z.string()),
  token: z.optional(z.string()),
  user_id: z.optional(z.string()),
}) as unknown as z.ZodType<ModelsNotificationError>;

export const modelsNotificationResponseSchema = z.object({
  get errors() {
    return z.array(modelsNotificationErrorSchema).optional();
  },
  failure_count: z.optional(z.int()),
  success_count: z.optional(z.int()),
}) as unknown as z.ZodType<ModelsNotificationResponse>;

export const modelsS3HealthCheckResponseSchema = z.object({
  bucketName: z.optional(z.string()),
  error: z.optional(
    z
      .string()
      .describe(
        'Error contains the underlying error message when status is "unhealthy"',
      ),
  ),
  region: z.optional(z.string()),
  status: z.optional(z.string()),
}) as unknown as z.ZodType<ModelsS3HealthCheckResponse>;

export const modelsSendBulkNotificationRequestSchema = z.object({
  body: z.string().min(1).max(500),
  data: z.optional(z.object({}).catchall(z.any())),
  title: z.string().min(1).max(100),
  user_ids: z.array(z.string()).min(1).max(1000),
}) as unknown as z.ZodType<ModelsSendBulkNotificationRequest>;

export const modelsSendNotificationRequestSchema = z.object({
  body: z.string().min(1).max(500),
  data: z.optional(z.object({}).catchall(z.any())),
  title: z.string().min(1).max(100),
  user_id: z.string(),
}) as unknown as z.ZodType<ModelsSendNotificationRequest>;

export const modelsSizedUploadURLSchema = z.object({
  get size() {
    return modelsImageSizeSchema.optional();
  },
  url: z.optional(z.string()),
}) as unknown as z.ZodType<ModelsSizedUploadURL>;

export const modelsTripSchema = z.object({
  budget_max: z.optional(z.int()),
  budget_min: z.optional(z.int()),
  created_at: z.optional(z.string()),
  id: z.optional(z.string()),
  name: z.optional(z.string()),
  updated_at: z.optional(z.string()),
}) as unknown as z.ZodType<ModelsTrip>;

export const modelsTripCursorPageResultSchema = z.object({
  get items() {
    return z.array(modelsTripSchema).optional();
  },
  limit: z.optional(z.int()),
  next_cursor: z.optional(z.string()),
}) as unknown as z.ZodType<ModelsTripCursorPageResult>;

export const modelsUpdateMembershipRequestSchema = z.object({
  budget_max: z.optional(z.int().min(0)),
  budget_min: z.optional(z.int().min(0)),
  is_admin: z.optional(z.boolean()),
}) as unknown as z.ZodType<ModelsUpdateMembershipRequest>;

export const modelsUpdateTripRequestSchema = z.object({
  budget_max: z.optional(z.int().min(0)),
  budget_min: z.optional(z.int().min(0)),
  name: z.optional(z.string().min(1)),
}) as unknown as z.ZodType<ModelsUpdateTripRequest>;

export const modelsUpdateUserRequestSchema = z.object({
  device_token: z.optional(z.string().max(200)),
  name: z.optional(z.string().min(1)),
  phone_number: z.optional(z.string()),
  profile_picture: z.optional(z.string()),
  timezone: z.optional(z.string()),
  username: z.optional(z.string()),
}) as unknown as z.ZodType<ModelsUpdateUserRequest>;

export const modelsUploadURLRequestSchema = z.object({
  contentType: z.string().min(1),
  fileKey: z.string().min(1),
  get sizes() {
    return z.array(modelsImageSizeSchema).min(1).max(3);
  },
}) as unknown as z.ZodType<ModelsUploadURLRequest>;

export const modelsUploadURLResponseSchema = z.object({
  expiresAt: z.optional(z.string()),
  fileKey: z.optional(z.string()),
  imageId: z.optional(z.string()),
  get uploadUrls() {
    return z.array(modelsSizedUploadURLSchema).optional();
  },
}) as unknown as z.ZodType<ModelsUploadURLResponse>;

export const modelsUserSchema = z.object({
  device_token: z.optional(z.string()),
  device_token_updated_at: z.optional(z.string()),
  id: z.optional(z.string()),
  name: z.optional(z.string()),
  phone_number: z.optional(z.string()),
  profile_picture: z.optional(z.string()),
  timezone: z.optional(z.string()),
  username: z.optional(z.string()),
}) as unknown as z.ZodType<ModelsUser>;

/**
 * @description OK
 */
export const confirmUpload200Schema = z.lazy(
  () => modelsConfirmUploadResponseSchema,
) as unknown as z.ZodType<ConfirmUpload200>;

/**
 * @description Bad Request
 */
export const confirmUpload400Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<ConfirmUpload400>;

/**
 * @description Not Found
 */
export const confirmUpload404Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<ConfirmUpload404>;

/**
 * @description Unprocessable Entity
 */
export const confirmUpload422Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<ConfirmUpload422>;

/**
 * @description Internal Server Error
 */
export const confirmUpload500Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<ConfirmUpload500>;

/**
 * @description Confirm upload request
 */
export const confirmUploadMutationRequestSchema = z.lazy(
  () => modelsConfirmUploadRequestSchema,
) as unknown as z.ZodType<ConfirmUploadMutationRequest>;

export const confirmUploadMutationResponseSchema = z.lazy(
  () => confirmUpload200Schema,
) as unknown as z.ZodType<ConfirmUploadMutationResponse>;

/**
 * @description OK
 */
export const checkS3Health200Schema = z.lazy(
  () => modelsS3HealthCheckResponseSchema,
) as unknown as z.ZodType<CheckS3Health200>;

/**
 * @description Service Unavailable
 */
export const checkS3Health503Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<CheckS3Health503>;

export const checkS3HealthQueryResponseSchema = z.lazy(
  () => checkS3Health200Schema,
) as unknown as z.ZodType<CheckS3HealthQueryResponse>;

/**
 * @description Created
 */
export const createUploadURLs201Schema = z.lazy(
  () => modelsUploadURLResponseSchema,
) as unknown as z.ZodType<CreateUploadURLs201>;

/**
 * @description Bad Request
 */
export const createUploadURLs400Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<CreateUploadURLs400>;

/**
 * @description Unprocessable Entity
 */
export const createUploadURLs422Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<CreateUploadURLs422>;

/**
 * @description Internal Server Error
 */
export const createUploadURLs500Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<CreateUploadURLs500>;

/**
 * @description Upload URL request
 */
export const createUploadURLsMutationRequestSchema = z.lazy(
  () => modelsUploadURLRequestSchema,
) as unknown as z.ZodType<CreateUploadURLsMutationRequest>;

export const createUploadURLsMutationResponseSchema = z.lazy(
  () => createUploadURLs201Schema,
) as unknown as z.ZodType<CreateUploadURLsMutationResponse>;

export const getFileAllSizesPathParamsSchema = z.object({
  imageId: z.string().describe("Image ID (UUID)"),
}) as unknown as z.ZodType<GetFileAllSizesPathParams>;

/**
 * @description OK
 */
export const getFileAllSizes200Schema = z.lazy(
  () => modelsGetFileAllSizesResponseSchema,
) as unknown as z.ZodType<GetFileAllSizes200>;

/**
 * @description Bad Request
 */
export const getFileAllSizes400Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<GetFileAllSizes400>;

/**
 * @description Not Found
 */
export const getFileAllSizes404Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<GetFileAllSizes404>;

/**
 * @description Internal Server Error
 */
export const getFileAllSizes500Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<GetFileAllSizes500>;

export const getFileAllSizesQueryResponseSchema = z.lazy(
  () => getFileAllSizes200Schema,
) as unknown as z.ZodType<GetFileAllSizesQueryResponse>;

export const getFilePathParamsSchema = z.object({
  imageId: z.string().describe("Image ID (UUID)"),
  size: z.string().describe("Image size (large, medium, small)"),
}) as unknown as z.ZodType<GetFilePathParams>;

/**
 * @description OK
 */
export const getFile200Schema = z.lazy(
  () => modelsGetFileResponseSchema,
) as unknown as z.ZodType<GetFile200>;

/**
 * @description Bad Request
 */
export const getFile400Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<GetFile400>;

/**
 * @description Not Found
 */
export const getFile404Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<GetFile404>;

/**
 * @description Internal Server Error
 */
export const getFile500Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<GetFile500>;

export const getFileQueryResponseSchema = z.lazy(
  () => getFile200Schema,
) as unknown as z.ZodType<GetFileQueryResponse>;

/**
 * @description Created
 */
export const addMember201Schema = z.lazy(
  () => modelsMembershipSchema,
) as unknown as z.ZodType<AddMember201>;

/**
 * @description Bad Request
 */
export const addMember400Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<AddMember400>;

/**
 * @description Unprocessable Entity
 */
export const addMember422Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<AddMember422>;

/**
 * @description Internal Server Error
 */
export const addMember500Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<AddMember500>;

/**
 * @description Create membership request
 */
export const addMemberMutationRequestSchema = z.lazy(
  () => modelsCreateMembershipRequestSchema,
) as unknown as z.ZodType<AddMemberMutationRequest>;

export const addMemberMutationResponseSchema = z.lazy(
  () => addMember201Schema,
) as unknown as z.ZodType<AddMemberMutationResponse>;

/**
 * @description OK
 */
export const sendNotification200Schema =
  z.any() as unknown as z.ZodType<SendNotification200>;

/**
 * @description Bad Request
 */
export const sendNotification400Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<SendNotification400>;

/**
 * @description Unprocessable Entity
 */
export const sendNotification422Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<SendNotification422>;

/**
 * @description Internal Server Error
 */
export const sendNotification500Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<SendNotification500>;

/**
 * @description Notification request
 */
export const sendNotificationMutationRequestSchema = z.lazy(
  () => modelsSendNotificationRequestSchema,
) as unknown as z.ZodType<SendNotificationMutationRequest>;

export const sendNotificationMutationResponseSchema = z.lazy(
  () => sendNotification200Schema,
) as unknown as z.ZodType<SendNotificationMutationResponse>;

/**
 * @description OK
 */
export const sendBulkNotification200Schema = z.lazy(
  () => modelsNotificationResponseSchema,
) as unknown as z.ZodType<SendBulkNotification200>;

/**
 * @description Bad Request
 */
export const sendBulkNotification400Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<SendBulkNotification400>;

/**
 * @description Unprocessable Entity
 */
export const sendBulkNotification422Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<SendBulkNotification422>;

/**
 * @description Internal Server Error
 */
export const sendBulkNotification500Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<SendBulkNotification500>;

/**
 * @description Bulk notification request
 */
export const sendBulkNotificationMutationRequestSchema = z.lazy(
  () => modelsSendBulkNotificationRequestSchema,
) as unknown as z.ZodType<SendBulkNotificationMutationRequest>;

export const sendBulkNotificationMutationResponseSchema = z.lazy(
  () => sendBulkNotification200Schema,
) as unknown as z.ZodType<SendBulkNotificationMutationResponse>;

export const getAllTripsQueryParamsSchema = z
  .object({
    limit: z.optional(
      z.coerce
        .number()
        .int()
        .describe("Max items per page (default 20, max 100)"),
    ),
    cursor: z.optional(
      z
        .string()
        .describe(
          "Opaque cursor from previous response next_cursor for next page",
        ),
    ),
  })
  .optional() as unknown as z.ZodType<GetAllTripsQueryParams>;

/**
 * @description OK
 */
export const getAllTrips200Schema = z.lazy(
  () => modelsTripCursorPageResultSchema,
) as unknown as z.ZodType<GetAllTrips200>;

/**
 * @description Invalid cursor
 */
export const getAllTrips400Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<GetAllTrips400>;

/**
 * @description Internal Server Error
 */
export const getAllTrips500Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<GetAllTrips500>;

export const getAllTripsQueryResponseSchema = z.lazy(
  () => getAllTrips200Schema,
) as unknown as z.ZodType<GetAllTripsQueryResponse>;

/**
 * @description Created
 */
export const createTrip201Schema = z.lazy(
  () => modelsTripSchema,
) as unknown as z.ZodType<CreateTrip201>;

/**
 * @description Bad Request
 */
export const createTrip400Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<CreateTrip400>;

/**
 * @description Unprocessable Entity
 */
export const createTrip422Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<CreateTrip422>;

/**
 * @description Internal Server Error
 */
export const createTrip500Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<CreateTrip500>;

/**
 * @description Create trip request
 */
export const createTripMutationRequestSchema = z.lazy(
  () => modelsCreateTripRequestSchema,
) as unknown as z.ZodType<CreateTripMutationRequest>;

export const createTripMutationResponseSchema = z.lazy(
  () => createTrip201Schema,
) as unknown as z.ZodType<CreateTripMutationResponse>;

export const getTripPathParamsSchema = z.object({
  tripID: z.string().describe("Trip ID"),
}) as unknown as z.ZodType<GetTripPathParams>;

/**
 * @description OK
 */
export const getTrip200Schema = z.lazy(
  () => modelsTripSchema,
) as unknown as z.ZodType<GetTrip200>;

/**
 * @description Bad Request
 */
export const getTrip400Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<GetTrip400>;

/**
 * @description Not Found
 */
export const getTrip404Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<GetTrip404>;

/**
 * @description Internal Server Error
 */
export const getTrip500Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<GetTrip500>;

export const getTripQueryResponseSchema = z.lazy(
  () => getTrip200Schema,
) as unknown as z.ZodType<GetTripQueryResponse>;

export const deleteTripPathParamsSchema = z.object({
  tripID: z.string().describe("Trip ID"),
}) as unknown as z.ZodType<DeleteTripPathParams>;

/**
 * @description No Content
 */
export const deleteTrip204Schema =
  z.any() as unknown as z.ZodType<DeleteTrip204>;

/**
 * @description Bad Request
 */
export const deleteTrip400Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<DeleteTrip400>;

/**
 * @description Not Found
 */
export const deleteTrip404Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<DeleteTrip404>;

/**
 * @description Internal Server Error
 */
export const deleteTrip500Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<DeleteTrip500>;

export const deleteTripMutationResponseSchema = z.lazy(
  () => deleteTrip204Schema,
) as unknown as z.ZodType<DeleteTripMutationResponse>;

export const updateTripPathParamsSchema = z.object({
  tripID: z.string().describe("Trip ID"),
}) as unknown as z.ZodType<UpdateTripPathParams>;

/**
 * @description OK
 */
export const updateTrip200Schema = z.lazy(
  () => modelsTripSchema,
) as unknown as z.ZodType<UpdateTrip200>;

/**
 * @description Bad Request
 */
export const updateTrip400Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<UpdateTrip400>;

/**
 * @description Not Found
 */
export const updateTrip404Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<UpdateTrip404>;

/**
 * @description Unprocessable Entity
 */
export const updateTrip422Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<UpdateTrip422>;

/**
 * @description Internal Server Error
 */
export const updateTrip500Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<UpdateTrip500>;

/**
 * @description Update trip request
 */
export const updateTripMutationRequestSchema = z.lazy(
  () => modelsUpdateTripRequestSchema,
) as unknown as z.ZodType<UpdateTripMutationRequest>;

export const updateTripMutationResponseSchema = z.lazy(
  () => updateTrip200Schema,
) as unknown as z.ZodType<UpdateTripMutationResponse>;

export const getTripMembersPathParamsSchema = z.object({
  tripID: z.string().describe("Trip ID"),
}) as unknown as z.ZodType<GetTripMembersPathParams>;

/**
 * @description OK
 */
export const getTripMembers200Schema = z.lazy(
  () => modelsGetTripMembersResponseSchema,
) as unknown as z.ZodType<GetTripMembers200>;

/**
 * @description Bad Request
 */
export const getTripMembers400Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<GetTripMembers400>;

/**
 * @description Internal Server Error
 */
export const getTripMembers500Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<GetTripMembers500>;

export const getTripMembersQueryResponseSchema = z.lazy(
  () => getTripMembers200Schema,
) as unknown as z.ZodType<GetTripMembersQueryResponse>;

export const getMembershipPathParamsSchema = z.object({
  tripID: z.string().describe("Trip ID"),
  userID: z.string().describe("User ID"),
}) as unknown as z.ZodType<GetMembershipPathParams>;

/**
 * @description OK
 */
export const getMembership200Schema = z.lazy(
  () => modelsMembershipSchema,
) as unknown as z.ZodType<GetMembership200>;

/**
 * @description Bad Request
 */
export const getMembership400Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<GetMembership400>;

/**
 * @description Not Found
 */
export const getMembership404Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<GetMembership404>;

/**
 * @description Internal Server Error
 */
export const getMembership500Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<GetMembership500>;

export const getMembershipQueryResponseSchema = z.lazy(
  () => getMembership200Schema,
) as unknown as z.ZodType<GetMembershipQueryResponse>;

export const removeMemberPathParamsSchema = z.object({
  tripID: z.string().describe("Trip ID"),
  userID: z.string().describe("User ID"),
}) as unknown as z.ZodType<RemoveMemberPathParams>;

/**
 * @description No Content
 */
export const removeMember204Schema =
  z.any() as unknown as z.ZodType<RemoveMember204>;

/**
 * @description Bad Request
 */
export const removeMember400Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<RemoveMember400>;

/**
 * @description Not Found
 */
export const removeMember404Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<RemoveMember404>;

/**
 * @description Internal Server Error
 */
export const removeMember500Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<RemoveMember500>;

export const removeMemberMutationResponseSchema = z.lazy(
  () => removeMember204Schema,
) as unknown as z.ZodType<RemoveMemberMutationResponse>;

export const updateMembershipPathParamsSchema = z.object({
  tripID: z.string().describe("Trip ID"),
  userID: z.string().describe("User ID"),
}) as unknown as z.ZodType<UpdateMembershipPathParams>;

/**
 * @description OK
 */
export const updateMembership200Schema = z.lazy(
  () => modelsMembershipSchema,
) as unknown as z.ZodType<UpdateMembership200>;

/**
 * @description Bad Request
 */
export const updateMembership400Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<UpdateMembership400>;

/**
 * @description Not Found
 */
export const updateMembership404Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<UpdateMembership404>;

/**
 * @description Unprocessable Entity
 */
export const updateMembership422Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<UpdateMembership422>;

/**
 * @description Internal Server Error
 */
export const updateMembership500Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<UpdateMembership500>;

/**
 * @description Update membership request
 */
export const updateMembershipMutationRequestSchema = z.lazy(
  () => modelsUpdateMembershipRequestSchema,
) as unknown as z.ZodType<UpdateMembershipMutationRequest>;

export const updateMembershipMutationResponseSchema = z.lazy(
  () => updateMembership200Schema,
) as unknown as z.ZodType<UpdateMembershipMutationResponse>;

export const demoteFromAdminPathParamsSchema = z.object({
  tripID: z.string().describe("Trip ID"),
  userID: z.string().describe("User ID"),
}) as unknown as z.ZodType<DemoteFromAdminPathParams>;

/**
 * @description OK
 */
export const demoteFromAdmin200Schema = z
  .object({})
  .catchall(z.string()) as unknown as z.ZodType<DemoteFromAdmin200>;

/**
 * @description Bad Request
 */
export const demoteFromAdmin400Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<DemoteFromAdmin400>;

/**
 * @description Not Found
 */
export const demoteFromAdmin404Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<DemoteFromAdmin404>;

/**
 * @description Internal Server Error
 */
export const demoteFromAdmin500Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<DemoteFromAdmin500>;

export const demoteFromAdminMutationResponseSchema = z.lazy(
  () => demoteFromAdmin200Schema,
) as unknown as z.ZodType<DemoteFromAdminMutationResponse>;

export const promoteToAdminPathParamsSchema = z.object({
  tripID: z.string().describe("Trip ID"),
  userID: z.string().describe("User ID"),
}) as unknown as z.ZodType<PromoteToAdminPathParams>;

/**
 * @description OK
 */
export const promoteToAdmin200Schema = z
  .object({})
  .catchall(z.string()) as unknown as z.ZodType<PromoteToAdmin200>;

/**
 * @description Bad Request
 */
export const promoteToAdmin400Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<PromoteToAdmin400>;

/**
 * @description Not Found
 */
export const promoteToAdmin404Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<PromoteToAdmin404>;

/**
 * @description Internal Server Error
 */
export const promoteToAdmin500Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<PromoteToAdmin500>;

export const promoteToAdminMutationResponseSchema = z.lazy(
  () => promoteToAdmin200Schema,
) as unknown as z.ZodType<PromoteToAdminMutationResponse>;

/**
 * @description Created
 */
export const createUser201Schema = z.lazy(
  () => modelsUserSchema,
) as unknown as z.ZodType<CreateUser201>;

/**
 * @description Bad Request
 */
export const createUser400Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<CreateUser400>;

/**
 * @description Unprocessable Entity
 */
export const createUser422Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<CreateUser422>;

/**
 * @description Internal Server Error
 */
export const createUser500Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<CreateUser500>;

/**
 * @description Create user request
 */
export const createUserMutationRequestSchema = z.lazy(
  () => modelsCreateUserRequestSchema,
) as unknown as z.ZodType<CreateUserMutationRequest>;

export const createUserMutationResponseSchema = z.lazy(
  () => createUser201Schema,
) as unknown as z.ZodType<CreateUserMutationResponse>;

/**
 * @description OK
 */
export const getCurrentUser200Schema = z.lazy(
  () => modelsUserSchema,
) as unknown as z.ZodType<GetCurrentUser200>;

/**
 * @description Unauthorized
 */
export const getCurrentUser401Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<GetCurrentUser401>;

/**
 * @description Not Found
 */
export const getCurrentUser404Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<GetCurrentUser404>;

/**
 * @description Internal Server Error
 */
export const getCurrentUser500Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<GetCurrentUser500>;

export const getCurrentUserQueryResponseSchema = z.lazy(
  () => getCurrentUser200Schema,
) as unknown as z.ZodType<GetCurrentUserQueryResponse>;

export const getUserPathParamsSchema = z.object({
  userID: z.string().describe("User ID"),
}) as unknown as z.ZodType<GetUserPathParams>;

/**
 * @description OK
 */
export const getUser200Schema = z.lazy(
  () => modelsUserSchema,
) as unknown as z.ZodType<GetUser200>;

/**
 * @description Bad Request
 */
export const getUser400Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<GetUser400>;

/**
 * @description Not Found
 */
export const getUser404Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<GetUser404>;

/**
 * @description Internal Server Error
 */
export const getUser500Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<GetUser500>;

export const getUserQueryResponseSchema = z.lazy(
  () => getUser200Schema,
) as unknown as z.ZodType<GetUserQueryResponse>;

export const deleteUserPathParamsSchema = z.object({
  userID: z.string().describe("User ID"),
}) as unknown as z.ZodType<DeleteUserPathParams>;

/**
 * @description No Content
 */
export const deleteUser204Schema =
  z.any() as unknown as z.ZodType<DeleteUser204>;

/**
 * @description Bad Request
 */
export const deleteUser400Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<DeleteUser400>;

/**
 * @description Not Found
 */
export const deleteUser404Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<DeleteUser404>;

/**
 * @description Internal Server Error
 */
export const deleteUser500Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<DeleteUser500>;

export const deleteUserMutationResponseSchema = z.lazy(
  () => deleteUser204Schema,
) as unknown as z.ZodType<DeleteUserMutationResponse>;

export const updateUserPathParamsSchema = z.object({
  userID: z.string().describe("User ID"),
}) as unknown as z.ZodType<UpdateUserPathParams>;

/**
 * @description OK
 */
export const updateUser200Schema = z.lazy(
  () => modelsUserSchema,
) as unknown as z.ZodType<UpdateUser200>;

/**
 * @description Bad Request
 */
export const updateUser400Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<UpdateUser400>;

/**
 * @description Not Found
 */
export const updateUser404Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<UpdateUser404>;

/**
 * @description Unprocessable Entity
 */
export const updateUser422Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<UpdateUser422>;

/**
 * @description Internal Server Error
 */
export const updateUser500Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<UpdateUser500>;

/**
 * @description Update user request
 */
export const updateUserMutationRequestSchema = z.lazy(
  () => modelsUpdateUserRequestSchema,
) as unknown as z.ZodType<UpdateUserMutationRequest>;

export const updateUserMutationResponseSchema = z.lazy(
  () => updateUser200Schema,
) as unknown as z.ZodType<UpdateUserMutationResponse>;

export const getUserTripsPathParamsSchema = z.object({
  userID: z.string().describe("User ID"),
}) as unknown as z.ZodType<GetUserTripsPathParams>;

/**
 * @description OK
 */
export const getUserTrips200Schema = z.array(
  z.lazy(() => modelsMembershipSchema),
) as unknown as z.ZodType<GetUserTrips200>;

/**
 * @description Bad Request
 */
export const getUserTrips400Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<GetUserTrips400>;

/**
 * @description Internal Server Error
 */
export const getUserTrips500Schema = z.lazy(
  () => errsAPIErrorSchema,
) as unknown as z.ZodType<GetUserTrips500>;

export const getUserTripsQueryResponseSchema = z.lazy(
  () => getUserTrips200Schema,
) as unknown as z.ZodType<GetUserTripsQueryResponse>;

/**
 * @description OK
 */
export const healthcheck200Schema = z
  .object({})
  .catchall(z.any()) as unknown as z.ZodType<Healthcheck200>;

/**
 * @description Internal Server Error
 */
export const healthcheck500Schema = z
  .object({})
  .catchall(z.any()) as unknown as z.ZodType<Healthcheck500>;

export const healthcheckQueryResponseSchema = z.lazy(
  () => healthcheck200Schema,
) as unknown as z.ZodType<HealthcheckQueryResponse>;
