/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  CheckS3HealthQueryResponse,
  CheckS3Health503,
} from "../../types/types.gen.ts";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const checkS3HealthQueryKey = () =>
  [{ url: "/api/v1/files/health" }] as const;

export type CheckS3HealthQueryKey = ReturnType<typeof checkS3HealthQueryKey>;

/**
 * @description Verifies connectivity to the configured S3 bucket
 * @summary Check S3 connection
 * {@link /api/v1/files/health}
 */
export async function checkS3Health(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    CheckS3HealthQueryResponse,
    ResponseErrorConfig<CheckS3Health503>,
    unknown
  >({ method: "GET", url: `/api/v1/files/health`, ...requestConfig });
  return res.data;
}

export function checkS3HealthQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = checkS3HealthQueryKey();
  return queryOptions<
    CheckS3HealthQueryResponse,
    ResponseErrorConfig<CheckS3Health503>,
    CheckS3HealthQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return checkS3Health(config);
    },
  });
}

/**
 * @description Verifies connectivity to the configured S3 bucket
 * @summary Check S3 connection
 * {@link /api/v1/files/health}
 */
export function useCheckS3Health<
  TData = CheckS3HealthQueryResponse,
  TQueryData = CheckS3HealthQueryResponse,
  TQueryKey extends QueryKey = CheckS3HealthQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        CheckS3HealthQueryResponse,
        ResponseErrorConfig<CheckS3Health503>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? checkS3HealthQueryKey();

  const query = useQuery(
    {
      ...checkS3HealthQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<CheckS3Health503>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
