/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type {
  CreateUploadURLsMutationRequest,
  CreateUploadURLsMutationResponse,
  CreateUploadURLs400,
  CreateUploadURLs422,
  CreateUploadURLs500,
} from "../../types/types.gen.ts";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const createUploadURLsMutationKey = () =>
  [{ url: "/api/v1/files/upload" }] as const;

export type CreateUploadURLsMutationKey = ReturnType<
  typeof createUploadURLsMutationKey
>;

/**
 * @description Generates presigned PUT URLs for uploading files and creates pending records in DB
 * @summary Create upload URLs
 * {@link /api/v1/files/upload}
 */
export async function createUploadURLs(
  data: CreateUploadURLsMutationRequest,
  config: Partial<RequestConfig<CreateUploadURLsMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    CreateUploadURLsMutationResponse,
    ResponseErrorConfig<
      CreateUploadURLs400 | CreateUploadURLs422 | CreateUploadURLs500
    >,
    CreateUploadURLsMutationRequest
  >({
    method: "POST",
    url: `/api/v1/files/upload`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function createUploadURLsMutationOptions(
  config: Partial<RequestConfig<CreateUploadURLsMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const mutationKey = createUploadURLsMutationKey();
  return mutationOptions<
    CreateUploadURLsMutationResponse,
    ResponseErrorConfig<
      CreateUploadURLs400 | CreateUploadURLs422 | CreateUploadURLs500
    >,
    { data: CreateUploadURLsMutationRequest },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return createUploadURLs(data, config);
    },
  });
}

/**
 * @description Generates presigned PUT URLs for uploading files and creates pending records in DB
 * @summary Create upload URLs
 * {@link /api/v1/files/upload}
 */
export function useCreateUploadURLs<TContext>(
  options: {
    mutation?: UseMutationOptions<
      CreateUploadURLsMutationResponse,
      ResponseErrorConfig<
        CreateUploadURLs400 | CreateUploadURLs422 | CreateUploadURLs500
      >,
      { data: CreateUploadURLsMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<CreateUploadURLsMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? createUploadURLsMutationKey();

  const baseOptions = createUploadURLsMutationOptions(
    config,
  ) as UseMutationOptions<
    CreateUploadURLsMutationResponse,
    ResponseErrorConfig<
      CreateUploadURLs400 | CreateUploadURLs422 | CreateUploadURLs500
    >,
    { data: CreateUploadURLsMutationRequest },
    TContext
  >;

  return useMutation<
    CreateUploadURLsMutationResponse,
    ResponseErrorConfig<
      CreateUploadURLs400 | CreateUploadURLs422 | CreateUploadURLs500
    >,
    { data: CreateUploadURLsMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    CreateUploadURLsMutationResponse,
    ResponseErrorConfig<
      CreateUploadURLs400 | CreateUploadURLs422 | CreateUploadURLs500
    >,
    { data: CreateUploadURLsMutationRequest },
    TContext
  >;
}
