/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { CheckS3HealthQueryResponse, CheckS3Health503 } from "../../types/types.gen.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const checkS3HealthSuspenseQueryKey = () => [{ url: '/api/v1/files/health' }] as const

export type CheckS3HealthSuspenseQueryKey = ReturnType<typeof checkS3HealthSuspenseQueryKey>

/**
 * @description Verifies connectivity to the configured S3 bucket
 * @summary Check S3 connection
 * {@link /api/v1/files/health}
 */
export async function checkS3HealthSuspense(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<CheckS3HealthQueryResponse, ResponseErrorConfig<CheckS3Health503>, unknown>({ method : "GET", url : `/api/v1/files/health`, ... requestConfig })  
  return res.data
}

export function checkS3HealthSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = checkS3HealthSuspenseQueryKey()
  return queryOptions<CheckS3HealthQueryResponse, ResponseErrorConfig<CheckS3Health503>, CheckS3HealthQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return checkS3HealthSuspense(config)
   },
  })
}

/**
 * @description Verifies connectivity to the configured S3 bucket
 * @summary Check S3 connection
 * {@link /api/v1/files/health}
 */
export function useCheckS3HealthSuspense<TData = CheckS3HealthQueryResponse, TQueryKey extends QueryKey = CheckS3HealthSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<CheckS3HealthQueryResponse, ResponseErrorConfig<CheckS3Health503>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? checkS3HealthSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...checkS3HealthSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<CheckS3Health503>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}