/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type {
  GetFileAllSizesQueryResponse,
  GetFileAllSizesPathParams,
  GetFileAllSizes400,
  GetFileAllSizes404,
  GetFileAllSizes500,
} from "../../types/types.gen.ts";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getFileAllSizesSuspenseQueryKey = (
  imageId: GetFileAllSizesPathParams["imageId"],
) => [{ url: "/api/v1/files/:imageId", params: { imageId: imageId } }] as const;

export type GetFileAllSizesSuspenseQueryKey = ReturnType<
  typeof getFileAllSizesSuspenseQueryKey
>;

/**
 * @description Retrieves presigned URLs for all sizes of an image
 * @summary Get all sizes of a file
 * {@link /api/v1/files/:imageId}
 */
export async function getFileAllSizesSuspense(
  imageId: GetFileAllSizesPathParams["imageId"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetFileAllSizesQueryResponse,
    ResponseErrorConfig<
      GetFileAllSizes400 | GetFileAllSizes404 | GetFileAllSizes500
    >,
    unknown
  >({ method: "GET", url: `/api/v1/files/${imageId}`, ...requestConfig });
  return res.data;
}

export function getFileAllSizesSuspenseQueryOptions(
  imageId: GetFileAllSizesPathParams["imageId"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getFileAllSizesSuspenseQueryKey(imageId);
  return queryOptions<
    GetFileAllSizesQueryResponse,
    ResponseErrorConfig<
      GetFileAllSizes400 | GetFileAllSizes404 | GetFileAllSizes500
    >,
    GetFileAllSizesQueryResponse,
    typeof queryKey
  >({
    enabled: !!imageId,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getFileAllSizesSuspense(imageId, config);
    },
  });
}

/**
 * @description Retrieves presigned URLs for all sizes of an image
 * @summary Get all sizes of a file
 * {@link /api/v1/files/:imageId}
 */
export function useGetFileAllSizesSuspense<
  TData = GetFileAllSizesQueryResponse,
  TQueryKey extends QueryKey = GetFileAllSizesSuspenseQueryKey,
>(
  imageId: GetFileAllSizesPathParams["imageId"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetFileAllSizesQueryResponse,
        ResponseErrorConfig<
          GetFileAllSizes400 | GetFileAllSizes404 | GetFileAllSizes500
        >,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getFileAllSizesSuspenseQueryKey(imageId);

  const query = useSuspenseQuery(
    {
      ...getFileAllSizesSuspenseQueryOptions(imageId, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<
      GetFileAllSizes400 | GetFileAllSizes404 | GetFileAllSizes500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
