/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  GetFileAllSizesQueryResponse,
  GetFileAllSizesPathParams,
  GetFileAllSizes400,
  GetFileAllSizes404,
  GetFileAllSizes500,
} from "../../types/types.gen.ts";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getFileAllSizesQueryKey = (
  imageId: GetFileAllSizesPathParams["imageId"],
) => [{ url: "/api/v1/files/:imageId", params: { imageId: imageId } }] as const;

export type GetFileAllSizesQueryKey = ReturnType<
  typeof getFileAllSizesQueryKey
>;

/**
 * @description Retrieves presigned URLs for all sizes of an image
 * @summary Get all sizes of a file
 * {@link /api/v1/files/:imageId}
 */
export async function getFileAllSizes(
  imageId: GetFileAllSizesPathParams["imageId"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetFileAllSizesQueryResponse,
    ResponseErrorConfig<
      GetFileAllSizes400 | GetFileAllSizes404 | GetFileAllSizes500
    >,
    unknown
  >({ method: "GET", url: `/api/v1/files/${imageId}`, ...requestConfig });
  return res.data;
}

export function getFileAllSizesQueryOptions(
  imageId: GetFileAllSizesPathParams["imageId"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getFileAllSizesQueryKey(imageId);
  return queryOptions<
    GetFileAllSizesQueryResponse,
    ResponseErrorConfig<
      GetFileAllSizes400 | GetFileAllSizes404 | GetFileAllSizes500
    >,
    GetFileAllSizesQueryResponse,
    typeof queryKey
  >({
    enabled: !!imageId,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getFileAllSizes(imageId, config);
    },
  });
}

/**
 * @description Retrieves presigned URLs for all sizes of an image
 * @summary Get all sizes of a file
 * {@link /api/v1/files/:imageId}
 */
export function useGetFileAllSizes<
  TData = GetFileAllSizesQueryResponse,
  TQueryData = GetFileAllSizesQueryResponse,
  TQueryKey extends QueryKey = GetFileAllSizesQueryKey,
>(
  imageId: GetFileAllSizesPathParams["imageId"],
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetFileAllSizesQueryResponse,
        ResponseErrorConfig<
          GetFileAllSizes400 | GetFileAllSizes404 | GetFileAllSizes500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? getFileAllSizesQueryKey(imageId);

  const query = useQuery(
    {
      ...getFileAllSizesQueryOptions(imageId, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      GetFileAllSizes400 | GetFileAllSizes404 | GetFileAllSizes500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
