/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type {
  CreateCommentMutationRequest,
  CreateCommentMutationResponse,
  CreateComment400,
  CreateComment422,
  CreateComment500,
} from "../../types/types.gen.ts";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const createCommentMutationKey = () =>
  [{ url: "/api/v1/comments" }] as const;

export type CreateCommentMutationKey = ReturnType<
  typeof createCommentMutationKey
>;

/**
 * @description Creates a new comment
 * @summary Create a comment
 * {@link /api/v1/comments}
 */
export async function createComment(
  data: CreateCommentMutationRequest,
  config: Partial<RequestConfig<CreateCommentMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    CreateCommentMutationResponse,
    ResponseErrorConfig<CreateComment400 | CreateComment422 | CreateComment500>,
    CreateCommentMutationRequest
  >({
    method: "POST",
    url: `/api/v1/comments`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function createCommentMutationOptions(
  config: Partial<RequestConfig<CreateCommentMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const mutationKey = createCommentMutationKey();
  return mutationOptions<
    CreateCommentMutationResponse,
    ResponseErrorConfig<CreateComment400 | CreateComment422 | CreateComment500>,
    { data: CreateCommentMutationRequest },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return createComment(data, config);
    },
  });
}

/**
 * @description Creates a new comment
 * @summary Create a comment
 * {@link /api/v1/comments}
 */
export function useCreateComment<TContext>(
  options: {
    mutation?: UseMutationOptions<
      CreateCommentMutationResponse,
      ResponseErrorConfig<
        CreateComment400 | CreateComment422 | CreateComment500
      >,
      { data: CreateCommentMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<CreateCommentMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? createCommentMutationKey();

  const baseOptions = createCommentMutationOptions(
    config,
  ) as UseMutationOptions<
    CreateCommentMutationResponse,
    ResponseErrorConfig<CreateComment400 | CreateComment422 | CreateComment500>,
    { data: CreateCommentMutationRequest },
    TContext
  >;

  return useMutation<
    CreateCommentMutationResponse,
    ResponseErrorConfig<CreateComment400 | CreateComment422 | CreateComment500>,
    { data: CreateCommentMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    CreateCommentMutationResponse,
    ResponseErrorConfig<CreateComment400 | CreateComment422 | CreateComment500>,
    { data: CreateCommentMutationRequest },
    TContext
  >;
}
