/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  DeleteCommentMutationResponse,
  DeleteCommentPathParams,
  DeleteComment400,
  DeleteComment401,
  DeleteComment404,
  DeleteComment500,
} from "../../types/types.gen.ts";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteCommentMutationKey = () =>
  [{ url: "/api/v1/comments/:commentID" }] as const;

export type DeleteCommentMutationKey = ReturnType<
  typeof deleteCommentMutationKey
>;

/**
 * @description Deletes a comment by ID
 * @summary Delete a comment
 * {@link /api/v1/comments/:commentID}
 */
export async function deleteComment(
  commentID: DeleteCommentPathParams["commentID"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeleteCommentMutationResponse,
    ResponseErrorConfig<
      DeleteComment400 | DeleteComment401 | DeleteComment404 | DeleteComment500
    >,
    unknown
  >({
    method: "DELETE",
    url: `/api/v1/comments/${commentID}`,
    ...requestConfig,
  });
  return res.data;
}

export function deleteCommentMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = deleteCommentMutationKey();
  return mutationOptions<
    DeleteCommentMutationResponse,
    ResponseErrorConfig<
      DeleteComment400 | DeleteComment401 | DeleteComment404 | DeleteComment500
    >,
    { commentID: DeleteCommentPathParams["commentID"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ commentID }) => {
      return deleteComment(commentID, config);
    },
  });
}

/**
 * @description Deletes a comment by ID
 * @summary Delete a comment
 * {@link /api/v1/comments/:commentID}
 */
export function useDeleteComment<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteCommentMutationResponse,
      ResponseErrorConfig<
        | DeleteComment400
        | DeleteComment401
        | DeleteComment404
        | DeleteComment500
      >,
      { commentID: DeleteCommentPathParams["commentID"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? deleteCommentMutationKey();

  const baseOptions = deleteCommentMutationOptions(
    config,
  ) as UseMutationOptions<
    DeleteCommentMutationResponse,
    ResponseErrorConfig<
      DeleteComment400 | DeleteComment401 | DeleteComment404 | DeleteComment500
    >,
    { commentID: DeleteCommentPathParams["commentID"] },
    TContext
  >;

  return useMutation<
    DeleteCommentMutationResponse,
    ResponseErrorConfig<
      DeleteComment400 | DeleteComment401 | DeleteComment404 | DeleteComment500
    >,
    { commentID: DeleteCommentPathParams["commentID"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteCommentMutationResponse,
    ResponseErrorConfig<
      DeleteComment400 | DeleteComment401 | DeleteComment404 | DeleteComment500
    >,
    { commentID: DeleteCommentPathParams["commentID"] },
    TContext
  >;
}
