/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  SearchTripsQueryResponse,
  SearchTripsQueryParams,
  SearchTrips400,
  SearchTrips401,
  SearchTrips422,
  SearchTrips500,
} from "../../types/types.gen.ts";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const searchTripsSuspenseQueryKey = (params: SearchTripsQueryParams) =>
  [{ url: "/api/v1/search/trips" }, ...(params ? [params] : [])] as const;

export type SearchTripsSuspenseQueryKey = ReturnType<
  typeof searchTripsSuspenseQueryKey
>;

/**
 * @description Full-text search over trips the authenticated user is a member of. Ordered by relevance then recency.
 * @summary Search trips
 * {@link /api/v1/search/trips}
 */
export async function searchTripsSuspense(
  params: SearchTripsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    SearchTripsQueryResponse,
    ResponseErrorConfig<
      SearchTrips400 | SearchTrips401 | SearchTrips422 | SearchTrips500
    >,
    unknown
  >({ method: "GET", url: `/api/v1/search/trips`, params, ...requestConfig });
  return res.data;
}

export function searchTripsSuspenseQueryOptions(
  params: SearchTripsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = searchTripsSuspenseQueryKey(params);
  return queryOptions<
    SearchTripsQueryResponse,
    ResponseErrorConfig<
      SearchTrips400 | SearchTrips401 | SearchTrips422 | SearchTrips500
    >,
    SearchTripsQueryResponse,
    typeof queryKey
  >({
    enabled: !!params,
    queryKey,
    queryFn: async ({ signal }) => {
      if (!config.signal) {
        config.signal = signal;
      }
      return searchTripsSuspense(params, config);
    },
  });
}

/**
 * @description Full-text search over trips the authenticated user is a member of. Ordered by relevance then recency.
 * @summary Search trips
 * {@link /api/v1/search/trips}
 */
export function useSearchTripsSuspense<
  TData = SearchTripsQueryResponse,
  TQueryKey extends QueryKey = SearchTripsSuspenseQueryKey,
>(
  params: SearchTripsQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        SearchTripsQueryResponse,
        ResponseErrorConfig<
          SearchTrips400 | SearchTrips401 | SearchTrips422 | SearchTrips500
        >,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? searchTripsSuspenseQueryKey(params);

  const query = useSuspenseQuery(
    {
      ...searchTripsSuspenseQueryOptions(params, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<
      SearchTrips400 | SearchTrips401 | SearchTrips422 | SearchTrips500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
