/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  SearchTripMembersQueryResponse,
  SearchTripMembersPathParams,
  SearchTripMembersQueryParams,
  SearchTripMembers400,
  SearchTripMembers401,
  SearchTripMembers404,
  SearchTripMembers422,
  SearchTripMembers500,
} from "../../types/types.gen.ts";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const searchTripMembersQueryKey = (
  tripID: SearchTripMembersPathParams["tripID"],
  params: SearchTripMembersQueryParams,
) =>
  [
    { url: "/api/v1/search/trips/:tripID/members", params: { tripID: tripID } },
    ...(params ? [params] : []),
  ] as const;

export type SearchTripMembersQueryKey = ReturnType<
  typeof searchTripMembersQueryKey
>;

/**
 * @description Full-text search over members of a specific trip, matching on name and username.
 * @summary Search trip members
 * {@link /api/v1/search/trips/:tripID/members}
 */
export async function searchTripMembers(
  tripID: SearchTripMembersPathParams["tripID"],
  params: SearchTripMembersQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    SearchTripMembersQueryResponse,
    ResponseErrorConfig<
      | SearchTripMembers400
      | SearchTripMembers401
      | SearchTripMembers404
      | SearchTripMembers422
      | SearchTripMembers500
    >,
    unknown
  >({
    method: "GET",
    url: `/api/v1/search/trips/${tripID}/members`,
    params,
    ...requestConfig,
  });
  return res.data;
}

export function searchTripMembersQueryOptions(
  tripID: SearchTripMembersPathParams["tripID"],
  params: SearchTripMembersQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = searchTripMembersQueryKey(tripID, params);
  return queryOptions<
    SearchTripMembersQueryResponse,
    ResponseErrorConfig<
      | SearchTripMembers400
      | SearchTripMembers401
      | SearchTripMembers404
      | SearchTripMembers422
      | SearchTripMembers500
    >,
    SearchTripMembersQueryResponse,
    typeof queryKey
  >({
    enabled: !!(tripID && params),
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return searchTripMembers(tripID, params, config);
    },
  });
}

/**
 * @description Full-text search over members of a specific trip, matching on name and username.
 * @summary Search trip members
 * {@link /api/v1/search/trips/:tripID/members}
 */
export function useSearchTripMembers<
  TData = SearchTripMembersQueryResponse,
  TQueryData = SearchTripMembersQueryResponse,
  TQueryKey extends QueryKey = SearchTripMembersQueryKey,
>(
  tripID: SearchTripMembersPathParams["tripID"],
  params: SearchTripMembersQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        SearchTripMembersQueryResponse,
        ResponseErrorConfig<
          | SearchTripMembers400
          | SearchTripMembers401
          | SearchTripMembers404
          | SearchTripMembers422
          | SearchTripMembers500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? searchTripMembersQueryKey(tripID, params);

  const query = useQuery(
    {
      ...searchTripMembersQueryOptions(tripID, params, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      | SearchTripMembers400
      | SearchTripMembers401
      | SearchTripMembers404
      | SearchTripMembers422
      | SearchTripMembers500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
