/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import type {
  SearchActivitiesQueryResponse,
  SearchActivitiesPathParams,
  SearchActivitiesQueryParams,
  SearchActivities400,
  SearchActivities401,
  SearchActivities404,
  SearchActivities422,
  SearchActivities500,
} from "../../types/types.gen.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const searchActivitiesSuspenseQueryKey = (
  tripID: SearchActivitiesPathParams["tripID"],
  params: SearchActivitiesQueryParams,
) =>
  [
    {
      url: "/api/v1/search/trips/:tripID/activities",
      params: { tripID: tripID },
    },
    ...(params ? [params] : []),
  ] as const;

export type SearchActivitiesSuspenseQueryKey = ReturnType<
  typeof searchActivitiesSuspenseQueryKey
>;

/**
 * @description Full-text search over activities within a specific trip. Ordered by relevance then recency.
 * @summary Search activities in a trip
 * {@link /api/v1/search/trips/:tripID/activities}
 */
export async function searchActivitiesSuspense(
  tripID: SearchActivitiesPathParams["tripID"],
  params: SearchActivitiesQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    SearchActivitiesQueryResponse,
    ResponseErrorConfig<
      | SearchActivities400
      | SearchActivities401
      | SearchActivities404
      | SearchActivities422
      | SearchActivities500
    >,
    unknown
  >({
    method: "GET",
    url: `/api/v1/search/trips/${tripID}/activities`,
    params,
    ...requestConfig,
  });
  return res.data;
}

export function searchActivitiesSuspenseQueryOptions(
  tripID: SearchActivitiesPathParams["tripID"],
  params: SearchActivitiesQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = searchActivitiesSuspenseQueryKey(tripID, params);
  return queryOptions<
    SearchActivitiesQueryResponse,
    ResponseErrorConfig<
      | SearchActivities400
      | SearchActivities401
      | SearchActivities404
      | SearchActivities422
      | SearchActivities500
    >,
    SearchActivitiesQueryResponse,
    typeof queryKey
  >({
    enabled: !!(tripID && params),
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return searchActivitiesSuspense(tripID, params, config);
    },
  });
}

/**
 * @description Full-text search over activities within a specific trip. Ordered by relevance then recency.
 * @summary Search activities in a trip
 * {@link /api/v1/search/trips/:tripID/activities}
 */
export function useSearchActivitiesSuspense<
  TData = SearchActivitiesQueryResponse,
  TQueryKey extends QueryKey = SearchActivitiesSuspenseQueryKey,
>(
  tripID: SearchActivitiesPathParams["tripID"],
  params: SearchActivitiesQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        SearchActivitiesQueryResponse,
        ResponseErrorConfig<
          | SearchActivities400
          | SearchActivities401
          | SearchActivities404
          | SearchActivities422
          | SearchActivities500
        >,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? searchActivitiesSuspenseQueryKey(tripID, params);

  const query = useSuspenseQuery(
    {
      ...searchActivitiesSuspenseQueryOptions(tripID, params, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<
      | SearchActivities400
      | SearchActivities401
      | SearchActivities404
      | SearchActivities422
      | SearchActivities500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
