/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  CreateActivityMutationRequest,
  CreateActivityMutationResponse,
  CreateActivityPathParams,
  CreateActivity400,
  CreateActivity401,
  CreateActivity403,
  CreateActivity404,
  CreateActivity422,
  CreateActivity500,
} from "../../types/types.gen.ts";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const createActivityMutationKey = () =>
  [{ url: "/api/v1/trips/:tripID/activities" }] as const;

export type CreateActivityMutationKey = ReturnType<
  typeof createActivityMutationKey
>;

/**
 * @description Creates a new activity for a trip
 * @summary Create activity
 * {@link /api/v1/trips/:tripID/activities}
 */
export async function createActivity(
  tripID: CreateActivityPathParams["tripID"],
  data: CreateActivityMutationRequest,
  config: Partial<RequestConfig<CreateActivityMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    CreateActivityMutationResponse,
    ResponseErrorConfig<
      | CreateActivity400
      | CreateActivity401
      | CreateActivity403
      | CreateActivity404
      | CreateActivity422
      | CreateActivity500
    >,
    CreateActivityMutationRequest
  >({
    method: "POST",
    url: `/api/v1/trips/${tripID}/activities`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function createActivityMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<CreateActivityMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = createActivityMutationKey();
  return mutationOptions<
    CreateActivityMutationResponse,
    ResponseErrorConfig<
      | CreateActivity400
      | CreateActivity401
      | CreateActivity403
      | CreateActivity404
      | CreateActivity422
      | CreateActivity500
    >,
    {
      tripID: CreateActivityPathParams["tripID"];
      data: CreateActivityMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ tripID, data }) => {
      return createActivity(tripID, data, config);
    },
  });
}

/**
 * @description Creates a new activity for a trip
 * @summary Create activity
 * {@link /api/v1/trips/:tripID/activities}
 */
export function useCreateActivity<TContext>(
  options: {
    mutation?: UseMutationOptions<
      CreateActivityMutationResponse,
      ResponseErrorConfig<
        | CreateActivity400
        | CreateActivity401
        | CreateActivity403
        | CreateActivity404
        | CreateActivity422
        | CreateActivity500
      >,
      {
        tripID: CreateActivityPathParams["tripID"];
        data: CreateActivityMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<CreateActivityMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? createActivityMutationKey();

  const baseOptions = createActivityMutationOptions(
    config,
  ) as UseMutationOptions<
    CreateActivityMutationResponse,
    ResponseErrorConfig<
      | CreateActivity400
      | CreateActivity401
      | CreateActivity403
      | CreateActivity404
      | CreateActivity422
      | CreateActivity500
    >,
    {
      tripID: CreateActivityPathParams["tripID"];
      data: CreateActivityMutationRequest;
    },
    TContext
  >;

  return useMutation<
    CreateActivityMutationResponse,
    ResponseErrorConfig<
      | CreateActivity400
      | CreateActivity401
      | CreateActivity403
      | CreateActivity404
      | CreateActivity422
      | CreateActivity500
    >,
    {
      tripID: CreateActivityPathParams["tripID"];
      data: CreateActivityMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    CreateActivityMutationResponse,
    ResponseErrorConfig<
      | CreateActivity400
      | CreateActivity401
      | CreateActivity403
      | CreateActivity404
      | CreateActivity422
      | CreateActivity500
    >,
    {
      tripID: CreateActivityPathParams["tripID"];
      data: CreateActivityMutationRequest;
    },
    TContext
  >;
}
