/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  DeleteApiV1TripsTripidActivitiesActivityidRsvpsUseridMutationResponse,
  DeleteApiV1TripsTripidActivitiesActivityidRsvpsUseridPathParams,
  DeleteApiV1TripsTripidActivitiesActivityidRsvpsUserid400,
  DeleteApiV1TripsTripidActivitiesActivityidRsvpsUserid401,
  DeleteApiV1TripsTripidActivitiesActivityidRsvpsUserid403,
  DeleteApiV1TripsTripidActivitiesActivityidRsvpsUserid404,
  DeleteApiV1TripsTripidActivitiesActivityidRsvpsUserid500,
} from "../../types/types.gen.ts";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteApiV1TripsTripidActivitiesActivityidRsvpsUseridMutationKey =
  () =>
    [
      { url: "/api/v1/trips/:tripID/activities/:activityID/rsvps/:userID" },
    ] as const;

export type DeleteApiV1TripsTripidActivitiesActivityidRsvpsUseridMutationKey =
  ReturnType<
    typeof deleteApiV1TripsTripidActivitiesActivityidRsvpsUseridMutationKey
  >;

/**
 * @description Removes a user's RSVP from an activity. Only the activity proposer or a trip admin can remove another user's RSVP.
 * @summary Remove activity RSVP
 * {@link /api/v1/trips/:tripID/activities/:activityID/rsvps/:userID}
 */
export async function deleteApiV1TripsTripidActivitiesActivityidRsvpsUserid(
  tripID: DeleteApiV1TripsTripidActivitiesActivityidRsvpsUseridPathParams["tripID"],
  activityID: DeleteApiV1TripsTripidActivitiesActivityidRsvpsUseridPathParams["activityID"],
  userID: DeleteApiV1TripsTripidActivitiesActivityidRsvpsUseridPathParams["userID"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeleteApiV1TripsTripidActivitiesActivityidRsvpsUseridMutationResponse,
    ResponseErrorConfig<
      | DeleteApiV1TripsTripidActivitiesActivityidRsvpsUserid400
      | DeleteApiV1TripsTripidActivitiesActivityidRsvpsUserid401
      | DeleteApiV1TripsTripidActivitiesActivityidRsvpsUserid403
      | DeleteApiV1TripsTripidActivitiesActivityidRsvpsUserid404
      | DeleteApiV1TripsTripidActivitiesActivityidRsvpsUserid500
    >,
    unknown
  >({
    method: "DELETE",
    url: `/api/v1/trips/${tripID}/activities/${activityID}/rsvps/${userID}`,
    ...requestConfig,
  });
  return res.data;
}

export function deleteApiV1TripsTripidActivitiesActivityidRsvpsUseridMutationOptions<
  TContext = unknown,
>(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const mutationKey =
    deleteApiV1TripsTripidActivitiesActivityidRsvpsUseridMutationKey();
  return mutationOptions<
    DeleteApiV1TripsTripidActivitiesActivityidRsvpsUseridMutationResponse,
    ResponseErrorConfig<
      | DeleteApiV1TripsTripidActivitiesActivityidRsvpsUserid400
      | DeleteApiV1TripsTripidActivitiesActivityidRsvpsUserid401
      | DeleteApiV1TripsTripidActivitiesActivityidRsvpsUserid403
      | DeleteApiV1TripsTripidActivitiesActivityidRsvpsUserid404
      | DeleteApiV1TripsTripidActivitiesActivityidRsvpsUserid500
    >,
    {
      tripID: DeleteApiV1TripsTripidActivitiesActivityidRsvpsUseridPathParams["tripID"];
      activityID: DeleteApiV1TripsTripidActivitiesActivityidRsvpsUseridPathParams["activityID"];
      userID: DeleteApiV1TripsTripidActivitiesActivityidRsvpsUseridPathParams["userID"];
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ tripID, activityID, userID }) => {
      return deleteApiV1TripsTripidActivitiesActivityidRsvpsUserid(
        tripID,
        activityID,
        userID,
        config,
      );
    },
  });
}

/**
 * @description Removes a user's RSVP from an activity. Only the activity proposer or a trip admin can remove another user's RSVP.
 * @summary Remove activity RSVP
 * {@link /api/v1/trips/:tripID/activities/:activityID/rsvps/:userID}
 */
export function useDeleteApiV1TripsTripidActivitiesActivityidRsvpsUserid<
  TContext,
>(
  options: {
    mutation?: UseMutationOptions<
      DeleteApiV1TripsTripidActivitiesActivityidRsvpsUseridMutationResponse,
      ResponseErrorConfig<
        | DeleteApiV1TripsTripidActivitiesActivityidRsvpsUserid400
        | DeleteApiV1TripsTripidActivitiesActivityidRsvpsUserid401
        | DeleteApiV1TripsTripidActivitiesActivityidRsvpsUserid403
        | DeleteApiV1TripsTripidActivitiesActivityidRsvpsUserid404
        | DeleteApiV1TripsTripidActivitiesActivityidRsvpsUserid500
      >,
      {
        tripID: DeleteApiV1TripsTripidActivitiesActivityidRsvpsUseridPathParams["tripID"];
        activityID: DeleteApiV1TripsTripidActivitiesActivityidRsvpsUseridPathParams["activityID"];
        userID: DeleteApiV1TripsTripidActivitiesActivityidRsvpsUseridPathParams["userID"];
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ??
    deleteApiV1TripsTripidActivitiesActivityidRsvpsUseridMutationKey();

  const baseOptions =
    deleteApiV1TripsTripidActivitiesActivityidRsvpsUseridMutationOptions(
      config,
    ) as UseMutationOptions<
      DeleteApiV1TripsTripidActivitiesActivityidRsvpsUseridMutationResponse,
      ResponseErrorConfig<
        | DeleteApiV1TripsTripidActivitiesActivityidRsvpsUserid400
        | DeleteApiV1TripsTripidActivitiesActivityidRsvpsUserid401
        | DeleteApiV1TripsTripidActivitiesActivityidRsvpsUserid403
        | DeleteApiV1TripsTripidActivitiesActivityidRsvpsUserid404
        | DeleteApiV1TripsTripidActivitiesActivityidRsvpsUserid500
      >,
      {
        tripID: DeleteApiV1TripsTripidActivitiesActivityidRsvpsUseridPathParams["tripID"];
        activityID: DeleteApiV1TripsTripidActivitiesActivityidRsvpsUseridPathParams["activityID"];
        userID: DeleteApiV1TripsTripidActivitiesActivityidRsvpsUseridPathParams["userID"];
      },
      TContext
    >;

  return useMutation<
    DeleteApiV1TripsTripidActivitiesActivityidRsvpsUseridMutationResponse,
    ResponseErrorConfig<
      | DeleteApiV1TripsTripidActivitiesActivityidRsvpsUserid400
      | DeleteApiV1TripsTripidActivitiesActivityidRsvpsUserid401
      | DeleteApiV1TripsTripidActivitiesActivityidRsvpsUserid403
      | DeleteApiV1TripsTripidActivitiesActivityidRsvpsUserid404
      | DeleteApiV1TripsTripidActivitiesActivityidRsvpsUserid500
    >,
    {
      tripID: DeleteApiV1TripsTripidActivitiesActivityidRsvpsUseridPathParams["tripID"];
      activityID: DeleteApiV1TripsTripidActivitiesActivityidRsvpsUseridPathParams["activityID"];
      userID: DeleteApiV1TripsTripidActivitiesActivityidRsvpsUseridPathParams["userID"];
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteApiV1TripsTripidActivitiesActivityidRsvpsUseridMutationResponse,
    ResponseErrorConfig<
      | DeleteApiV1TripsTripidActivitiesActivityidRsvpsUserid400
      | DeleteApiV1TripsTripidActivitiesActivityidRsvpsUserid401
      | DeleteApiV1TripsTripidActivitiesActivityidRsvpsUserid403
      | DeleteApiV1TripsTripidActivitiesActivityidRsvpsUserid404
      | DeleteApiV1TripsTripidActivitiesActivityidRsvpsUserid500
    >,
    {
      tripID: DeleteApiV1TripsTripidActivitiesActivityidRsvpsUseridPathParams["tripID"];
      activityID: DeleteApiV1TripsTripidActivitiesActivityidRsvpsUseridPathParams["activityID"];
      userID: DeleteApiV1TripsTripidActivitiesActivityidRsvpsUseridPathParams["userID"];
    },
    TContext
  >;
}
