/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  GetActivityCategoriesQueryResponse,
  GetActivityCategoriesPathParams,
  GetActivityCategoriesQueryParams,
  GetActivityCategories400,
  GetActivityCategories401,
  GetActivityCategories403,
  GetActivityCategories404,
  GetActivityCategories500,
} from "../../types/types.gen.ts";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getActivityCategoriesQueryKey = (
  tripID: GetActivityCategoriesPathParams["tripID"],
  activityID: GetActivityCategoriesPathParams["activityID"],
  params: GetActivityCategoriesQueryParams = {},
) =>
  [
    {
      url: "/api/v1/trips/:tripID/activities/:activityID/categories",
      params: { tripID: tripID, activityID: activityID },
    },
    ...(params ? [params] : []),
  ] as const;

export type GetActivityCategoriesQueryKey = ReturnType<
  typeof getActivityCategoriesQueryKey
>;

/**
 * @description Retrieves categories for an activity with pagination
 * @summary Get activity categories
 * {@link /api/v1/trips/:tripID/activities/:activityID/categories}
 */
export async function getActivityCategories(
  tripID: GetActivityCategoriesPathParams["tripID"],
  activityID: GetActivityCategoriesPathParams["activityID"],
  params?: GetActivityCategoriesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetActivityCategoriesQueryResponse,
    ResponseErrorConfig<
      | GetActivityCategories400
      | GetActivityCategories401
      | GetActivityCategories403
      | GetActivityCategories404
      | GetActivityCategories500
    >,
    unknown
  >({
    method: "GET",
    url: `/api/v1/trips/${tripID}/activities/${activityID}/categories`,
    params,
    ...requestConfig,
  });
  return res.data;
}

export function getActivityCategoriesQueryOptions(
  tripID: GetActivityCategoriesPathParams["tripID"],
  activityID: GetActivityCategoriesPathParams["activityID"],
  params?: GetActivityCategoriesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getActivityCategoriesQueryKey(tripID, activityID, params);
  return queryOptions<
    GetActivityCategoriesQueryResponse,
    ResponseErrorConfig<
      | GetActivityCategories400
      | GetActivityCategories401
      | GetActivityCategories403
      | GetActivityCategories404
      | GetActivityCategories500
    >,
    GetActivityCategoriesQueryResponse,
    typeof queryKey
  >({
    enabled: !!(tripID && activityID),
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getActivityCategories(tripID, activityID, params, config);
    },
  });
}

/**
 * @description Retrieves categories for an activity with pagination
 * @summary Get activity categories
 * {@link /api/v1/trips/:tripID/activities/:activityID/categories}
 */
export function useGetActivityCategories<
  TData = GetActivityCategoriesQueryResponse,
  TQueryData = GetActivityCategoriesQueryResponse,
  TQueryKey extends QueryKey = GetActivityCategoriesQueryKey,
>(
  tripID: GetActivityCategoriesPathParams["tripID"],
  activityID: GetActivityCategoriesPathParams["activityID"],
  params?: GetActivityCategoriesQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetActivityCategoriesQueryResponse,
        ResponseErrorConfig<
          | GetActivityCategories400
          | GetActivityCategories401
          | GetActivityCategories403
          | GetActivityCategories404
          | GetActivityCategories500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ??
    getActivityCategoriesQueryKey(tripID, activityID, params);

  const query = useQuery(
    {
      ...getActivityCategoriesQueryOptions(tripID, activityID, params, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetActivityCategories400
      | GetActivityCategories401
      | GetActivityCategories403
      | GetActivityCategories404
      | GetActivityCategories500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
