/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  GetActivitiesByTripIDQueryResponse,
  GetActivitiesByTripIDPathParams,
  GetActivitiesByTripIDQueryParams,
  GetActivitiesByTripID400,
  GetActivitiesByTripID401,
  GetActivitiesByTripID403,
  GetActivitiesByTripID404,
  GetActivitiesByTripID500,
} from "../../types/types.gen.ts";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getActivitiesByTripIDQueryKey = (
  tripID: GetActivitiesByTripIDPathParams["tripID"],
  params: GetActivitiesByTripIDQueryParams = {},
) =>
  [
    { url: "/api/v1/trips/:tripID/activities", params: { tripID: tripID } },
    ...(params ? [params] : []),
  ] as const;

export type GetActivitiesByTripIDQueryKey = ReturnType<
  typeof getActivitiesByTripIDQueryKey
>;

/**
 * @description Retrieves paginated activities for a trip, optionally filtered by category
 * @summary Get activities by trip
 * {@link /api/v1/trips/:tripID/activities}
 */
export async function getActivitiesByTripID(
  tripID: GetActivitiesByTripIDPathParams["tripID"],
  params?: GetActivitiesByTripIDQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetActivitiesByTripIDQueryResponse,
    ResponseErrorConfig<
      | GetActivitiesByTripID400
      | GetActivitiesByTripID401
      | GetActivitiesByTripID403
      | GetActivitiesByTripID404
      | GetActivitiesByTripID500
    >,
    unknown
  >({
    method: "GET",
    url: `/api/v1/trips/${tripID}/activities`,
    params,
    ...requestConfig,
  });
  return res.data;
}

export function getActivitiesByTripIDQueryOptions(
  tripID: GetActivitiesByTripIDPathParams["tripID"],
  params?: GetActivitiesByTripIDQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getActivitiesByTripIDQueryKey(tripID, params);
  return queryOptions<
    GetActivitiesByTripIDQueryResponse,
    ResponseErrorConfig<
      | GetActivitiesByTripID400
      | GetActivitiesByTripID401
      | GetActivitiesByTripID403
      | GetActivitiesByTripID404
      | GetActivitiesByTripID500
    >,
    GetActivitiesByTripIDQueryResponse,
    typeof queryKey
  >({
    enabled: !!tripID,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getActivitiesByTripID(tripID, params, config);
    },
  });
}

/**
 * @description Retrieves paginated activities for a trip, optionally filtered by category
 * @summary Get activities by trip
 * {@link /api/v1/trips/:tripID/activities}
 */
export function useGetActivitiesByTripID<
  TData = GetActivitiesByTripIDQueryResponse,
  TQueryData = GetActivitiesByTripIDQueryResponse,
  TQueryKey extends QueryKey = GetActivitiesByTripIDQueryKey,
>(
  tripID: GetActivitiesByTripIDPathParams["tripID"],
  params?: GetActivitiesByTripIDQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetActivitiesByTripIDQueryResponse,
        ResponseErrorConfig<
          | GetActivitiesByTripID400
          | GetActivitiesByTripID401
          | GetActivitiesByTripID403
          | GetActivitiesByTripID404
          | GetActivitiesByTripID500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getActivitiesByTripIDQueryKey(tripID, params);

  const query = useQuery(
    {
      ...getActivitiesByTripIDQueryOptions(tripID, params, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetActivitiesByTripID400
      | GetActivitiesByTripID401
      | GetActivitiesByTripID403
      | GetActivitiesByTripID404
      | GetActivitiesByTripID500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
