/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  PostApiV1TripsTripidActivitiesActivityidRsvpMutationRequest,
  PostApiV1TripsTripidActivitiesActivityidRsvpMutationResponse,
  PostApiV1TripsTripidActivitiesActivityidRsvpPathParams,
  PostApiV1TripsTripidActivitiesActivityidRsvp400,
  PostApiV1TripsTripidActivitiesActivityidRsvp401,
  PostApiV1TripsTripidActivitiesActivityidRsvp403,
  PostApiV1TripsTripidActivitiesActivityidRsvp404,
  PostApiV1TripsTripidActivitiesActivityidRsvp422,
  PostApiV1TripsTripidActivitiesActivityidRsvp500,
} from "../../types/types.gen.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postApiV1TripsTripidActivitiesActivityidRsvpMutationKey = () =>
  [{ url: "/api/v1/trips/:tripID/activities/:activityID/rsvp" }] as const;

export type PostApiV1TripsTripidActivitiesActivityidRsvpMutationKey =
  ReturnType<typeof postApiV1TripsTripidActivitiesActivityidRsvpMutationKey>;

/**
 * @description Allows a user to RSVP to a specific activity within a trip.
 * @summary RSVP to activity
 * {@link /api/v1/trips/:tripID/activities/:activityID/rsvp}
 */
export async function postApiV1TripsTripidActivitiesActivityidRsvp(
  tripID: PostApiV1TripsTripidActivitiesActivityidRsvpPathParams["tripID"],
  activityID: PostApiV1TripsTripidActivitiesActivityidRsvpPathParams["activityID"],
  data?: PostApiV1TripsTripidActivitiesActivityidRsvpMutationRequest,
  config: Partial<
    RequestConfig<PostApiV1TripsTripidActivitiesActivityidRsvpMutationRequest>
  > & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostApiV1TripsTripidActivitiesActivityidRsvpMutationResponse,
    ResponseErrorConfig<
      | PostApiV1TripsTripidActivitiesActivityidRsvp400
      | PostApiV1TripsTripidActivitiesActivityidRsvp401
      | PostApiV1TripsTripidActivitiesActivityidRsvp403
      | PostApiV1TripsTripidActivitiesActivityidRsvp404
      | PostApiV1TripsTripidActivitiesActivityidRsvp422
      | PostApiV1TripsTripidActivitiesActivityidRsvp500
    >,
    PostApiV1TripsTripidActivitiesActivityidRsvpMutationRequest
  >({
    method: "POST",
    url: `/api/v1/trips/${tripID}/activities/${activityID}/rsvp`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function postApiV1TripsTripidActivitiesActivityidRsvpMutationOptions(
  config: Partial<
    RequestConfig<PostApiV1TripsTripidActivitiesActivityidRsvpMutationRequest>
  > & { client?: typeof fetch } = {},
) {
  const mutationKey = postApiV1TripsTripidActivitiesActivityidRsvpMutationKey();
  return mutationOptions<
    PostApiV1TripsTripidActivitiesActivityidRsvpMutationResponse,
    ResponseErrorConfig<
      | PostApiV1TripsTripidActivitiesActivityidRsvp400
      | PostApiV1TripsTripidActivitiesActivityidRsvp401
      | PostApiV1TripsTripidActivitiesActivityidRsvp403
      | PostApiV1TripsTripidActivitiesActivityidRsvp404
      | PostApiV1TripsTripidActivitiesActivityidRsvp422
      | PostApiV1TripsTripidActivitiesActivityidRsvp500
    >,
    {
      tripID: PostApiV1TripsTripidActivitiesActivityidRsvpPathParams["tripID"];
      activityID: PostApiV1TripsTripidActivitiesActivityidRsvpPathParams["activityID"];
      data?: PostApiV1TripsTripidActivitiesActivityidRsvpMutationRequest;
    },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ tripID, activityID, data }) => {
      return postApiV1TripsTripidActivitiesActivityidRsvp(
        tripID,
        activityID,
        data,
        config,
      );
    },
  });
}

/**
 * @description Allows a user to RSVP to a specific activity within a trip.
 * @summary RSVP to activity
 * {@link /api/v1/trips/:tripID/activities/:activityID/rsvp}
 */
export function usePostApiV1TripsTripidActivitiesActivityidRsvp<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostApiV1TripsTripidActivitiesActivityidRsvpMutationResponse,
      ResponseErrorConfig<
        | PostApiV1TripsTripidActivitiesActivityidRsvp400
        | PostApiV1TripsTripidActivitiesActivityidRsvp401
        | PostApiV1TripsTripidActivitiesActivityidRsvp403
        | PostApiV1TripsTripidActivitiesActivityidRsvp404
        | PostApiV1TripsTripidActivitiesActivityidRsvp422
        | PostApiV1TripsTripidActivitiesActivityidRsvp500
      >,
      {
        tripID: PostApiV1TripsTripidActivitiesActivityidRsvpPathParams["tripID"];
        activityID: PostApiV1TripsTripidActivitiesActivityidRsvpPathParams["activityID"];
        data?: PostApiV1TripsTripidActivitiesActivityidRsvpMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<PostApiV1TripsTripidActivitiesActivityidRsvpMutationRequest>
    > & { client?: typeof fetch };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ??
    postApiV1TripsTripidActivitiesActivityidRsvpMutationKey();

  const baseOptions =
    postApiV1TripsTripidActivitiesActivityidRsvpMutationOptions(
      config,
    ) as UseMutationOptions<
      PostApiV1TripsTripidActivitiesActivityidRsvpMutationResponse,
      ResponseErrorConfig<
        | PostApiV1TripsTripidActivitiesActivityidRsvp400
        | PostApiV1TripsTripidActivitiesActivityidRsvp401
        | PostApiV1TripsTripidActivitiesActivityidRsvp403
        | PostApiV1TripsTripidActivitiesActivityidRsvp404
        | PostApiV1TripsTripidActivitiesActivityidRsvp422
        | PostApiV1TripsTripidActivitiesActivityidRsvp500
      >,
      {
        tripID: PostApiV1TripsTripidActivitiesActivityidRsvpPathParams["tripID"];
        activityID: PostApiV1TripsTripidActivitiesActivityidRsvpPathParams["activityID"];
        data?: PostApiV1TripsTripidActivitiesActivityidRsvpMutationRequest;
      },
      TContext
    >;

  return useMutation<
    PostApiV1TripsTripidActivitiesActivityidRsvpMutationResponse,
    ResponseErrorConfig<
      | PostApiV1TripsTripidActivitiesActivityidRsvp400
      | PostApiV1TripsTripidActivitiesActivityidRsvp401
      | PostApiV1TripsTripidActivitiesActivityidRsvp403
      | PostApiV1TripsTripidActivitiesActivityidRsvp404
      | PostApiV1TripsTripidActivitiesActivityidRsvp422
      | PostApiV1TripsTripidActivitiesActivityidRsvp500
    >,
    {
      tripID: PostApiV1TripsTripidActivitiesActivityidRsvpPathParams["tripID"];
      activityID: PostApiV1TripsTripidActivitiesActivityidRsvpPathParams["activityID"];
      data?: PostApiV1TripsTripidActivitiesActivityidRsvpMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostApiV1TripsTripidActivitiesActivityidRsvpMutationResponse,
    ResponseErrorConfig<
      | PostApiV1TripsTripidActivitiesActivityidRsvp400
      | PostApiV1TripsTripidActivitiesActivityidRsvp401
      | PostApiV1TripsTripidActivitiesActivityidRsvp403
      | PostApiV1TripsTripidActivitiesActivityidRsvp404
      | PostApiV1TripsTripidActivitiesActivityidRsvp422
      | PostApiV1TripsTripidActivitiesActivityidRsvp500
    >,
    {
      tripID: PostApiV1TripsTripidActivitiesActivityidRsvpPathParams["tripID"];
      activityID: PostApiV1TripsTripidActivitiesActivityidRsvpPathParams["activityID"];
      data?: PostApiV1TripsTripidActivitiesActivityidRsvpMutationRequest;
    },
    TContext
  >;
}
