/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  ParseActivityLinkMutationRequest,
  ParseActivityLinkMutationResponse,
  ParseActivityLinkPathParams,
  ParseActivityLink400,
  ParseActivityLink401,
  ParseActivityLink403,
  ParseActivityLink422,
  ParseActivityLink500,
} from "../../types/types.gen.ts";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const parseActivityLinkMutationKey = () =>
  [{ url: "/api/v1/trips/:tripID/activities/parse-link" }] as const;

export type ParseActivityLinkMutationKey = ReturnType<
  typeof parseActivityLinkMutationKey
>;

/**
 * @description Fetches a URL and extracts structured activity fields (name, description, thumbnail) for form autofill. Supports Airbnb, Booking.com, TikTok, Instagram, and generic travel blog URLs.
 * @summary Parse link into activity data
 * {@link /api/v1/trips/:tripID/activities/parse-link}
 */
export async function parseActivityLink(
  tripID: ParseActivityLinkPathParams["tripID"],
  data: ParseActivityLinkMutationRequest,
  config: Partial<RequestConfig<ParseActivityLinkMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    ParseActivityLinkMutationResponse,
    ResponseErrorConfig<
      | ParseActivityLink400
      | ParseActivityLink401
      | ParseActivityLink403
      | ParseActivityLink422
      | ParseActivityLink500
    >,
    ParseActivityLinkMutationRequest
  >({
    method: "POST",
    url: `/api/v1/trips/${tripID}/activities/parse-link`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function parseActivityLinkMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<ParseActivityLinkMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = parseActivityLinkMutationKey();
  return mutationOptions<
    ParseActivityLinkMutationResponse,
    ResponseErrorConfig<
      | ParseActivityLink400
      | ParseActivityLink401
      | ParseActivityLink403
      | ParseActivityLink422
      | ParseActivityLink500
    >,
    {
      tripID: ParseActivityLinkPathParams["tripID"];
      data: ParseActivityLinkMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ tripID, data }) => {
      return parseActivityLink(tripID, data, config);
    },
  });
}

/**
 * @description Fetches a URL and extracts structured activity fields (name, description, thumbnail) for form autofill. Supports Airbnb, Booking.com, TikTok, Instagram, and generic travel blog URLs.
 * @summary Parse link into activity data
 * {@link /api/v1/trips/:tripID/activities/parse-link}
 */
export function useParseActivityLink<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ParseActivityLinkMutationResponse,
      ResponseErrorConfig<
        | ParseActivityLink400
        | ParseActivityLink401
        | ParseActivityLink403
        | ParseActivityLink422
        | ParseActivityLink500
      >,
      {
        tripID: ParseActivityLinkPathParams["tripID"];
        data: ParseActivityLinkMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<ParseActivityLinkMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? parseActivityLinkMutationKey();

  const baseOptions = parseActivityLinkMutationOptions(
    config,
  ) as UseMutationOptions<
    ParseActivityLinkMutationResponse,
    ResponseErrorConfig<
      | ParseActivityLink400
      | ParseActivityLink401
      | ParseActivityLink403
      | ParseActivityLink422
      | ParseActivityLink500
    >,
    {
      tripID: ParseActivityLinkPathParams["tripID"];
      data: ParseActivityLinkMutationRequest;
    },
    TContext
  >;

  return useMutation<
    ParseActivityLinkMutationResponse,
    ResponseErrorConfig<
      | ParseActivityLink400
      | ParseActivityLink401
      | ParseActivityLink403
      | ParseActivityLink422
      | ParseActivityLink500
    >,
    {
      tripID: ParseActivityLinkPathParams["tripID"];
      data: ParseActivityLinkMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    ParseActivityLinkMutationResponse,
    ResponseErrorConfig<
      | ParseActivityLink400
      | ParseActivityLink401
      | ParseActivityLink403
      | ParseActivityLink422
      | ParseActivityLink500
    >,
    {
      tripID: ParseActivityLinkPathParams["tripID"];
      data: ParseActivityLinkMutationRequest;
    },
    TContext
  >;
}
