/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  RemoveCategoryFromActivityMutationResponse,
  RemoveCategoryFromActivityPathParams,
  RemoveCategoryFromActivity400,
  RemoveCategoryFromActivity401,
  RemoveCategoryFromActivity403,
  RemoveCategoryFromActivity404,
  RemoveCategoryFromActivity422,
  RemoveCategoryFromActivity500,
} from "../../types/types.gen.ts";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const removeCategoryFromActivityMutationKey = () =>
  [
    {
      url: "/api/v1/trips/:tripID/activities/:activityID/categories/:categoryName",
    },
  ] as const;

export type RemoveCategoryFromActivityMutationKey = ReturnType<
  typeof removeCategoryFromActivityMutationKey
>;

/**
 * @description Removes a category from an activity
 * @summary Remove category from activity
 * {@link /api/v1/trips/:tripID/activities/:activityID/categories/:categoryName}
 */
export async function removeCategoryFromActivity(
  tripID: RemoveCategoryFromActivityPathParams["tripID"],
  activityID: RemoveCategoryFromActivityPathParams["activityID"],
  categoryName: RemoveCategoryFromActivityPathParams["categoryName"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    RemoveCategoryFromActivityMutationResponse,
    ResponseErrorConfig<
      | RemoveCategoryFromActivity400
      | RemoveCategoryFromActivity401
      | RemoveCategoryFromActivity403
      | RemoveCategoryFromActivity404
      | RemoveCategoryFromActivity422
      | RemoveCategoryFromActivity500
    >,
    unknown
  >({
    method: "DELETE",
    url: `/api/v1/trips/${tripID}/activities/${activityID}/categories/${categoryName}`,
    ...requestConfig,
  });
  return res.data;
}

export function removeCategoryFromActivityMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = removeCategoryFromActivityMutationKey();
  return mutationOptions<
    RemoveCategoryFromActivityMutationResponse,
    ResponseErrorConfig<
      | RemoveCategoryFromActivity400
      | RemoveCategoryFromActivity401
      | RemoveCategoryFromActivity403
      | RemoveCategoryFromActivity404
      | RemoveCategoryFromActivity422
      | RemoveCategoryFromActivity500
    >,
    {
      tripID: RemoveCategoryFromActivityPathParams["tripID"];
      activityID: RemoveCategoryFromActivityPathParams["activityID"];
      categoryName: RemoveCategoryFromActivityPathParams["categoryName"];
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ tripID, activityID, categoryName }) => {
      return removeCategoryFromActivity(
        tripID,
        activityID,
        categoryName,
        config,
      );
    },
  });
}

/**
 * @description Removes a category from an activity
 * @summary Remove category from activity
 * {@link /api/v1/trips/:tripID/activities/:activityID/categories/:categoryName}
 */
export function useRemoveCategoryFromActivity<TContext>(
  options: {
    mutation?: UseMutationOptions<
      RemoveCategoryFromActivityMutationResponse,
      ResponseErrorConfig<
        | RemoveCategoryFromActivity400
        | RemoveCategoryFromActivity401
        | RemoveCategoryFromActivity403
        | RemoveCategoryFromActivity404
        | RemoveCategoryFromActivity422
        | RemoveCategoryFromActivity500
      >,
      {
        tripID: RemoveCategoryFromActivityPathParams["tripID"];
        activityID: RemoveCategoryFromActivityPathParams["activityID"];
        categoryName: RemoveCategoryFromActivityPathParams["categoryName"];
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? removeCategoryFromActivityMutationKey();

  const baseOptions = removeCategoryFromActivityMutationOptions(
    config,
  ) as UseMutationOptions<
    RemoveCategoryFromActivityMutationResponse,
    ResponseErrorConfig<
      | RemoveCategoryFromActivity400
      | RemoveCategoryFromActivity401
      | RemoveCategoryFromActivity403
      | RemoveCategoryFromActivity404
      | RemoveCategoryFromActivity422
      | RemoveCategoryFromActivity500
    >,
    {
      tripID: RemoveCategoryFromActivityPathParams["tripID"];
      activityID: RemoveCategoryFromActivityPathParams["activityID"];
      categoryName: RemoveCategoryFromActivityPathParams["categoryName"];
    },
    TContext
  >;

  return useMutation<
    RemoveCategoryFromActivityMutationResponse,
    ResponseErrorConfig<
      | RemoveCategoryFromActivity400
      | RemoveCategoryFromActivity401
      | RemoveCategoryFromActivity403
      | RemoveCategoryFromActivity404
      | RemoveCategoryFromActivity422
      | RemoveCategoryFromActivity500
    >,
    {
      tripID: RemoveCategoryFromActivityPathParams["tripID"];
      activityID: RemoveCategoryFromActivityPathParams["activityID"];
      categoryName: RemoveCategoryFromActivityPathParams["categoryName"];
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    RemoveCategoryFromActivityMutationResponse,
    ResponseErrorConfig<
      | RemoveCategoryFromActivity400
      | RemoveCategoryFromActivity401
      | RemoveCategoryFromActivity403
      | RemoveCategoryFromActivity404
      | RemoveCategoryFromActivity422
      | RemoveCategoryFromActivity500
    >,
    {
      tripID: RemoveCategoryFromActivityPathParams["tripID"];
      activityID: RemoveCategoryFromActivityPathParams["activityID"];
      categoryName: RemoveCategoryFromActivityPathParams["categoryName"];
    },
    TContext
  >;
}
