/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  GetPitchQueryResponse,
  GetPitchPathParams,
  GetPitch400,
  GetPitch404,
  GetPitch500,
} from "../../types/types.gen.ts";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getPitchQueryKey = (
  tripID: GetPitchPathParams["tripID"],
  pitchID: GetPitchPathParams["pitchID"],
) =>
  [
    {
      url: "/api/v1/trips/:tripID/pitches/:pitchID",
      params: { tripID: tripID, pitchID: pitchID },
    },
  ] as const;

export type GetPitchQueryKey = ReturnType<typeof getPitchQueryKey>;

/**
 * @description Returns a single pitch with presigned URLs for the audio file and associated images (medium_url for each image)
 * @summary Get a pitch by ID
 * {@link /api/v1/trips/:tripID/pitches/:pitchID}
 */
export async function getPitch(
  tripID: GetPitchPathParams["tripID"],
  pitchID: GetPitchPathParams["pitchID"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetPitchQueryResponse,
    ResponseErrorConfig<GetPitch400 | GetPitch404 | GetPitch500>,
    unknown
  >({
    method: "GET",
    url: `/api/v1/trips/${tripID}/pitches/${pitchID}`,
    ...requestConfig,
  });
  return res.data;
}

export function getPitchQueryOptions(
  tripID: GetPitchPathParams["tripID"],
  pitchID: GetPitchPathParams["pitchID"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getPitchQueryKey(tripID, pitchID);
  return queryOptions<
    GetPitchQueryResponse,
    ResponseErrorConfig<GetPitch400 | GetPitch404 | GetPitch500>,
    GetPitchQueryResponse,
    typeof queryKey
  >({
    enabled: !!(tripID && pitchID),
    queryKey,
    queryFn: async ({ signal }) => {
      if (!config.signal) {
        config.signal = signal;
      }
      return getPitch(tripID, pitchID, config);
    },
  });
}

/**
 * @description Returns a single pitch with presigned URLs for the audio file and associated images (medium_url for each image)
 * @summary Get a pitch by ID
 * {@link /api/v1/trips/:tripID/pitches/:pitchID}
 */
export function useGetPitch<
  TData = GetPitchQueryResponse,
  TQueryData = GetPitchQueryResponse,
  TQueryKey extends QueryKey = GetPitchQueryKey,
>(
  tripID: GetPitchPathParams["tripID"],
  pitchID: GetPitchPathParams["pitchID"],
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetPitchQueryResponse,
        ResponseErrorConfig<GetPitch400 | GetPitch404 | GetPitch500>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? getPitchQueryKey(tripID, pitchID);

  const query = useQuery(
    {
      ...getPitchQueryOptions(tripID, pitchID, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<GetPitch400 | GetPitch404 | GetPitch500>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
