/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type {
  GetPitchQueryResponse,
  GetPitchPathParams,
  GetPitch400,
  GetPitch404,
  GetPitch500,
} from "../../types/types.gen.ts";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getPitchSuspenseQueryKey = (
  tripID: GetPitchPathParams["tripID"],
  pitchID: GetPitchPathParams["pitchID"],
) =>
  [
    {
      url: "/api/v1/trips/:tripID/pitches/:pitchID",
      params: { tripID: tripID, pitchID: pitchID },
    },
  ] as const;

export type GetPitchSuspenseQueryKey = ReturnType<
  typeof getPitchSuspenseQueryKey
>;

/**
 * @description Returns a single pitch with a presigned URL for the audio file
 * @summary Get a pitch by ID
 * {@link /api/v1/trips/:tripID/pitches/:pitchID}
 */
export async function getPitchSuspense(
  tripID: GetPitchPathParams["tripID"],
  pitchID: GetPitchPathParams["pitchID"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetPitchQueryResponse,
    ResponseErrorConfig<GetPitch400 | GetPitch404 | GetPitch500>,
    unknown
  >({
    method: "GET",
    url: `/api/v1/trips/${tripID}/pitches/${pitchID}`,
    ...requestConfig,
  });
  return res.data;
}

export function getPitchSuspenseQueryOptions(
  tripID: GetPitchPathParams["tripID"],
  pitchID: GetPitchPathParams["pitchID"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getPitchSuspenseQueryKey(tripID, pitchID);
  return queryOptions<
    GetPitchQueryResponse,
    ResponseErrorConfig<GetPitch400 | GetPitch404 | GetPitch500>,
    GetPitchQueryResponse,
    typeof queryKey
  >({
    enabled: !!(tripID && pitchID),
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getPitchSuspense(tripID, pitchID, config);
    },
  });
}

/**
 * @description Returns a single pitch with a presigned URL for the audio file
 * @summary Get a pitch by ID
 * {@link /api/v1/trips/:tripID/pitches/:pitchID}
 */
export function useGetPitchSuspense<
  TData = GetPitchQueryResponse,
  TQueryKey extends QueryKey = GetPitchSuspenseQueryKey,
>(
  tripID: GetPitchPathParams["tripID"],
  pitchID: GetPitchPathParams["pitchID"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetPitchQueryResponse,
        ResponseErrorConfig<GetPitch400 | GetPitch404 | GetPitch500>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getPitchSuspenseQueryKey(tripID, pitchID);

  const query = useSuspenseQuery(
    {
      ...getPitchSuspenseQueryOptions(tripID, pitchID, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<GetPitch400 | GetPitch404 | GetPitch500>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
