/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { SendNotificationMutationRequest, SendNotificationMutationResponse, SendNotification400, SendNotification422, SendNotification500 } from "../../types/types.gen.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const sendNotificationMutationKey = () => [{ url: '/api/v1/notifications/send' }] as const

export type SendNotificationMutationKey = ReturnType<typeof sendNotificationMutationKey>

/**
 * @description Sends a push notification to a single user
 * @summary Send notification to user
 * {@link /api/v1/notifications/send}
 */
export async function sendNotification(data: SendNotificationMutationRequest, config: Partial<RequestConfig<SendNotificationMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<SendNotificationMutationResponse, ResponseErrorConfig<SendNotification400 | SendNotification422 | SendNotification500>, SendNotificationMutationRequest>({ method : "POST", url : `/api/v1/notifications/send`, data : requestData, ... requestConfig })  
  return res.data
}

export function sendNotificationMutationOptions(config: Partial<RequestConfig<SendNotificationMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = sendNotificationMutationKey()
  return mutationOptions<SendNotificationMutationResponse, ResponseErrorConfig<SendNotification400 | SendNotification422 | SendNotification500>, {data: SendNotificationMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return sendNotification(data, config)
    },
  })
}

/**
 * @description Sends a push notification to a single user
 * @summary Send notification to user
 * {@link /api/v1/notifications/send}
 */
export function useSendNotification<TContext>(options: 
{
  mutation?: UseMutationOptions<SendNotificationMutationResponse, ResponseErrorConfig<SendNotification400 | SendNotification422 | SendNotification500>, {data: SendNotificationMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<SendNotificationMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? sendNotificationMutationKey()

  const baseOptions = sendNotificationMutationOptions(config) as UseMutationOptions<SendNotificationMutationResponse, ResponseErrorConfig<SendNotification400 | SendNotification422 | SendNotification500>, {data: SendNotificationMutationRequest}, TContext>

  return useMutation<SendNotificationMutationResponse, ResponseErrorConfig<SendNotification400 | SendNotification422 | SendNotification500>, {data: SendNotificationMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<SendNotificationMutationResponse, ResponseErrorConfig<SendNotification400 | SendNotification422 | SendNotification500>, {data: SendNotificationMutationRequest}, TContext>
}