/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { SendBulkNotificationMutationRequest, SendBulkNotificationMutationResponse, SendBulkNotification400, SendBulkNotification422, SendBulkNotification500 } from "../../types/types.gen.ts";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const sendBulkNotificationMutationKey = () => [{ url: '/api/v1/notifications/send-bulk' }] as const

export type SendBulkNotificationMutationKey = ReturnType<typeof sendBulkNotificationMutationKey>

/**
 * @description Sends push notifications to multiple users
 * @summary Send bulk notifications
 * {@link /api/v1/notifications/send-bulk}
 */
export async function sendBulkNotification(data: SendBulkNotificationMutationRequest, config: Partial<RequestConfig<SendBulkNotificationMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<SendBulkNotificationMutationResponse, ResponseErrorConfig<SendBulkNotification400 | SendBulkNotification422 | SendBulkNotification500>, SendBulkNotificationMutationRequest>({ method : "POST", url : `/api/v1/notifications/send-bulk`, data : requestData, ... requestConfig })  
  return res.data
}

export function sendBulkNotificationMutationOptions(config: Partial<RequestConfig<SendBulkNotificationMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = sendBulkNotificationMutationKey()
  return mutationOptions<SendBulkNotificationMutationResponse, ResponseErrorConfig<SendBulkNotification400 | SendBulkNotification422 | SendBulkNotification500>, {data: SendBulkNotificationMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return sendBulkNotification(data, config)
    },
  })
}

/**
 * @description Sends push notifications to multiple users
 * @summary Send bulk notifications
 * {@link /api/v1/notifications/send-bulk}
 */
export function useSendBulkNotification<TContext>(options: 
{
  mutation?: UseMutationOptions<SendBulkNotificationMutationResponse, ResponseErrorConfig<SendBulkNotification400 | SendBulkNotification422 | SendBulkNotification500>, {data: SendBulkNotificationMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<SendBulkNotificationMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? sendBulkNotificationMutationKey()

  const baseOptions = sendBulkNotificationMutationOptions(config) as UseMutationOptions<SendBulkNotificationMutationResponse, ResponseErrorConfig<SendBulkNotification400 | SendBulkNotification422 | SendBulkNotification500>, {data: SendBulkNotificationMutationRequest}, TContext>

  return useMutation<SendBulkNotificationMutationResponse, ResponseErrorConfig<SendBulkNotification400 | SendBulkNotification422 | SendBulkNotification500>, {data: SendBulkNotificationMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<SendBulkNotificationMutationResponse, ResponseErrorConfig<SendBulkNotification400 | SendBulkNotification422 | SendBulkNotification500>, {data: SendBulkNotificationMutationRequest}, TContext>
}