/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  DemoteFromAdminMutationResponse,
  DemoteFromAdminPathParams,
  DemoteFromAdmin400,
  DemoteFromAdmin404,
  DemoteFromAdmin500,
} from "../../types/types.gen.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const demoteFromAdminMutationKey = () =>
  [{ url: "/api/v1/trips/:tripID/members/:userID/demote" }] as const;

export type DemoteFromAdminMutationKey = ReturnType<
  typeof demoteFromAdminMutationKey
>;

/**
 * @description Demotes an admin to regular member role
 * @summary Demote admin to member
 * {@link /api/v1/trips/:tripID/members/:userID/demote}
 */
export async function demoteFromAdmin(
  tripID: DemoteFromAdminPathParams["tripID"],
  userID: DemoteFromAdminPathParams["userID"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DemoteFromAdminMutationResponse,
    ResponseErrorConfig<
      DemoteFromAdmin400 | DemoteFromAdmin404 | DemoteFromAdmin500
    >,
    unknown
  >({
    method: "POST",
    url: `/api/v1/trips/${tripID}/members/${userID}/demote`,
    ...requestConfig,
  });
  return res.data;
}

export function demoteFromAdminMutationOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const mutationKey = demoteFromAdminMutationKey();
  return mutationOptions<
    DemoteFromAdminMutationResponse,
    ResponseErrorConfig<
      DemoteFromAdmin400 | DemoteFromAdmin404 | DemoteFromAdmin500
    >,
    {
      tripID: DemoteFromAdminPathParams["tripID"];
      userID: DemoteFromAdminPathParams["userID"];
    },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ tripID, userID }) => {
      return demoteFromAdmin(tripID, userID, config);
    },
  });
}

/**
 * @description Demotes an admin to regular member role
 * @summary Demote admin to member
 * {@link /api/v1/trips/:tripID/members/:userID/demote}
 */
export function useDemoteFromAdmin<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DemoteFromAdminMutationResponse,
      ResponseErrorConfig<
        DemoteFromAdmin400 | DemoteFromAdmin404 | DemoteFromAdmin500
      >,
      {
        tripID: DemoteFromAdminPathParams["tripID"];
        userID: DemoteFromAdminPathParams["userID"];
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? demoteFromAdminMutationKey();

  const baseOptions = demoteFromAdminMutationOptions(
    config,
  ) as UseMutationOptions<
    DemoteFromAdminMutationResponse,
    ResponseErrorConfig<
      DemoteFromAdmin400 | DemoteFromAdmin404 | DemoteFromAdmin500
    >,
    {
      tripID: DemoteFromAdminPathParams["tripID"];
      userID: DemoteFromAdminPathParams["userID"];
    },
    TContext
  >;

  return useMutation<
    DemoteFromAdminMutationResponse,
    ResponseErrorConfig<
      DemoteFromAdmin400 | DemoteFromAdmin404 | DemoteFromAdmin500
    >,
    {
      tripID: DemoteFromAdminPathParams["tripID"];
      userID: DemoteFromAdminPathParams["userID"];
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DemoteFromAdminMutationResponse,
    ResponseErrorConfig<
      DemoteFromAdmin400 | DemoteFromAdmin404 | DemoteFromAdmin500
    >,
    {
      tripID: DemoteFromAdminPathParams["tripID"];
      userID: DemoteFromAdminPathParams["userID"];
    },
    TContext
  >;
}
