/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type {
  GetTripMembersQueryResponse,
  GetTripMembersPathParams,
  GetTripMembersQueryParams,
  GetTripMembers400,
  GetTripMembers401,
  GetTripMembers404,
  GetTripMembers500,
} from "../../types/types.gen.ts";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getTripMembersSuspenseQueryKey = (
  tripID: GetTripMembersPathParams["tripID"],
  params: GetTripMembersQueryParams = {},
) =>
  [
    { url: "/api/v1/trips/:tripID/memberships", params: { tripID: tripID } },
    ...(params ? [params] : []),
  ] as const;

export type GetTripMembersSuspenseQueryKey = ReturnType<
  typeof getTripMembersSuspenseQueryKey
>;

/**
 * @description Retrieves all members of a trip
 * @summary Get trip members
 * {@link /api/v1/trips/:tripID/memberships}
 */
export async function getTripMembersSuspense(
  tripID: GetTripMembersPathParams["tripID"],
  params?: GetTripMembersQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetTripMembersQueryResponse,
    ResponseErrorConfig<
      | GetTripMembers400
      | GetTripMembers401
      | GetTripMembers404
      | GetTripMembers500
    >,
    unknown
  >({
    method: "GET",
    url: `/api/v1/trips/${tripID}/memberships`,
    params,
    ...requestConfig,
  });
  return res.data;
}

export function getTripMembersSuspenseQueryOptions(
  tripID: GetTripMembersPathParams["tripID"],
  params?: GetTripMembersQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getTripMembersSuspenseQueryKey(tripID, params);
  return queryOptions<
    GetTripMembersQueryResponse,
    ResponseErrorConfig<
      | GetTripMembers400
      | GetTripMembers401
      | GetTripMembers404
      | GetTripMembers500
    >,
    GetTripMembersQueryResponse,
    typeof queryKey
  >({
    enabled: !!tripID,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getTripMembersSuspense(tripID, params, config);
    },
  });
}

/**
 * @description Retrieves all members of a trip
 * @summary Get trip members
 * {@link /api/v1/trips/:tripID/memberships}
 */
export function useGetTripMembersSuspense<
  TData = GetTripMembersQueryResponse,
  TQueryKey extends QueryKey = GetTripMembersSuspenseQueryKey,
>(
  tripID: GetTripMembersPathParams["tripID"],
  params?: GetTripMembersQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetTripMembersQueryResponse,
        ResponseErrorConfig<
          | GetTripMembers400
          | GetTripMembers401
          | GetTripMembers404
          | GetTripMembers500
        >,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getTripMembersSuspenseQueryKey(tripID, params);

  const query = useSuspenseQuery(
    {
      ...getTripMembersSuspenseQueryOptions(tripID, params, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetTripMembers400
      | GetTripMembers401
      | GetTripMembers404
      | GetTripMembers500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
