/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type {
  GetMembershipQueryResponse,
  GetMembershipPathParams,
  GetMembership400,
  GetMembership404,
  GetMembership500,
} from "../../types/types.gen.ts";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getMembershipSuspenseQueryKey = (
  tripID: GetMembershipPathParams["tripID"],
  userID: GetMembershipPathParams["userID"],
) =>
  [
    {
      url: "/api/v1/trips/:tripID/memberships/:userID",
      params: { tripID: tripID, userID: userID },
    },
  ] as const;

export type GetMembershipSuspenseQueryKey = ReturnType<
  typeof getMembershipSuspenseQueryKey
>;

/**
 * @description Retrieves the membership for a user in a trip
 * @summary Get membership
 * {@link /api/v1/trips/:tripID/memberships/:userID}
 */
export async function getMembershipSuspense(
  tripID: GetMembershipPathParams["tripID"],
  userID: GetMembershipPathParams["userID"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetMembershipQueryResponse,
    ResponseErrorConfig<GetMembership400 | GetMembership404 | GetMembership500>,
    unknown
  >({
    method: "GET",
    url: `/api/v1/trips/${tripID}/memberships/${userID}`,
    ...requestConfig,
  });
  return res.data;
}

export function getMembershipSuspenseQueryOptions(
  tripID: GetMembershipPathParams["tripID"],
  userID: GetMembershipPathParams["userID"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getMembershipSuspenseQueryKey(tripID, userID);
  return queryOptions<
    GetMembershipQueryResponse,
    ResponseErrorConfig<GetMembership400 | GetMembership404 | GetMembership500>,
    GetMembershipQueryResponse,
    typeof queryKey
  >({
    enabled: !!(tripID && userID),
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getMembershipSuspense(tripID, userID, config);
    },
  });
}

/**
 * @description Retrieves the membership for a user in a trip
 * @summary Get membership
 * {@link /api/v1/trips/:tripID/memberships/:userID}
 */
export function useGetMembershipSuspense<
  TData = GetMembershipQueryResponse,
  TQueryKey extends QueryKey = GetMembershipSuspenseQueryKey,
>(
  tripID: GetMembershipPathParams["tripID"],
  userID: GetMembershipPathParams["userID"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetMembershipQueryResponse,
        ResponseErrorConfig<
          GetMembership400 | GetMembership404 | GetMembership500
        >,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getMembershipSuspenseQueryKey(tripID, userID);

  const query = useSuspenseQuery(
    {
      ...getMembershipSuspenseQueryOptions(tripID, userID, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<GetMembership400 | GetMembership404 | GetMembership500>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
