/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  JoinTripByInviteMutationResponse,
  JoinTripByInvitePathParams,
  JoinTripByInvite400,
  JoinTripByInvite401,
  JoinTripByInvite500,
} from "../../types/types.gen.ts";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const joinTripByInviteMutationKey = () =>
  [{ url: "/api/v1/trip-invites/:code/join" }] as const;

export type JoinTripByInviteMutationKey = ReturnType<
  typeof joinTripByInviteMutationKey
>;

/**
 * @description Adds the authenticated user to a trip using an invite code
 * @summary Join trip by invite code
 * {@link /api/v1/trip-invites/:code/join}
 */
export async function joinTripByInvite(
  code: JoinTripByInvitePathParams["code"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    JoinTripByInviteMutationResponse,
    ResponseErrorConfig<
      JoinTripByInvite400 | JoinTripByInvite401 | JoinTripByInvite500
    >,
    unknown
  >({
    method: "POST",
    url: `/api/v1/trip-invites/${code}/join`,
    ...requestConfig,
  });
  return res.data;
}

export function joinTripByInviteMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = joinTripByInviteMutationKey();
  return mutationOptions<
    JoinTripByInviteMutationResponse,
    ResponseErrorConfig<
      JoinTripByInvite400 | JoinTripByInvite401 | JoinTripByInvite500
    >,
    { code: JoinTripByInvitePathParams["code"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ code }) => {
      return joinTripByInvite(code, config);
    },
  });
}

/**
 * @description Adds the authenticated user to a trip using an invite code
 * @summary Join trip by invite code
 * {@link /api/v1/trip-invites/:code/join}
 */
export function useJoinTripByInvite<TContext>(
  options: {
    mutation?: UseMutationOptions<
      JoinTripByInviteMutationResponse,
      ResponseErrorConfig<
        JoinTripByInvite400 | JoinTripByInvite401 | JoinTripByInvite500
      >,
      { code: JoinTripByInvitePathParams["code"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? joinTripByInviteMutationKey();

  const baseOptions = joinTripByInviteMutationOptions(
    config,
  ) as UseMutationOptions<
    JoinTripByInviteMutationResponse,
    ResponseErrorConfig<
      JoinTripByInvite400 | JoinTripByInvite401 | JoinTripByInvite500
    >,
    { code: JoinTripByInvitePathParams["code"] },
    TContext
  >;

  return useMutation<
    JoinTripByInviteMutationResponse,
    ResponseErrorConfig<
      JoinTripByInvite400 | JoinTripByInvite401 | JoinTripByInvite500
    >,
    { code: JoinTripByInvitePathParams["code"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    JoinTripByInviteMutationResponse,
    ResponseErrorConfig<
      JoinTripByInvite400 | JoinTripByInvite401 | JoinTripByInvite500
    >,
    { code: JoinTripByInvitePathParams["code"] },
    TContext
  >;
}
