/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  RemoveMemberMutationResponse,
  RemoveMemberPathParams,
  RemoveMember400,
  RemoveMember404,
  RemoveMember500,
} from "../../types/types.gen.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const removeMemberMutationKey = () =>
  [{ url: "/api/v1/trips/:tripID/members/:userID" }] as const;

export type RemoveMemberMutationKey = ReturnType<
  typeof removeMemberMutationKey
>;

/**
 * @description Removes a user from a trip
 * @summary Remove member from trip
 * {@link /api/v1/trips/:tripID/members/:userID}
 */
export async function removeMember(
  tripID: RemoveMemberPathParams["tripID"],
  userID: RemoveMemberPathParams["userID"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    RemoveMemberMutationResponse,
    ResponseErrorConfig<RemoveMember400 | RemoveMember404 | RemoveMember500>,
    unknown
  >({
    method: "DELETE",
    url: `/api/v1/trips/${tripID}/members/${userID}`,
    ...requestConfig,
  });
  return res.data;
}

export function removeMemberMutationOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const mutationKey = removeMemberMutationKey();
  return mutationOptions<
    RemoveMemberMutationResponse,
    ResponseErrorConfig<RemoveMember400 | RemoveMember404 | RemoveMember500>,
    {
      tripID: RemoveMemberPathParams["tripID"];
      userID: RemoveMemberPathParams["userID"];
    },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ tripID, userID }) => {
      return removeMember(tripID, userID, config);
    },
  });
}

/**
 * @description Removes a user from a trip
 * @summary Remove member from trip
 * {@link /api/v1/trips/:tripID/members/:userID}
 */
export function useRemoveMember<TContext>(
  options: {
    mutation?: UseMutationOptions<
      RemoveMemberMutationResponse,
      ResponseErrorConfig<RemoveMember400 | RemoveMember404 | RemoveMember500>,
      {
        tripID: RemoveMemberPathParams["tripID"];
        userID: RemoveMemberPathParams["userID"];
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? removeMemberMutationKey();

  const baseOptions = removeMemberMutationOptions(config) as UseMutationOptions<
    RemoveMemberMutationResponse,
    ResponseErrorConfig<RemoveMember400 | RemoveMember404 | RemoveMember500>,
    {
      tripID: RemoveMemberPathParams["tripID"];
      userID: RemoveMemberPathParams["userID"];
    },
    TContext
  >;

  return useMutation<
    RemoveMemberMutationResponse,
    ResponseErrorConfig<RemoveMember400 | RemoveMember404 | RemoveMember500>,
    {
      tripID: RemoveMemberPathParams["tripID"];
      userID: RemoveMemberPathParams["userID"];
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    RemoveMemberMutationResponse,
    ResponseErrorConfig<RemoveMember400 | RemoveMember404 | RemoveMember500>,
    {
      tripID: RemoveMemberPathParams["tripID"];
      userID: RemoveMemberPathParams["userID"];
    },
    TContext
  >;
}
