/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type {
  UpdateMembershipMutationRequest,
  UpdateMembershipMutationResponse,
  UpdateMembershipPathParams,
  UpdateMembership400,
  UpdateMembership404,
  UpdateMembership422,
  UpdateMembership500,
} from "../../types/types.gen.ts";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const updateMembershipMutationKey = () =>
  [{ url: "/api/v1/trips/:tripID/memberships/:userID" }] as const;

export type UpdateMembershipMutationKey = ReturnType<
  typeof updateMembershipMutationKey
>;

/**
 * @description Updates a membership
 * @summary Update membership
 * {@link /api/v1/trips/:tripID/memberships/:userID}
 */
export async function updateMembership(
  tripID: UpdateMembershipPathParams["tripID"],
  userID: UpdateMembershipPathParams["userID"],
  data?: UpdateMembershipMutationRequest,
  config: Partial<RequestConfig<UpdateMembershipMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    UpdateMembershipMutationResponse,
    ResponseErrorConfig<
      | UpdateMembership400
      | UpdateMembership404
      | UpdateMembership422
      | UpdateMembership500
    >,
    UpdateMembershipMutationRequest
  >({
    method: "PATCH",
    url: `/api/v1/trips/${tripID}/memberships/${userID}`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function updateMembershipMutationOptions(
  config: Partial<RequestConfig<UpdateMembershipMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const mutationKey = updateMembershipMutationKey();
  return mutationOptions<
    UpdateMembershipMutationResponse,
    ResponseErrorConfig<
      | UpdateMembership400
      | UpdateMembership404
      | UpdateMembership422
      | UpdateMembership500
    >,
    {
      tripID: UpdateMembershipPathParams["tripID"];
      userID: UpdateMembershipPathParams["userID"];
      data?: UpdateMembershipMutationRequest;
    },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ tripID, userID, data }) => {
      return updateMembership(tripID, userID, data, config);
    },
  });
}

/**
 * @description Updates a membership
 * @summary Update membership
 * {@link /api/v1/trips/:tripID/memberships/:userID}
 */
export function useUpdateMembership<TContext>(
  options: {
    mutation?: UseMutationOptions<
      UpdateMembershipMutationResponse,
      ResponseErrorConfig<
        | UpdateMembership400
        | UpdateMembership404
        | UpdateMembership422
        | UpdateMembership500
      >,
      {
        tripID: UpdateMembershipPathParams["tripID"];
        userID: UpdateMembershipPathParams["userID"];
        data?: UpdateMembershipMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<UpdateMembershipMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? updateMembershipMutationKey();

  const baseOptions = updateMembershipMutationOptions(
    config,
  ) as UseMutationOptions<
    UpdateMembershipMutationResponse,
    ResponseErrorConfig<
      | UpdateMembership400
      | UpdateMembership404
      | UpdateMembership422
      | UpdateMembership500
    >,
    {
      tripID: UpdateMembershipPathParams["tripID"];
      userID: UpdateMembershipPathParams["userID"];
      data?: UpdateMembershipMutationRequest;
    },
    TContext
  >;

  return useMutation<
    UpdateMembershipMutationResponse,
    ResponseErrorConfig<
      | UpdateMembership400
      | UpdateMembership404
      | UpdateMembership422
      | UpdateMembership500
    >,
    {
      tripID: UpdateMembershipPathParams["tripID"];
      userID: UpdateMembershipPathParams["userID"];
      data?: UpdateMembershipMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    UpdateMembershipMutationResponse,
    ResponseErrorConfig<
      | UpdateMembership400
      | UpdateMembership404
      | UpdateMembership422
      | UpdateMembership500
    >,
    {
      tripID: UpdateMembershipPathParams["tripID"];
      userID: UpdateMembershipPathParams["userID"];
      data?: UpdateMembershipMutationRequest;
    },
    TContext
  >;
}
