/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  UpdateMembershipNotificationPreferencesMutationRequest,
  UpdateMembershipNotificationPreferencesMutationResponse,
  UpdateMembershipNotificationPreferencesPathParams,
  UpdateMembershipNotificationPreferences400,
  UpdateMembershipNotificationPreferences401,
  UpdateMembershipNotificationPreferences403,
  UpdateMembershipNotificationPreferences404,
  UpdateMembershipNotificationPreferences422,
  UpdateMembershipNotificationPreferences500,
} from "../../types/types.gen.ts";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const updateMembershipNotificationPreferencesMutationKey = () =>
  [
    {
      url: "/api/v1/trips/:tripID/memberships/:userID/notification-preferences",
    },
  ] as const;

export type UpdateMembershipNotificationPreferencesMutationKey = ReturnType<
  typeof updateMembershipNotificationPreferencesMutationKey
>;

/**
 * @description Updates the notification preferences for a membership (self only)
 * @summary Update notification preferences
 * {@link /api/v1/trips/:tripID/memberships/:userID/notification-preferences}
 */
export async function updateMembershipNotificationPreferences(
  tripID: UpdateMembershipNotificationPreferencesPathParams["tripID"],
  userID: UpdateMembershipNotificationPreferencesPathParams["userID"],
  data: UpdateMembershipNotificationPreferencesMutationRequest,
  config: Partial<
    RequestConfig<UpdateMembershipNotificationPreferencesMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    UpdateMembershipNotificationPreferencesMutationResponse,
    ResponseErrorConfig<
      | UpdateMembershipNotificationPreferences400
      | UpdateMembershipNotificationPreferences401
      | UpdateMembershipNotificationPreferences403
      | UpdateMembershipNotificationPreferences404
      | UpdateMembershipNotificationPreferences422
      | UpdateMembershipNotificationPreferences500
    >,
    UpdateMembershipNotificationPreferencesMutationRequest
  >({
    method: "PATCH",
    url: `/api/v1/trips/${tripID}/memberships/${userID}/notification-preferences`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function updateMembershipNotificationPreferencesMutationOptions<
  TContext = unknown,
>(
  config: Partial<
    RequestConfig<UpdateMembershipNotificationPreferencesMutationRequest>
  > & { client?: Client } = {},
) {
  const mutationKey = updateMembershipNotificationPreferencesMutationKey();
  return mutationOptions<
    UpdateMembershipNotificationPreferencesMutationResponse,
    ResponseErrorConfig<
      | UpdateMembershipNotificationPreferences400
      | UpdateMembershipNotificationPreferences401
      | UpdateMembershipNotificationPreferences403
      | UpdateMembershipNotificationPreferences404
      | UpdateMembershipNotificationPreferences422
      | UpdateMembershipNotificationPreferences500
    >,
    {
      tripID: UpdateMembershipNotificationPreferencesPathParams["tripID"];
      userID: UpdateMembershipNotificationPreferencesPathParams["userID"];
      data: UpdateMembershipNotificationPreferencesMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ tripID, userID, data }) => {
      return updateMembershipNotificationPreferences(
        tripID,
        userID,
        data,
        config,
      );
    },
  });
}

/**
 * @description Updates the notification preferences for a membership (self only)
 * @summary Update notification preferences
 * {@link /api/v1/trips/:tripID/memberships/:userID/notification-preferences}
 */
export function useUpdateMembershipNotificationPreferences<TContext>(
  options: {
    mutation?: UseMutationOptions<
      UpdateMembershipNotificationPreferencesMutationResponse,
      ResponseErrorConfig<
        | UpdateMembershipNotificationPreferences400
        | UpdateMembershipNotificationPreferences401
        | UpdateMembershipNotificationPreferences403
        | UpdateMembershipNotificationPreferences404
        | UpdateMembershipNotificationPreferences422
        | UpdateMembershipNotificationPreferences500
      >,
      {
        tripID: UpdateMembershipNotificationPreferencesPathParams["tripID"];
        userID: UpdateMembershipNotificationPreferencesPathParams["userID"];
        data: UpdateMembershipNotificationPreferencesMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<UpdateMembershipNotificationPreferencesMutationRequest>
    > & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ??
    updateMembershipNotificationPreferencesMutationKey();

  const baseOptions = updateMembershipNotificationPreferencesMutationOptions(
    config,
  ) as UseMutationOptions<
    UpdateMembershipNotificationPreferencesMutationResponse,
    ResponseErrorConfig<
      | UpdateMembershipNotificationPreferences400
      | UpdateMembershipNotificationPreferences401
      | UpdateMembershipNotificationPreferences403
      | UpdateMembershipNotificationPreferences404
      | UpdateMembershipNotificationPreferences422
      | UpdateMembershipNotificationPreferences500
    >,
    {
      tripID: UpdateMembershipNotificationPreferencesPathParams["tripID"];
      userID: UpdateMembershipNotificationPreferencesPathParams["userID"];
      data: UpdateMembershipNotificationPreferencesMutationRequest;
    },
    TContext
  >;

  return useMutation<
    UpdateMembershipNotificationPreferencesMutationResponse,
    ResponseErrorConfig<
      | UpdateMembershipNotificationPreferences400
      | UpdateMembershipNotificationPreferences401
      | UpdateMembershipNotificationPreferences403
      | UpdateMembershipNotificationPreferences404
      | UpdateMembershipNotificationPreferences422
      | UpdateMembershipNotificationPreferences500
    >,
    {
      tripID: UpdateMembershipNotificationPreferencesPathParams["tripID"];
      userID: UpdateMembershipNotificationPreferencesPathParams["userID"];
      data: UpdateMembershipNotificationPreferencesMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    UpdateMembershipNotificationPreferencesMutationResponse,
    ResponseErrorConfig<
      | UpdateMembershipNotificationPreferences400
      | UpdateMembershipNotificationPreferences401
      | UpdateMembershipNotificationPreferences403
      | UpdateMembershipNotificationPreferences404
      | UpdateMembershipNotificationPreferences422
      | UpdateMembershipNotificationPreferences500
    >,
    {
      tripID: UpdateMembershipNotificationPreferencesPathParams["tripID"];
      userID: UpdateMembershipNotificationPreferencesPathParams["userID"];
      data: UpdateMembershipNotificationPreferencesMutationRequest;
    },
    TContext
  >;
}
