/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  GetCategoriesByTripIDQueryResponse,
  GetCategoriesByTripIDPathParams,
  GetCategoriesByTripIDQueryParams,
  GetCategoriesByTripID400,
  GetCategoriesByTripID401,
  GetCategoriesByTripID403,
  GetCategoriesByTripID404,
  GetCategoriesByTripID500,
} from "../../types/types.gen.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getCategoriesByTripIDQueryKey = (
  tripID: GetCategoriesByTripIDPathParams["tripID"],
  params?: GetCategoriesByTripIDQueryParams,
) =>
  [
    { url: "/api/v1/trips/:tripID/categories", params: { tripID: tripID } },
    ...(params ? [params] : []),
  ] as const;

export type GetCategoriesByTripIDQueryKey = ReturnType<
  typeof getCategoriesByTripIDQueryKey
>;

/**
 * @description Retrieves all categories for a trip
 * @summary Get categories by trip
 * {@link /api/v1/trips/:tripID/categories}
 */
export async function getCategoriesByTripID(
  tripID: GetCategoriesByTripIDPathParams["tripID"],
  params?: GetCategoriesByTripIDQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetCategoriesByTripIDQueryResponse,
    ResponseErrorConfig<
      | GetCategoriesByTripID400
      | GetCategoriesByTripID401
      | GetCategoriesByTripID403
      | GetCategoriesByTripID404
      | GetCategoriesByTripID500
    >,
    unknown
  >({
    method: "GET",
    url: `/api/v1/trips/${tripID}/categories`,
    params,
    ...requestConfig,
  });
  return res.data;
}

export function getCategoriesByTripIDQueryOptions(
  tripID: GetCategoriesByTripIDPathParams["tripID"],
  params?: GetCategoriesByTripIDQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getCategoriesByTripIDQueryKey(tripID, params);
  return queryOptions<
    GetCategoriesByTripIDQueryResponse,
    ResponseErrorConfig<
      | GetCategoriesByTripID400
      | GetCategoriesByTripID401
      | GetCategoriesByTripID403
      | GetCategoriesByTripID404
      | GetCategoriesByTripID500
    >,
    GetCategoriesByTripIDQueryResponse,
    typeof queryKey
  >({
    enabled: !!tripID,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getCategoriesByTripID(tripID, params, config);
    },
  });
}

/**
 * @description Retrieves all categories for a trip
 * @summary Get categories by trip
 * {@link /api/v1/trips/:tripID/categories}
 */
export function useGetCategoriesByTripID<
  TData = GetCategoriesByTripIDQueryResponse,
  TQueryData = GetCategoriesByTripIDQueryResponse,
  TQueryKey extends QueryKey = GetCategoriesByTripIDQueryKey,
>(
  tripID: GetCategoriesByTripIDPathParams["tripID"],
  params?: GetCategoriesByTripIDQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetCategoriesByTripIDQueryResponse,
        ResponseErrorConfig<
          | GetCategoriesByTripID400
          | GetCategoriesByTripID401
          | GetCategoriesByTripID403
          | GetCategoriesByTripID404
          | GetCategoriesByTripID500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getCategoriesByTripIDQueryKey(tripID, params);

  const query = useQuery(
    {
      ...getCategoriesByTripIDQueryOptions(tripID, params, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetCategoriesByTripID400
      | GetCategoriesByTripID401
      | GetCategoriesByTripID403
      | GetCategoriesByTripID404
      | GetCategoriesByTripID500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
