/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  HideCategoryMutationResponse,
  HideCategoryPathParams,
  HideCategory400,
  HideCategory401,
  HideCategory403,
  HideCategory404,
  HideCategory500,
} from "../../types/types.gen.ts";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const hideCategoryMutationKey = () =>
  [{ url: "/api/v1/trips/:tripID/categories/:name/hide" }] as const;

export type HideCategoryMutationKey = ReturnType<
  typeof hideCategoryMutationKey
>;

/**
 * @description Hides a category from all members (admin only)
 * @summary Hide category
 * {@link /api/v1/trips/:tripID/categories/:name/hide}
 */
export async function hideCategory(
  tripID: HideCategoryPathParams["tripID"],
  name: HideCategoryPathParams["name"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    HideCategoryMutationResponse,
    ResponseErrorConfig<
      | HideCategory400
      | HideCategory401
      | HideCategory403
      | HideCategory404
      | HideCategory500
    >,
    unknown
  >({
    method: "PUT",
    url: `/api/v1/trips/${tripID}/categories/${name}/hide`,
    ...requestConfig,
  });
  return res.data;
}

export function hideCategoryMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = hideCategoryMutationKey();
  return mutationOptions<
    HideCategoryMutationResponse,
    ResponseErrorConfig<
      | HideCategory400
      | HideCategory401
      | HideCategory403
      | HideCategory404
      | HideCategory500
    >,
    {
      tripID: HideCategoryPathParams["tripID"];
      name: HideCategoryPathParams["name"];
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ tripID, name }) => {
      return hideCategory(tripID, name, config);
    },
  });
}

/**
 * @description Hides a category from all members (admin only)
 * @summary Hide category
 * {@link /api/v1/trips/:tripID/categories/:name/hide}
 */
export function useHideCategory<TContext>(
  options: {
    mutation?: UseMutationOptions<
      HideCategoryMutationResponse,
      ResponseErrorConfig<
        | HideCategory400
        | HideCategory401
        | HideCategory403
        | HideCategory404
        | HideCategory500
      >,
      {
        tripID: HideCategoryPathParams["tripID"];
        name: HideCategoryPathParams["name"];
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? hideCategoryMutationKey();

  const baseOptions = hideCategoryMutationOptions(config) as UseMutationOptions<
    HideCategoryMutationResponse,
    ResponseErrorConfig<
      | HideCategory400
      | HideCategory401
      | HideCategory403
      | HideCategory404
      | HideCategory500
    >,
    {
      tripID: HideCategoryPathParams["tripID"];
      name: HideCategoryPathParams["name"];
    },
    TContext
  >;

  return useMutation<
    HideCategoryMutationResponse,
    ResponseErrorConfig<
      | HideCategory400
      | HideCategory401
      | HideCategory403
      | HideCategory404
      | HideCategory500
    >,
    {
      tripID: HideCategoryPathParams["tripID"];
      name: HideCategoryPathParams["name"];
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    HideCategoryMutationResponse,
    ResponseErrorConfig<
      | HideCategory400
      | HideCategory401
      | HideCategory403
      | HideCategory404
      | HideCategory500
    >,
    {
      tripID: HideCategoryPathParams["tripID"];
      name: HideCategoryPathParams["name"];
    },
    TContext
  >;
}
