/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  ShowCategoryMutationResponse,
  ShowCategoryPathParams,
  ShowCategory400,
  ShowCategory401,
  ShowCategory403,
  ShowCategory404,
  ShowCategory500,
} from "../../types/types.gen.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const showCategoryMutationKey = () =>
  [{ url: "/api/v1/trips/:tripID/categories/:name/show" }] as const;

export type ShowCategoryMutationKey = ReturnType<
  typeof showCategoryMutationKey
>;

/**
 * @description Makes a previously hidden category visible again (admin only)
 * @summary Show category
 * {@link /api/v1/trips/:tripID/categories/:name/show}
 */
export async function showCategory(
  tripID: ShowCategoryPathParams["tripID"],
  name: ShowCategoryPathParams["name"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ShowCategoryMutationResponse,
    ResponseErrorConfig<
      | ShowCategory400
      | ShowCategory401
      | ShowCategory403
      | ShowCategory404
      | ShowCategory500
    >,
    unknown
  >({
    method: "PUT",
    url: `/api/v1/trips/${tripID}/categories/${name}/show`,
    ...requestConfig,
  });
  return res.data;
}

export function showCategoryMutationOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const mutationKey = showCategoryMutationKey();
  return mutationOptions<
    ShowCategoryMutationResponse,
    ResponseErrorConfig<
      | ShowCategory400
      | ShowCategory401
      | ShowCategory403
      | ShowCategory404
      | ShowCategory500
    >,
    {
      tripID: ShowCategoryPathParams["tripID"];
      name: ShowCategoryPathParams["name"];
    },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ tripID, name }) => {
      return showCategory(tripID, name, config);
    },
  });
}

/**
 * @description Makes a previously hidden category visible again (admin only)
 * @summary Show category
 * {@link /api/v1/trips/:tripID/categories/:name/show}
 */
export function useShowCategory<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ShowCategoryMutationResponse,
      ResponseErrorConfig<
        | ShowCategory400
        | ShowCategory401
        | ShowCategory403
        | ShowCategory404
        | ShowCategory500
      >,
      {
        tripID: ShowCategoryPathParams["tripID"];
        name: ShowCategoryPathParams["name"];
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? showCategoryMutationKey();

  const baseOptions = showCategoryMutationOptions(config) as UseMutationOptions<
    ShowCategoryMutationResponse,
    ResponseErrorConfig<
      | ShowCategory400
      | ShowCategory401
      | ShowCategory403
      | ShowCategory404
      | ShowCategory500
    >,
    {
      tripID: ShowCategoryPathParams["tripID"];
      name: ShowCategoryPathParams["name"];
    },
    TContext
  >;

  return useMutation<
    ShowCategoryMutationResponse,
    ResponseErrorConfig<
      | ShowCategory400
      | ShowCategory401
      | ShowCategory403
      | ShowCategory404
      | ShowCategory500
    >,
    {
      tripID: ShowCategoryPathParams["tripID"];
      name: ShowCategoryPathParams["name"];
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    ShowCategoryMutationResponse,
    ResponseErrorConfig<
      | ShowCategory400
      | ShowCategory401
      | ShowCategory403
      | ShowCategory404
      | ShowCategory500
    >,
    {
      tripID: ShowCategoryPathParams["tripID"];
      name: ShowCategoryPathParams["name"];
    },
    TContext
  >;
}
