/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  AddPollOptionMutationRequest,
  AddPollOptionMutationResponse,
  AddPollOptionPathParams,
  AddPollOption400,
  AddPollOption401,
  AddPollOption403,
  AddPollOption404,
  AddPollOption409,
  AddPollOption422,
  AddPollOption500,
} from "../../types/types.gen.ts";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const addPollOptionMutationKey = () =>
  [{ url: "/api/v1/trips/:tripID/vote-polls/:pollId/options" }] as const;

export type AddPollOptionMutationKey = ReturnType<
  typeof addPollOptionMutationKey
>;

/**
 * @description Adds an option to a poll (only if no votes exist yet)
 * @summary Add a poll option
 * {@link /api/v1/trips/:tripID/vote-polls/:pollId/options}
 */
export async function addPollOption(
  tripID: AddPollOptionPathParams["tripID"],
  pollId: AddPollOptionPathParams["pollId"],
  data: AddPollOptionMutationRequest,
  config: Partial<RequestConfig<AddPollOptionMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    AddPollOptionMutationResponse,
    ResponseErrorConfig<
      | AddPollOption400
      | AddPollOption401
      | AddPollOption403
      | AddPollOption404
      | AddPollOption409
      | AddPollOption422
      | AddPollOption500
    >,
    AddPollOptionMutationRequest
  >({
    method: "POST",
    url: `/api/v1/trips/${tripID}/vote-polls/${pollId}/options`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function addPollOptionMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<AddPollOptionMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = addPollOptionMutationKey();
  return mutationOptions<
    AddPollOptionMutationResponse,
    ResponseErrorConfig<
      | AddPollOption400
      | AddPollOption401
      | AddPollOption403
      | AddPollOption404
      | AddPollOption409
      | AddPollOption422
      | AddPollOption500
    >,
    {
      tripID: AddPollOptionPathParams["tripID"];
      pollId: AddPollOptionPathParams["pollId"];
      data: AddPollOptionMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ tripID, pollId, data }) => {
      return addPollOption(tripID, pollId, data, config);
    },
  });
}

/**
 * @description Adds an option to a poll (only if no votes exist yet)
 * @summary Add a poll option
 * {@link /api/v1/trips/:tripID/vote-polls/:pollId/options}
 */
export function useAddPollOption<TContext>(
  options: {
    mutation?: UseMutationOptions<
      AddPollOptionMutationResponse,
      ResponseErrorConfig<
        | AddPollOption400
        | AddPollOption401
        | AddPollOption403
        | AddPollOption404
        | AddPollOption409
        | AddPollOption422
        | AddPollOption500
      >,
      {
        tripID: AddPollOptionPathParams["tripID"];
        pollId: AddPollOptionPathParams["pollId"];
        data: AddPollOptionMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<AddPollOptionMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? addPollOptionMutationKey();

  const baseOptions = addPollOptionMutationOptions(
    config,
  ) as UseMutationOptions<
    AddPollOptionMutationResponse,
    ResponseErrorConfig<
      | AddPollOption400
      | AddPollOption401
      | AddPollOption403
      | AddPollOption404
      | AddPollOption409
      | AddPollOption422
      | AddPollOption500
    >,
    {
      tripID: AddPollOptionPathParams["tripID"];
      pollId: AddPollOptionPathParams["pollId"];
      data: AddPollOptionMutationRequest;
    },
    TContext
  >;

  return useMutation<
    AddPollOptionMutationResponse,
    ResponseErrorConfig<
      | AddPollOption400
      | AddPollOption401
      | AddPollOption403
      | AddPollOption404
      | AddPollOption409
      | AddPollOption422
      | AddPollOption500
    >,
    {
      tripID: AddPollOptionPathParams["tripID"];
      pollId: AddPollOptionPathParams["pollId"];
      data: AddPollOptionMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    AddPollOptionMutationResponse,
    ResponseErrorConfig<
      | AddPollOption400
      | AddPollOption401
      | AddPollOption403
      | AddPollOption404
      | AddPollOption409
      | AddPollOption422
      | AddPollOption500
    >,
    {
      tripID: AddPollOptionPathParams["tripID"];
      pollId: AddPollOptionPathParams["pollId"];
      data: AddPollOptionMutationRequest;
    },
    TContext
  >;
}
