/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  CreatePollMutationRequest,
  CreatePollMutationResponse,
  CreatePollPathParams,
  CreatePoll400,
  CreatePoll401,
  CreatePoll403,
  CreatePoll422,
  CreatePoll500,
} from "../../types/types.gen.ts";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const createPollMutationKey = () =>
  [{ url: "/api/v1/trips/:tripID/vote-polls" }] as const;

export type CreatePollMutationKey = ReturnType<typeof createPollMutationKey>;

/**
 * @description Creates a new poll with initial options
 * @summary Create a poll
 * {@link /api/v1/trips/:tripID/vote-polls}
 */
export async function createPoll(
  tripID: CreatePollPathParams["tripID"],
  data: CreatePollMutationRequest,
  config: Partial<RequestConfig<CreatePollMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    CreatePollMutationResponse,
    ResponseErrorConfig<
      | CreatePoll400
      | CreatePoll401
      | CreatePoll403
      | CreatePoll422
      | CreatePoll500
    >,
    CreatePollMutationRequest
  >({
    method: "POST",
    url: `/api/v1/trips/${tripID}/vote-polls`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function createPollMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<CreatePollMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = createPollMutationKey();
  return mutationOptions<
    CreatePollMutationResponse,
    ResponseErrorConfig<
      | CreatePoll400
      | CreatePoll401
      | CreatePoll403
      | CreatePoll422
      | CreatePoll500
    >,
    { tripID: CreatePollPathParams["tripID"]; data: CreatePollMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ tripID, data }) => {
      return createPoll(tripID, data, config);
    },
  });
}

/**
 * @description Creates a new poll with initial options
 * @summary Create a poll
 * {@link /api/v1/trips/:tripID/vote-polls}
 */
export function useCreatePoll<TContext>(
  options: {
    mutation?: UseMutationOptions<
      CreatePollMutationResponse,
      ResponseErrorConfig<
        | CreatePoll400
        | CreatePoll401
        | CreatePoll403
        | CreatePoll422
        | CreatePoll500
      >,
      {
        tripID: CreatePollPathParams["tripID"];
        data: CreatePollMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<CreatePollMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? createPollMutationKey();

  const baseOptions = createPollMutationOptions(config) as UseMutationOptions<
    CreatePollMutationResponse,
    ResponseErrorConfig<
      | CreatePoll400
      | CreatePoll401
      | CreatePoll403
      | CreatePoll422
      | CreatePoll500
    >,
    { tripID: CreatePollPathParams["tripID"]; data: CreatePollMutationRequest },
    TContext
  >;

  return useMutation<
    CreatePollMutationResponse,
    ResponseErrorConfig<
      | CreatePoll400
      | CreatePoll401
      | CreatePoll403
      | CreatePoll422
      | CreatePoll500
    >,
    { tripID: CreatePollPathParams["tripID"]; data: CreatePollMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    CreatePollMutationResponse,
    ResponseErrorConfig<
      | CreatePoll400
      | CreatePoll401
      | CreatePoll403
      | CreatePoll422
      | CreatePoll500
    >,
    { tripID: CreatePollPathParams["tripID"]; data: CreatePollMutationRequest },
    TContext
  >;
}
