/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  DeleteRankPollOptionMutationResponse,
  DeleteRankPollOptionPathParams,
  DeleteRankPollOption400,
  DeleteRankPollOption401,
  DeleteRankPollOption403,
  DeleteRankPollOption404,
  DeleteRankPollOption409,
  DeleteRankPollOption500,
} from "../../types/types.gen.ts";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteRankPollOptionMutationKey = () =>
  [
    { url: "/api/v1/trips/:tripID/rank-polls/:pollId/options/:optionId" },
  ] as const;

export type DeleteRankPollOptionMutationKey = ReturnType<
  typeof deleteRankPollOptionMutationKey
>;

/**
 * @description Removes an option from a rank poll (only if no rankings exist yet)
 * @summary Delete a rank poll option
 * {@link /api/v1/trips/:tripID/rank-polls/:pollId/options/:optionId}
 */
export async function deleteRankPollOption(
  tripID: DeleteRankPollOptionPathParams["tripID"],
  pollId: DeleteRankPollOptionPathParams["pollId"],
  optionId: DeleteRankPollOptionPathParams["optionId"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeleteRankPollOptionMutationResponse,
    ResponseErrorConfig<
      | DeleteRankPollOption400
      | DeleteRankPollOption401
      | DeleteRankPollOption403
      | DeleteRankPollOption404
      | DeleteRankPollOption409
      | DeleteRankPollOption500
    >,
    unknown
  >({
    method: "DELETE",
    url: `/api/v1/trips/${tripID}/rank-polls/${pollId}/options/${optionId}`,
    ...requestConfig,
  });
  return res.data;
}

export function deleteRankPollOptionMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = deleteRankPollOptionMutationKey();
  return mutationOptions<
    DeleteRankPollOptionMutationResponse,
    ResponseErrorConfig<
      | DeleteRankPollOption400
      | DeleteRankPollOption401
      | DeleteRankPollOption403
      | DeleteRankPollOption404
      | DeleteRankPollOption409
      | DeleteRankPollOption500
    >,
    {
      tripID: DeleteRankPollOptionPathParams["tripID"];
      pollId: DeleteRankPollOptionPathParams["pollId"];
      optionId: DeleteRankPollOptionPathParams["optionId"];
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ tripID, pollId, optionId }) => {
      return deleteRankPollOption(tripID, pollId, optionId, config);
    },
  });
}

/**
 * @description Removes an option from a rank poll (only if no rankings exist yet)
 * @summary Delete a rank poll option
 * {@link /api/v1/trips/:tripID/rank-polls/:pollId/options/:optionId}
 */
export function useDeleteRankPollOption<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteRankPollOptionMutationResponse,
      ResponseErrorConfig<
        | DeleteRankPollOption400
        | DeleteRankPollOption401
        | DeleteRankPollOption403
        | DeleteRankPollOption404
        | DeleteRankPollOption409
        | DeleteRankPollOption500
      >,
      {
        tripID: DeleteRankPollOptionPathParams["tripID"];
        pollId: DeleteRankPollOptionPathParams["pollId"];
        optionId: DeleteRankPollOptionPathParams["optionId"];
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? deleteRankPollOptionMutationKey();

  const baseOptions = deleteRankPollOptionMutationOptions(
    config,
  ) as UseMutationOptions<
    DeleteRankPollOptionMutationResponse,
    ResponseErrorConfig<
      | DeleteRankPollOption400
      | DeleteRankPollOption401
      | DeleteRankPollOption403
      | DeleteRankPollOption404
      | DeleteRankPollOption409
      | DeleteRankPollOption500
    >,
    {
      tripID: DeleteRankPollOptionPathParams["tripID"];
      pollId: DeleteRankPollOptionPathParams["pollId"];
      optionId: DeleteRankPollOptionPathParams["optionId"];
    },
    TContext
  >;

  return useMutation<
    DeleteRankPollOptionMutationResponse,
    ResponseErrorConfig<
      | DeleteRankPollOption400
      | DeleteRankPollOption401
      | DeleteRankPollOption403
      | DeleteRankPollOption404
      | DeleteRankPollOption409
      | DeleteRankPollOption500
    >,
    {
      tripID: DeleteRankPollOptionPathParams["tripID"];
      pollId: DeleteRankPollOptionPathParams["pollId"];
      optionId: DeleteRankPollOptionPathParams["optionId"];
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteRankPollOptionMutationResponse,
    ResponseErrorConfig<
      | DeleteRankPollOption400
      | DeleteRankPollOption401
      | DeleteRankPollOption403
      | DeleteRankPollOption404
      | DeleteRankPollOption409
      | DeleteRankPollOption500
    >,
    {
      tripID: DeleteRankPollOptionPathParams["tripID"];
      pollId: DeleteRankPollOptionPathParams["pollId"];
      optionId: DeleteRankPollOptionPathParams["optionId"];
    },
    TContext
  >;
}
