/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  DeletePollOptionMutationResponse,
  DeletePollOptionPathParams,
  DeletePollOption400,
  DeletePollOption401,
  DeletePollOption403,
  DeletePollOption404,
  DeletePollOption409,
  DeletePollOption500,
} from "../../types/types.gen.ts";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deletePollOptionMutationKey = () =>
  [
    { url: "/api/v1/trips/:tripID/vote-polls/:pollId/options/:optionId" },
  ] as const;

export type DeletePollOptionMutationKey = ReturnType<
  typeof deletePollOptionMutationKey
>;

/**
 * @description Removes an option from a poll and returns the deleted option
 * @summary Delete a poll option
 * {@link /api/v1/trips/:tripID/vote-polls/:pollId/options/:optionId}
 */
export async function deletePollOption(
  tripID: DeletePollOptionPathParams["tripID"],
  pollId: DeletePollOptionPathParams["pollId"],
  optionId: DeletePollOptionPathParams["optionId"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeletePollOptionMutationResponse,
    ResponseErrorConfig<
      | DeletePollOption400
      | DeletePollOption401
      | DeletePollOption403
      | DeletePollOption404
      | DeletePollOption409
      | DeletePollOption500
    >,
    unknown
  >({
    method: "DELETE",
    url: `/api/v1/trips/${tripID}/vote-polls/${pollId}/options/${optionId}`,
    ...requestConfig,
  });
  return res.data;
}

export function deletePollOptionMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = deletePollOptionMutationKey();
  return mutationOptions<
    DeletePollOptionMutationResponse,
    ResponseErrorConfig<
      | DeletePollOption400
      | DeletePollOption401
      | DeletePollOption403
      | DeletePollOption404
      | DeletePollOption409
      | DeletePollOption500
    >,
    {
      tripID: DeletePollOptionPathParams["tripID"];
      pollId: DeletePollOptionPathParams["pollId"];
      optionId: DeletePollOptionPathParams["optionId"];
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ tripID, pollId, optionId }) => {
      return deletePollOption(tripID, pollId, optionId, config);
    },
  });
}

/**
 * @description Removes an option from a poll and returns the deleted option
 * @summary Delete a poll option
 * {@link /api/v1/trips/:tripID/vote-polls/:pollId/options/:optionId}
 */
export function useDeletePollOption<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeletePollOptionMutationResponse,
      ResponseErrorConfig<
        | DeletePollOption400
        | DeletePollOption401
        | DeletePollOption403
        | DeletePollOption404
        | DeletePollOption409
        | DeletePollOption500
      >,
      {
        tripID: DeletePollOptionPathParams["tripID"];
        pollId: DeletePollOptionPathParams["pollId"];
        optionId: DeletePollOptionPathParams["optionId"];
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? deletePollOptionMutationKey();

  const baseOptions = deletePollOptionMutationOptions(
    config,
  ) as UseMutationOptions<
    DeletePollOptionMutationResponse,
    ResponseErrorConfig<
      | DeletePollOption400
      | DeletePollOption401
      | DeletePollOption403
      | DeletePollOption404
      | DeletePollOption409
      | DeletePollOption500
    >,
    {
      tripID: DeletePollOptionPathParams["tripID"];
      pollId: DeletePollOptionPathParams["pollId"];
      optionId: DeletePollOptionPathParams["optionId"];
    },
    TContext
  >;

  return useMutation<
    DeletePollOptionMutationResponse,
    ResponseErrorConfig<
      | DeletePollOption400
      | DeletePollOption401
      | DeletePollOption403
      | DeletePollOption404
      | DeletePollOption409
      | DeletePollOption500
    >,
    {
      tripID: DeletePollOptionPathParams["tripID"];
      pollId: DeletePollOptionPathParams["pollId"];
      optionId: DeletePollOptionPathParams["optionId"];
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeletePollOptionMutationResponse,
    ResponseErrorConfig<
      | DeletePollOption400
      | DeletePollOption401
      | DeletePollOption403
      | DeletePollOption404
      | DeletePollOption409
      | DeletePollOption500
    >,
    {
      tripID: DeletePollOptionPathParams["tripID"];
      pollId: DeletePollOptionPathParams["pollId"];
      optionId: DeletePollOptionPathParams["optionId"];
    },
    TContext
  >;
}
