/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  GetRankChoiceVotersQueryResponse,
  GetRankChoiceVotersPathParams,
  GetRankChoiceVoters400,
  GetRankChoiceVoters401,
  GetRankChoiceVoters403,
  GetRankChoiceVoters404,
  GetRankChoiceVoters500,
} from "../../types/types.gen.ts";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getRankChoiceVotersSuspenseQueryKey = (
  tripID: GetRankChoiceVotersPathParams["tripID"],
  pollId: GetRankChoiceVotersPathParams["pollId"],
  optionId: GetRankChoiceVotersPathParams["optionId"],
  rankPosition: GetRankChoiceVotersPathParams["rankPosition"],
) =>
  [
    {
      url: "/api/v1/trips/:tripID/rank-polls/:pollId/options/:optionId/ranks/:rankPosition/voters",
      params: {
        tripID: tripID,
        pollId: pollId,
        optionId: optionId,
        rankPosition: rankPosition,
      },
    },
  ] as const;

export type GetRankChoiceVotersSuspenseQueryKey = ReturnType<
  typeof getRankChoiceVotersSuspenseQueryKey
>;

/**
 * @description Returns who ranked an option at a specific rank position
 * @summary Get voters for a ranked choice
 * {@link /api/v1/trips/:tripID/rank-polls/:pollId/options/:optionId/ranks/:rankPosition/voters}
 */
export async function getRankChoiceVotersSuspense(
  tripID: GetRankChoiceVotersPathParams["tripID"],
  pollId: GetRankChoiceVotersPathParams["pollId"],
  optionId: GetRankChoiceVotersPathParams["optionId"],
  rankPosition: GetRankChoiceVotersPathParams["rankPosition"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetRankChoiceVotersQueryResponse,
    ResponseErrorConfig<
      | GetRankChoiceVoters400
      | GetRankChoiceVoters401
      | GetRankChoiceVoters403
      | GetRankChoiceVoters404
      | GetRankChoiceVoters500
    >,
    unknown
  >({
    method: "GET",
    url: `/api/v1/trips/${tripID}/rank-polls/${pollId}/options/${optionId}/ranks/${rankPosition}/voters`,
    ...requestConfig,
  });
  return res.data;
}

export function getRankChoiceVotersSuspenseQueryOptions(
  tripID: GetRankChoiceVotersPathParams["tripID"],
  pollId: GetRankChoiceVotersPathParams["pollId"],
  optionId: GetRankChoiceVotersPathParams["optionId"],
  rankPosition: GetRankChoiceVotersPathParams["rankPosition"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getRankChoiceVotersSuspenseQueryKey(
    tripID,
    pollId,
    optionId,
    rankPosition,
  );
  return queryOptions<
    GetRankChoiceVotersQueryResponse,
    ResponseErrorConfig<
      | GetRankChoiceVoters400
      | GetRankChoiceVoters401
      | GetRankChoiceVoters403
      | GetRankChoiceVoters404
      | GetRankChoiceVoters500
    >,
    GetRankChoiceVotersQueryResponse,
    typeof queryKey
  >({
    enabled: !!(tripID && pollId && optionId && rankPosition),
    queryKey,
    queryFn: async ({ signal }) => {
      if (!config.signal) {
        config.signal = signal;
      }
      return getRankChoiceVotersSuspense(
        tripID,
        pollId,
        optionId,
        rankPosition,
        config,
      );
    },
  });
}

/**
 * @description Returns who ranked an option at a specific rank position
 * @summary Get voters for a ranked choice
 * {@link /api/v1/trips/:tripID/rank-polls/:pollId/options/:optionId/ranks/:rankPosition/voters}
 */
export function useGetRankChoiceVotersSuspense<
  TData = GetRankChoiceVotersQueryResponse,
  TQueryKey extends QueryKey = GetRankChoiceVotersSuspenseQueryKey,
>(
  tripID: GetRankChoiceVotersPathParams["tripID"],
  pollId: GetRankChoiceVotersPathParams["pollId"],
  optionId: GetRankChoiceVotersPathParams["optionId"],
  rankPosition: GetRankChoiceVotersPathParams["rankPosition"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetRankChoiceVotersQueryResponse,
        ResponseErrorConfig<
          | GetRankChoiceVoters400
          | GetRankChoiceVoters401
          | GetRankChoiceVoters403
          | GetRankChoiceVoters404
          | GetRankChoiceVoters500
        >,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ??
    getRankChoiceVotersSuspenseQueryKey(tripID, pollId, optionId, rankPosition);

  const query = useSuspenseQuery(
    {
      ...getRankChoiceVotersSuspenseQueryOptions(
        tripID,
        pollId,
        optionId,
        rankPosition,
        config,
      ),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetRankChoiceVoters400
      | GetRankChoiceVoters401
      | GetRankChoiceVoters403
      | GetRankChoiceVoters404
      | GetRankChoiceVoters500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
