/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  GetPollsByTripIDQueryResponse,
  GetPollsByTripIDPathParams,
  GetPollsByTripIDQueryParams,
  GetPollsByTripID400,
  GetPollsByTripID401,
  GetPollsByTripID403,
  GetPollsByTripID500,
} from "../../types/types.gen.ts";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getPollsByTripIDSuspenseQueryKey = (
  tripID: GetPollsByTripIDPathParams["tripID"],
  params: GetPollsByTripIDQueryParams = {},
) =>
  [
    { url: "/api/v1/trips/:tripID/vote-polls", params: { tripID: tripID } },
    ...(params ? [params] : []),
  ] as const;

export type GetPollsByTripIDSuspenseQueryKey = ReturnType<
  typeof getPollsByTripIDSuspenseQueryKey
>;

/**
 * @description Retrieves all polls for a trip with cursor-based pagination
 * @summary Get polls for a trip
 * {@link /api/v1/trips/:tripID/vote-polls}
 */
export async function getPollsByTripIDSuspense(
  tripID: GetPollsByTripIDPathParams["tripID"],
  params?: GetPollsByTripIDQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetPollsByTripIDQueryResponse,
    ResponseErrorConfig<
      | GetPollsByTripID400
      | GetPollsByTripID401
      | GetPollsByTripID403
      | GetPollsByTripID500
    >,
    unknown
  >({
    method: "GET",
    url: `/api/v1/trips/${tripID}/vote-polls`,
    params,
    ...requestConfig,
  });
  return res.data;
}

export function getPollsByTripIDSuspenseQueryOptions(
  tripID: GetPollsByTripIDPathParams["tripID"],
  params?: GetPollsByTripIDQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getPollsByTripIDSuspenseQueryKey(tripID, params);
  return queryOptions<
    GetPollsByTripIDQueryResponse,
    ResponseErrorConfig<
      | GetPollsByTripID400
      | GetPollsByTripID401
      | GetPollsByTripID403
      | GetPollsByTripID500
    >,
    GetPollsByTripIDQueryResponse,
    typeof queryKey
  >({
    enabled: !!tripID,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getPollsByTripIDSuspense(tripID, params, config);
    },
  });
}

/**
 * @description Retrieves all polls for a trip with cursor-based pagination
 * @summary Get polls for a trip
 * {@link /api/v1/trips/:tripID/vote-polls}
 */
export function useGetPollsByTripIDSuspense<
  TData = GetPollsByTripIDQueryResponse,
  TQueryKey extends QueryKey = GetPollsByTripIDSuspenseQueryKey,
>(
  tripID: GetPollsByTripIDPathParams["tripID"],
  params?: GetPollsByTripIDQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetPollsByTripIDQueryResponse,
        ResponseErrorConfig<
          | GetPollsByTripID400
          | GetPollsByTripID401
          | GetPollsByTripID403
          | GetPollsByTripID500
        >,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getPollsByTripIDSuspenseQueryKey(tripID, params);

  const query = useSuspenseQuery(
    {
      ...getPollsByTripIDSuspenseQueryOptions(tripID, params, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetPollsByTripID400
      | GetPollsByTripID401
      | GetPollsByTripID403
      | GetPollsByTripID500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
