/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  GetVoteOptionVotersQueryResponse,
  GetVoteOptionVotersPathParams,
  GetVoteOptionVoters400,
  GetVoteOptionVoters401,
  GetVoteOptionVoters403,
  GetVoteOptionVoters404,
  GetVoteOptionVoters500,
} from "../../types/types.gen.ts";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getVoteOptionVotersQueryKey = (
  tripID: GetVoteOptionVotersPathParams["tripID"],
  pollId: GetVoteOptionVotersPathParams["pollId"],
  optionId: GetVoteOptionVotersPathParams["optionId"],
) =>
  [
    {
      url: "/api/v1/trips/:tripID/vote-polls/:pollId/options/:optionId/voters",
      params: { tripID: tripID, pollId: pollId, optionId: optionId },
    },
  ] as const;

export type GetVoteOptionVotersQueryKey = ReturnType<
  typeof getVoteOptionVotersQueryKey
>;

/**
 * @description Returns all users who voted for a specific option in a vote poll
 * @summary Get option voters
 * {@link /api/v1/trips/:tripID/vote-polls/:pollId/options/:optionId/voters}
 */
export async function getVoteOptionVoters(
  tripID: GetVoteOptionVotersPathParams["tripID"],
  pollId: GetVoteOptionVotersPathParams["pollId"],
  optionId: GetVoteOptionVotersPathParams["optionId"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetVoteOptionVotersQueryResponse,
    ResponseErrorConfig<
      | GetVoteOptionVoters400
      | GetVoteOptionVoters401
      | GetVoteOptionVoters403
      | GetVoteOptionVoters404
      | GetVoteOptionVoters500
    >,
    unknown
  >({
    method: "GET",
    url: `/api/v1/trips/${tripID}/vote-polls/${pollId}/options/${optionId}/voters`,
    ...requestConfig,
  });
  return res.data;
}

export function getVoteOptionVotersQueryOptions(
  tripID: GetVoteOptionVotersPathParams["tripID"],
  pollId: GetVoteOptionVotersPathParams["pollId"],
  optionId: GetVoteOptionVotersPathParams["optionId"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getVoteOptionVotersQueryKey(tripID, pollId, optionId);
  return queryOptions<
    GetVoteOptionVotersQueryResponse,
    ResponseErrorConfig<
      | GetVoteOptionVoters400
      | GetVoteOptionVoters401
      | GetVoteOptionVoters403
      | GetVoteOptionVoters404
      | GetVoteOptionVoters500
    >,
    GetVoteOptionVotersQueryResponse,
    typeof queryKey
  >({
    enabled: !!(tripID && pollId && optionId),
    queryKey,
    queryFn: async ({ signal }) => {
      if (!config.signal) {
        config.signal = signal;
      }
      return getVoteOptionVoters(tripID, pollId, optionId, config);
    },
  });
}

/**
 * @description Returns all users who voted for a specific option in a vote poll
 * @summary Get option voters
 * {@link /api/v1/trips/:tripID/vote-polls/:pollId/options/:optionId/voters}
 */
export function useGetVoteOptionVoters<
  TData = GetVoteOptionVotersQueryResponse,
  TQueryData = GetVoteOptionVotersQueryResponse,
  TQueryKey extends QueryKey = GetVoteOptionVotersQueryKey,
>(
  tripID: GetVoteOptionVotersPathParams["tripID"],
  pollId: GetVoteOptionVotersPathParams["pollId"],
  optionId: GetVoteOptionVotersPathParams["optionId"],
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetVoteOptionVotersQueryResponse,
        ResponseErrorConfig<
          | GetVoteOptionVoters400
          | GetVoteOptionVoters401
          | GetVoteOptionVoters403
          | GetVoteOptionVoters404
          | GetVoteOptionVoters500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ??
    getVoteOptionVotersQueryKey(tripID, pollId, optionId);

  const query = useQuery(
    {
      ...getVoteOptionVotersQueryOptions(tripID, pollId, optionId, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetVoteOptionVoters400
      | GetVoteOptionVoters401
      | GetVoteOptionVoters403
      | GetVoteOptionVoters404
      | GetVoteOptionVoters500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
