/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  GetVotePollVotersQueryResponse,
  GetVotePollVotersPathParams,
  GetVotePollVoters400,
  GetVotePollVoters401,
  GetVotePollVoters403,
  GetVotePollVoters404,
  GetVotePollVoters500,
} from "../../types/types.gen.ts";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getVotePollVotersSuspenseQueryKey = (
  tripID: GetVotePollVotersPathParams["tripID"],
  pollId: GetVotePollVotersPathParams["pollId"],
) =>
  [
    {
      url: "/api/v1/trips/:tripID/vote-polls/:pollId/voters",
      params: { tripID: tripID, pollId: pollId },
    },
  ] as const;

export type GetVotePollVotersSuspenseQueryKey = ReturnType<
  typeof getVotePollVotersSuspenseQueryKey
>;

/**
 * @description Returns who has voted vs who hasn't for a vote poll
 * @summary Get vote poll voters
 * {@link /api/v1/trips/:tripID/vote-polls/:pollId/voters}
 */
export async function getVotePollVotersSuspense(
  tripID: GetVotePollVotersPathParams["tripID"],
  pollId: GetVotePollVotersPathParams["pollId"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetVotePollVotersQueryResponse,
    ResponseErrorConfig<
      | GetVotePollVoters400
      | GetVotePollVoters401
      | GetVotePollVoters403
      | GetVotePollVoters404
      | GetVotePollVoters500
    >,
    unknown
  >({
    method: "GET",
    url: `/api/v1/trips/${tripID}/vote-polls/${pollId}/voters`,
    ...requestConfig,
  });
  return res.data;
}

export function getVotePollVotersSuspenseQueryOptions(
  tripID: GetVotePollVotersPathParams["tripID"],
  pollId: GetVotePollVotersPathParams["pollId"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getVotePollVotersSuspenseQueryKey(tripID, pollId);
  return queryOptions<
    GetVotePollVotersQueryResponse,
    ResponseErrorConfig<
      | GetVotePollVoters400
      | GetVotePollVoters401
      | GetVotePollVoters403
      | GetVotePollVoters404
      | GetVotePollVoters500
    >,
    GetVotePollVotersQueryResponse,
    typeof queryKey
  >({
    enabled: !!(tripID && pollId),
    queryKey,
    queryFn: async ({ signal }) => {
      if (!config.signal) {
        config.signal = signal;
      }
      return getVotePollVotersSuspense(tripID, pollId, config);
    },
  });
}

/**
 * @description Returns who has voted vs who hasn't for a vote poll
 * @summary Get vote poll voters
 * {@link /api/v1/trips/:tripID/vote-polls/:pollId/voters}
 */
export function useGetVotePollVotersSuspense<
  TData = GetVotePollVotersQueryResponse,
  TQueryKey extends QueryKey = GetVotePollVotersSuspenseQueryKey,
>(
  tripID: GetVotePollVotersPathParams["tripID"],
  pollId: GetVotePollVotersPathParams["pollId"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetVotePollVotersQueryResponse,
        ResponseErrorConfig<
          | GetVotePollVoters400
          | GetVotePollVoters401
          | GetVotePollVoters403
          | GetVotePollVoters404
          | GetVotePollVoters500
        >,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getVotePollVotersSuspenseQueryKey(tripID, pollId);

  const query = useSuspenseQuery(
    {
      ...getVotePollVotersSuspenseQueryOptions(tripID, pollId, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetVotePollVoters400
      | GetVotePollVoters401
      | GetVotePollVoters403
      | GetVotePollVoters404
      | GetVotePollVoters500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
