/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  GetPollQueryResponse,
  GetPollPathParams,
  GetPoll400,
  GetPoll401,
  GetPoll403,
  GetPoll404,
  GetPoll500,
} from "../../types/types.gen.ts";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getPollQueryKey = (
  tripID: GetPollPathParams["tripID"],
  pollId: GetPollPathParams["pollId"],
) =>
  [
    {
      url: "/api/v1/trips/:tripID/vote-polls/:pollId",
      params: { tripID: tripID, pollId: pollId },
    },
  ] as const;

export type GetPollQueryKey = ReturnType<typeof getPollQueryKey>;

/**
 * @description Retrieves a poll with vote counts and the caller's votes
 * @summary Get poll results
 * {@link /api/v1/trips/:tripID/vote-polls/:pollId}
 */
export async function getPoll(
  tripID: GetPollPathParams["tripID"],
  pollId: GetPollPathParams["pollId"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetPollQueryResponse,
    ResponseErrorConfig<
      GetPoll400 | GetPoll401 | GetPoll403 | GetPoll404 | GetPoll500
    >,
    unknown
  >({
    method: "GET",
    url: `/api/v1/trips/${tripID}/vote-polls/${pollId}`,
    ...requestConfig,
  });
  return res.data;
}

export function getPollQueryOptions(
  tripID: GetPollPathParams["tripID"],
  pollId: GetPollPathParams["pollId"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getPollQueryKey(tripID, pollId);
  return queryOptions<
    GetPollQueryResponse,
    ResponseErrorConfig<
      GetPoll400 | GetPoll401 | GetPoll403 | GetPoll404 | GetPoll500
    >,
    GetPollQueryResponse,
    typeof queryKey
  >({
    enabled: !!(tripID && pollId),
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getPoll(tripID, pollId, config);
    },
  });
}

/**
 * @description Retrieves a poll with vote counts and the caller's votes
 * @summary Get poll results
 * {@link /api/v1/trips/:tripID/vote-polls/:pollId}
 */
export function useGetPoll<
  TData = GetPollQueryResponse,
  TQueryData = GetPollQueryResponse,
  TQueryKey extends QueryKey = GetPollQueryKey,
>(
  tripID: GetPollPathParams["tripID"],
  pollId: GetPollPathParams["pollId"],
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetPollQueryResponse,
        ResponseErrorConfig<
          GetPoll400 | GetPoll401 | GetPoll403 | GetPoll404 | GetPoll500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? getPollQueryKey(tripID, pollId);

  const query = useQuery(
    {
      ...getPollQueryOptions(tripID, pollId, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      GetPoll400 | GetPoll401 | GetPoll403 | GetPoll404 | GetPoll500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
