/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  SubmitRankingMutationRequest,
  SubmitRankingMutationResponse,
  SubmitRankingPathParams,
  SubmitRanking400,
  SubmitRanking401,
  SubmitRanking403,
  SubmitRanking404,
  SubmitRanking422,
  SubmitRanking500,
} from "../../types/types.gen.ts";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const submitRankingMutationKey = () =>
  [{ url: "/api/v1/trips/:tripID/rank-polls/:pollId/rank" }] as const;

export type SubmitRankingMutationKey = ReturnType<
  typeof submitRankingMutationKey
>;

/**
 * @description Submits or replaces the user's full ranking for a poll
 * @summary Submit ranking
 * {@link /api/v1/trips/:tripID/rank-polls/:pollId/rank}
 */
export async function submitRanking(
  tripID: SubmitRankingPathParams["tripID"],
  pollId: SubmitRankingPathParams["pollId"],
  data: SubmitRankingMutationRequest,
  config: Partial<RequestConfig<SubmitRankingMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    SubmitRankingMutationResponse,
    ResponseErrorConfig<
      | SubmitRanking400
      | SubmitRanking401
      | SubmitRanking403
      | SubmitRanking404
      | SubmitRanking422
      | SubmitRanking500
    >,
    SubmitRankingMutationRequest
  >({
    method: "POST",
    url: `/api/v1/trips/${tripID}/rank-polls/${pollId}/rank`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function submitRankingMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<SubmitRankingMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = submitRankingMutationKey();
  return mutationOptions<
    SubmitRankingMutationResponse,
    ResponseErrorConfig<
      | SubmitRanking400
      | SubmitRanking401
      | SubmitRanking403
      | SubmitRanking404
      | SubmitRanking422
      | SubmitRanking500
    >,
    {
      tripID: SubmitRankingPathParams["tripID"];
      pollId: SubmitRankingPathParams["pollId"];
      data: SubmitRankingMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ tripID, pollId, data }) => {
      return submitRanking(tripID, pollId, data, config);
    },
  });
}

/**
 * @description Submits or replaces the user's full ranking for a poll
 * @summary Submit ranking
 * {@link /api/v1/trips/:tripID/rank-polls/:pollId/rank}
 */
export function useSubmitRanking<TContext>(
  options: {
    mutation?: UseMutationOptions<
      SubmitRankingMutationResponse,
      ResponseErrorConfig<
        | SubmitRanking400
        | SubmitRanking401
        | SubmitRanking403
        | SubmitRanking404
        | SubmitRanking422
        | SubmitRanking500
      >,
      {
        tripID: SubmitRankingPathParams["tripID"];
        pollId: SubmitRankingPathParams["pollId"];
        data: SubmitRankingMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<SubmitRankingMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? submitRankingMutationKey();

  const baseOptions = submitRankingMutationOptions(
    config,
  ) as UseMutationOptions<
    SubmitRankingMutationResponse,
    ResponseErrorConfig<
      | SubmitRanking400
      | SubmitRanking401
      | SubmitRanking403
      | SubmitRanking404
      | SubmitRanking422
      | SubmitRanking500
    >,
    {
      tripID: SubmitRankingPathParams["tripID"];
      pollId: SubmitRankingPathParams["pollId"];
      data: SubmitRankingMutationRequest;
    },
    TContext
  >;

  return useMutation<
    SubmitRankingMutationResponse,
    ResponseErrorConfig<
      | SubmitRanking400
      | SubmitRanking401
      | SubmitRanking403
      | SubmitRanking404
      | SubmitRanking422
      | SubmitRanking500
    >,
    {
      tripID: SubmitRankingPathParams["tripID"];
      pollId: SubmitRankingPathParams["pollId"];
      data: SubmitRankingMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    SubmitRankingMutationResponse,
    ResponseErrorConfig<
      | SubmitRanking400
      | SubmitRanking401
      | SubmitRanking403
      | SubmitRanking404
      | SubmitRanking422
      | SubmitRanking500
    >,
    {
      tripID: SubmitRankingPathParams["tripID"];
      pollId: SubmitRankingPathParams["pollId"];
      data: SubmitRankingMutationRequest;
    },
    TContext
  >;
}
