/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  UpdatePollMutationRequest,
  UpdatePollMutationResponse,
  UpdatePollPathParams,
  UpdatePoll400,
  UpdatePoll401,
  UpdatePoll403,
  UpdatePoll404,
  UpdatePoll422,
  UpdatePoll500,
} from "../../types/types.gen.ts";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const updatePollMutationKey = () =>
  [{ url: "/api/v1/trips/:tripID/vote-polls/:pollId" }] as const;

export type UpdatePollMutationKey = ReturnType<typeof updatePollMutationKey>;

/**
 * @description Updates poll metadata (question, deadline)
 * @summary Update a poll
 * {@link /api/v1/trips/:tripID/vote-polls/:pollId}
 */
export async function updatePoll(
  tripID: UpdatePollPathParams["tripID"],
  pollId: UpdatePollPathParams["pollId"],
  data?: UpdatePollMutationRequest,
  config: Partial<RequestConfig<UpdatePollMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    UpdatePollMutationResponse,
    ResponseErrorConfig<
      | UpdatePoll400
      | UpdatePoll401
      | UpdatePoll403
      | UpdatePoll404
      | UpdatePoll422
      | UpdatePoll500
    >,
    UpdatePollMutationRequest
  >({
    method: "PATCH",
    url: `/api/v1/trips/${tripID}/vote-polls/${pollId}`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function updatePollMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<UpdatePollMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = updatePollMutationKey();
  return mutationOptions<
    UpdatePollMutationResponse,
    ResponseErrorConfig<
      | UpdatePoll400
      | UpdatePoll401
      | UpdatePoll403
      | UpdatePoll404
      | UpdatePoll422
      | UpdatePoll500
    >,
    {
      tripID: UpdatePollPathParams["tripID"];
      pollId: UpdatePollPathParams["pollId"];
      data?: UpdatePollMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ tripID, pollId, data }) => {
      return updatePoll(tripID, pollId, data, config);
    },
  });
}

/**
 * @description Updates poll metadata (question, deadline)
 * @summary Update a poll
 * {@link /api/v1/trips/:tripID/vote-polls/:pollId}
 */
export function useUpdatePoll<TContext>(
  options: {
    mutation?: UseMutationOptions<
      UpdatePollMutationResponse,
      ResponseErrorConfig<
        | UpdatePoll400
        | UpdatePoll401
        | UpdatePoll403
        | UpdatePoll404
        | UpdatePoll422
        | UpdatePoll500
      >,
      {
        tripID: UpdatePollPathParams["tripID"];
        pollId: UpdatePollPathParams["pollId"];
        data?: UpdatePollMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<UpdatePollMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? updatePollMutationKey();

  const baseOptions = updatePollMutationOptions(config) as UseMutationOptions<
    UpdatePollMutationResponse,
    ResponseErrorConfig<
      | UpdatePoll400
      | UpdatePoll401
      | UpdatePoll403
      | UpdatePoll404
      | UpdatePoll422
      | UpdatePoll500
    >,
    {
      tripID: UpdatePollPathParams["tripID"];
      pollId: UpdatePollPathParams["pollId"];
      data?: UpdatePollMutationRequest;
    },
    TContext
  >;

  return useMutation<
    UpdatePollMutationResponse,
    ResponseErrorConfig<
      | UpdatePoll400
      | UpdatePoll401
      | UpdatePoll403
      | UpdatePoll404
      | UpdatePoll422
      | UpdatePoll500
    >,
    {
      tripID: UpdatePollPathParams["tripID"];
      pollId: UpdatePollPathParams["pollId"];
      data?: UpdatePollMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    UpdatePollMutationResponse,
    ResponseErrorConfig<
      | UpdatePoll400
      | UpdatePoll401
      | UpdatePoll403
      | UpdatePoll404
      | UpdatePoll422
      | UpdatePoll500
    >,
    {
      tripID: UpdatePollPathParams["tripID"];
      pollId: UpdatePollPathParams["pollId"];
      data?: UpdatePollMutationRequest;
    },
    TContext
  >;
}
