/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  CreateNotificationPreferencesMutationRequest,
  CreateNotificationPreferencesMutationResponse,
  CreateNotificationPreferences400,
  CreateNotificationPreferences401,
  CreateNotificationPreferences409,
  CreateNotificationPreferences422,
  CreateNotificationPreferences500,
} from "../../types/types.gen.ts";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const createNotificationPreferencesMutationKey = () =>
  [{ url: "/api/v1/users/me/notification-preferences" }] as const;

export type CreateNotificationPreferencesMutationKey = ReturnType<
  typeof createNotificationPreferencesMutationKey
>;

/**
 * @description Creates notification preferences for the authenticated user
 * @summary Create notification preferences
 * {@link /api/v1/users/me/notification-preferences}
 */
export async function createNotificationPreferences(
  data: CreateNotificationPreferencesMutationRequest,
  config: Partial<
    RequestConfig<CreateNotificationPreferencesMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    CreateNotificationPreferencesMutationResponse,
    ResponseErrorConfig<
      | CreateNotificationPreferences400
      | CreateNotificationPreferences401
      | CreateNotificationPreferences409
      | CreateNotificationPreferences422
      | CreateNotificationPreferences500
    >,
    CreateNotificationPreferencesMutationRequest
  >({
    method: "POST",
    url: `/api/v1/users/me/notification-preferences`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function createNotificationPreferencesMutationOptions<
  TContext = unknown,
>(
  config: Partial<
    RequestConfig<CreateNotificationPreferencesMutationRequest>
  > & { client?: Client } = {},
) {
  const mutationKey = createNotificationPreferencesMutationKey();
  return mutationOptions<
    CreateNotificationPreferencesMutationResponse,
    ResponseErrorConfig<
      | CreateNotificationPreferences400
      | CreateNotificationPreferences401
      | CreateNotificationPreferences409
      | CreateNotificationPreferences422
      | CreateNotificationPreferences500
    >,
    { data: CreateNotificationPreferencesMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return createNotificationPreferences(data, config);
    },
  });
}

/**
 * @description Creates notification preferences for the authenticated user
 * @summary Create notification preferences
 * {@link /api/v1/users/me/notification-preferences}
 */
export function useCreateNotificationPreferences<TContext>(
  options: {
    mutation?: UseMutationOptions<
      CreateNotificationPreferencesMutationResponse,
      ResponseErrorConfig<
        | CreateNotificationPreferences400
        | CreateNotificationPreferences401
        | CreateNotificationPreferences409
        | CreateNotificationPreferences422
        | CreateNotificationPreferences500
      >,
      { data: CreateNotificationPreferencesMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<CreateNotificationPreferencesMutationRequest>
    > & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? createNotificationPreferencesMutationKey();

  const baseOptions = createNotificationPreferencesMutationOptions(
    config,
  ) as UseMutationOptions<
    CreateNotificationPreferencesMutationResponse,
    ResponseErrorConfig<
      | CreateNotificationPreferences400
      | CreateNotificationPreferences401
      | CreateNotificationPreferences409
      | CreateNotificationPreferences422
      | CreateNotificationPreferences500
    >,
    { data: CreateNotificationPreferencesMutationRequest },
    TContext
  >;

  return useMutation<
    CreateNotificationPreferencesMutationResponse,
    ResponseErrorConfig<
      | CreateNotificationPreferences400
      | CreateNotificationPreferences401
      | CreateNotificationPreferences409
      | CreateNotificationPreferences422
      | CreateNotificationPreferences500
    >,
    { data: CreateNotificationPreferencesMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    CreateNotificationPreferencesMutationResponse,
    ResponseErrorConfig<
      | CreateNotificationPreferences400
      | CreateNotificationPreferences401
      | CreateNotificationPreferences409
      | CreateNotificationPreferences422
      | CreateNotificationPreferences500
    >,
    { data: CreateNotificationPreferencesMutationRequest },
    TContext
  >;
}
