/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  DeleteNotificationPreferencesMutationResponse,
  DeleteNotificationPreferences401,
  DeleteNotificationPreferences500,
} from "../../types/types.gen.ts";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteNotificationPreferencesMutationKey = () =>
  [{ url: "/api/v1/users/me/notification-preferences" }] as const;

export type DeleteNotificationPreferencesMutationKey = ReturnType<
  typeof deleteNotificationPreferencesMutationKey
>;

/**
 * @description Deletes notification preferences for the authenticated user
 * @summary Delete notification preferences
 * {@link /api/v1/users/me/notification-preferences}
 */
export async function deleteNotificationPreferences(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeleteNotificationPreferencesMutationResponse,
    ResponseErrorConfig<
      DeleteNotificationPreferences401 | DeleteNotificationPreferences500
    >,
    unknown
  >({
    method: "DELETE",
    url: `/api/v1/users/me/notification-preferences`,
    ...requestConfig,
  });
  return res.data;
}

export function deleteNotificationPreferencesMutationOptions<
  TContext = unknown,
>(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const mutationKey = deleteNotificationPreferencesMutationKey();
  return mutationOptions<
    DeleteNotificationPreferencesMutationResponse,
    ResponseErrorConfig<
      DeleteNotificationPreferences401 | DeleteNotificationPreferences500
    >,
    void,
    TContext
  >({
    mutationKey,
    mutationFn: async () => {
      return deleteNotificationPreferences(config);
    },
  });
}

/**
 * @description Deletes notification preferences for the authenticated user
 * @summary Delete notification preferences
 * {@link /api/v1/users/me/notification-preferences}
 */
export function useDeleteNotificationPreferences<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteNotificationPreferencesMutationResponse,
      ResponseErrorConfig<
        DeleteNotificationPreferences401 | DeleteNotificationPreferences500
      >,
      void,
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? deleteNotificationPreferencesMutationKey();

  const baseOptions = deleteNotificationPreferencesMutationOptions(
    config,
  ) as UseMutationOptions<
    DeleteNotificationPreferencesMutationResponse,
    ResponseErrorConfig<
      DeleteNotificationPreferences401 | DeleteNotificationPreferences500
    >,
    void,
    TContext
  >;

  return useMutation<
    DeleteNotificationPreferencesMutationResponse,
    ResponseErrorConfig<
      DeleteNotificationPreferences401 | DeleteNotificationPreferences500
    >,
    void,
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteNotificationPreferencesMutationResponse,
    ResponseErrorConfig<
      DeleteNotificationPreferences401 | DeleteNotificationPreferences500
    >,
    void,
    TContext
  >;
}
