/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  GetNotificationPreferencesQueryResponse,
  GetNotificationPreferences401,
  GetNotificationPreferences404,
  GetNotificationPreferences500,
} from "../../types/types.gen.ts";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getNotificationPreferencesQueryKey = () =>
  [{ url: "/api/v1/users/me/notification-preferences" }] as const;

export type GetNotificationPreferencesQueryKey = ReturnType<
  typeof getNotificationPreferencesQueryKey
>;

/**
 * @description Retrieves the notification preferences for the authenticated user
 * @summary Get notification preferences
 * {@link /api/v1/users/me/notification-preferences}
 */
export async function getNotificationPreferences(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetNotificationPreferencesQueryResponse,
    ResponseErrorConfig<
      | GetNotificationPreferences401
      | GetNotificationPreferences404
      | GetNotificationPreferences500
    >,
    unknown
  >({
    method: "GET",
    url: `/api/v1/users/me/notification-preferences`,
    ...requestConfig,
  });
  return res.data;
}

export function getNotificationPreferencesQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getNotificationPreferencesQueryKey();
  return queryOptions<
    GetNotificationPreferencesQueryResponse,
    ResponseErrorConfig<
      | GetNotificationPreferences401
      | GetNotificationPreferences404
      | GetNotificationPreferences500
    >,
    GetNotificationPreferencesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      if (!config.signal) {
        config.signal = signal;
      }
      return getNotificationPreferences(config);
    },
  });
}

/**
 * @description Retrieves the notification preferences for the authenticated user
 * @summary Get notification preferences
 * {@link /api/v1/users/me/notification-preferences}
 */
export function useGetNotificationPreferences<
  TData = GetNotificationPreferencesQueryResponse,
  TQueryData = GetNotificationPreferencesQueryResponse,
  TQueryKey extends QueryKey = GetNotificationPreferencesQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetNotificationPreferencesQueryResponse,
        ResponseErrorConfig<
          | GetNotificationPreferences401
          | GetNotificationPreferences404
          | GetNotificationPreferences500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getNotificationPreferencesQueryKey();

  const query = useQuery(
    {
      ...getNotificationPreferencesQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetNotificationPreferences401
      | GetNotificationPreferences404
      | GetNotificationPreferences500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
