/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  GetOrCreateDefaultNotificationPreferencesMutationResponse,
  GetOrCreateDefaultNotificationPreferences401,
  GetOrCreateDefaultNotificationPreferences500,
} from "../../types/types.gen.ts";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const getOrCreateDefaultNotificationPreferencesMutationKey = () =>
  [{ url: "/api/v1/users/me/notification-preferences/default" }] as const;

export type GetOrCreateDefaultNotificationPreferencesMutationKey = ReturnType<
  typeof getOrCreateDefaultNotificationPreferencesMutationKey
>;

/**
 * @description Returns existing preferences or creates default preferences for the authenticated user
 * @summary Get or create default notification preferences
 * {@link /api/v1/users/me/notification-preferences/default}
 */
export async function getOrCreateDefaultNotificationPreferences(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetOrCreateDefaultNotificationPreferencesMutationResponse,
    ResponseErrorConfig<
      | GetOrCreateDefaultNotificationPreferences401
      | GetOrCreateDefaultNotificationPreferences500
    >,
    unknown
  >({
    method: "POST",
    url: `/api/v1/users/me/notification-preferences/default`,
    ...requestConfig,
  });
  return res.data;
}

export function getOrCreateDefaultNotificationPreferencesMutationOptions<
  TContext = unknown,
>(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const mutationKey = getOrCreateDefaultNotificationPreferencesMutationKey();
  return mutationOptions<
    GetOrCreateDefaultNotificationPreferencesMutationResponse,
    ResponseErrorConfig<
      | GetOrCreateDefaultNotificationPreferences401
      | GetOrCreateDefaultNotificationPreferences500
    >,
    void,
    TContext
  >({
    mutationKey,
    mutationFn: async () => {
      return getOrCreateDefaultNotificationPreferences(config);
    },
  });
}

/**
 * @description Returns existing preferences or creates default preferences for the authenticated user
 * @summary Get or create default notification preferences
 * {@link /api/v1/users/me/notification-preferences/default}
 */
export function useGetOrCreateDefaultNotificationPreferences<TContext>(
  options: {
    mutation?: UseMutationOptions<
      GetOrCreateDefaultNotificationPreferencesMutationResponse,
      ResponseErrorConfig<
        | GetOrCreateDefaultNotificationPreferences401
        | GetOrCreateDefaultNotificationPreferences500
      >,
      void,
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ??
    getOrCreateDefaultNotificationPreferencesMutationKey();

  const baseOptions = getOrCreateDefaultNotificationPreferencesMutationOptions(
    config,
  ) as UseMutationOptions<
    GetOrCreateDefaultNotificationPreferencesMutationResponse,
    ResponseErrorConfig<
      | GetOrCreateDefaultNotificationPreferences401
      | GetOrCreateDefaultNotificationPreferences500
    >,
    void,
    TContext
  >;

  return useMutation<
    GetOrCreateDefaultNotificationPreferencesMutationResponse,
    ResponseErrorConfig<
      | GetOrCreateDefaultNotificationPreferences401
      | GetOrCreateDefaultNotificationPreferences500
    >,
    void,
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    GetOrCreateDefaultNotificationPreferencesMutationResponse,
    ResponseErrorConfig<
      | GetOrCreateDefaultNotificationPreferences401
      | GetOrCreateDefaultNotificationPreferences500
    >,
    void,
    TContext
  >;
}
