/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  UpdateNotificationPreferencesMutationRequest,
  UpdateNotificationPreferencesMutationResponse,
  UpdateNotificationPreferences400,
  UpdateNotificationPreferences401,
  UpdateNotificationPreferences404,
  UpdateNotificationPreferences422,
  UpdateNotificationPreferences500,
} from "../../types/types.gen.ts";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const updateNotificationPreferencesMutationKey = () =>
  [{ url: "/api/v1/users/me/notification-preferences" }] as const;

export type UpdateNotificationPreferencesMutationKey = ReturnType<
  typeof updateNotificationPreferencesMutationKey
>;

/**
 * @description Updates notification preferences for the authenticated user
 * @summary Update notification preferences
 * {@link /api/v1/users/me/notification-preferences}
 */
export async function updateNotificationPreferences(
  data: UpdateNotificationPreferencesMutationRequest,
  config: Partial<
    RequestConfig<UpdateNotificationPreferencesMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    UpdateNotificationPreferencesMutationResponse,
    ResponseErrorConfig<
      | UpdateNotificationPreferences400
      | UpdateNotificationPreferences401
      | UpdateNotificationPreferences404
      | UpdateNotificationPreferences422
      | UpdateNotificationPreferences500
    >,
    UpdateNotificationPreferencesMutationRequest
  >({
    method: "PATCH",
    url: `/api/v1/users/me/notification-preferences`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function updateNotificationPreferencesMutationOptions<
  TContext = unknown,
>(
  config: Partial<
    RequestConfig<UpdateNotificationPreferencesMutationRequest>
  > & { client?: Client } = {},
) {
  const mutationKey = updateNotificationPreferencesMutationKey();
  return mutationOptions<
    UpdateNotificationPreferencesMutationResponse,
    ResponseErrorConfig<
      | UpdateNotificationPreferences400
      | UpdateNotificationPreferences401
      | UpdateNotificationPreferences404
      | UpdateNotificationPreferences422
      | UpdateNotificationPreferences500
    >,
    { data: UpdateNotificationPreferencesMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return updateNotificationPreferences(data, config);
    },
  });
}

/**
 * @description Updates notification preferences for the authenticated user
 * @summary Update notification preferences
 * {@link /api/v1/users/me/notification-preferences}
 */
export function useUpdateNotificationPreferences<TContext>(
  options: {
    mutation?: UseMutationOptions<
      UpdateNotificationPreferencesMutationResponse,
      ResponseErrorConfig<
        | UpdateNotificationPreferences400
        | UpdateNotificationPreferences401
        | UpdateNotificationPreferences404
        | UpdateNotificationPreferences422
        | UpdateNotificationPreferences500
      >,
      { data: UpdateNotificationPreferencesMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<UpdateNotificationPreferencesMutationRequest>
    > & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? updateNotificationPreferencesMutationKey();

  const baseOptions = updateNotificationPreferencesMutationOptions(
    config,
  ) as UseMutationOptions<
    UpdateNotificationPreferencesMutationResponse,
    ResponseErrorConfig<
      | UpdateNotificationPreferences400
      | UpdateNotificationPreferences401
      | UpdateNotificationPreferences404
      | UpdateNotificationPreferences422
      | UpdateNotificationPreferences500
    >,
    { data: UpdateNotificationPreferencesMutationRequest },
    TContext
  >;

  return useMutation<
    UpdateNotificationPreferencesMutationResponse,
    ResponseErrorConfig<
      | UpdateNotificationPreferences400
      | UpdateNotificationPreferences401
      | UpdateNotificationPreferences404
      | UpdateNotificationPreferences422
      | UpdateNotificationPreferences500
    >,
    { data: UpdateNotificationPreferencesMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    UpdateNotificationPreferencesMutationResponse,
    ResponseErrorConfig<
      | UpdateNotificationPreferences400
      | UpdateNotificationPreferences401
      | UpdateNotificationPreferences404
      | UpdateNotificationPreferences422
      | UpdateNotificationPreferences500
    >,
    { data: UpdateNotificationPreferencesMutationRequest },
    TContext
  >;
}
