/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  AddCommentReactionMutationRequest,
  AddCommentReactionMutationResponse,
  AddCommentReactionPathParams,
  AddCommentReaction400,
  AddCommentReaction401,
  AddCommentReaction404,
  AddCommentReaction409,
  AddCommentReaction422,
  AddCommentReaction500,
} from "../../types/types.gen.ts";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const addCommentReactionMutationKey = () =>
  [{ url: "/api/v1/comments/:commentID/reactions" }] as const;

export type AddCommentReactionMutationKey = ReturnType<
  typeof addCommentReactionMutationKey
>;

/**
 * @description Adds an emoji reaction to a comment
 * @summary Add a reaction to a comment
 * {@link /api/v1/comments/:commentID/reactions}
 */
export async function addCommentReaction(
  commentID: AddCommentReactionPathParams["commentID"],
  data: AddCommentReactionMutationRequest,
  config: Partial<RequestConfig<AddCommentReactionMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    AddCommentReactionMutationResponse,
    ResponseErrorConfig<
      | AddCommentReaction400
      | AddCommentReaction401
      | AddCommentReaction404
      | AddCommentReaction409
      | AddCommentReaction422
      | AddCommentReaction500
    >,
    AddCommentReactionMutationRequest
  >({
    method: "POST",
    url: `/api/v1/comments/${commentID}/reactions`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function addCommentReactionMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<AddCommentReactionMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = addCommentReactionMutationKey();
  return mutationOptions<
    AddCommentReactionMutationResponse,
    ResponseErrorConfig<
      | AddCommentReaction400
      | AddCommentReaction401
      | AddCommentReaction404
      | AddCommentReaction409
      | AddCommentReaction422
      | AddCommentReaction500
    >,
    {
      commentID: AddCommentReactionPathParams["commentID"];
      data: AddCommentReactionMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ commentID, data }) => {
      return addCommentReaction(commentID, data, config);
    },
  });
}

/**
 * @description Adds an emoji reaction to a comment
 * @summary Add a reaction to a comment
 * {@link /api/v1/comments/:commentID/reactions}
 */
export function useAddCommentReaction<TContext>(
  options: {
    mutation?: UseMutationOptions<
      AddCommentReactionMutationResponse,
      ResponseErrorConfig<
        | AddCommentReaction400
        | AddCommentReaction401
        | AddCommentReaction404
        | AddCommentReaction409
        | AddCommentReaction422
        | AddCommentReaction500
      >,
      {
        commentID: AddCommentReactionPathParams["commentID"];
        data: AddCommentReactionMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<AddCommentReactionMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? addCommentReactionMutationKey();

  const baseOptions = addCommentReactionMutationOptions(
    config,
  ) as UseMutationOptions<
    AddCommentReactionMutationResponse,
    ResponseErrorConfig<
      | AddCommentReaction400
      | AddCommentReaction401
      | AddCommentReaction404
      | AddCommentReaction409
      | AddCommentReaction422
      | AddCommentReaction500
    >,
    {
      commentID: AddCommentReactionPathParams["commentID"];
      data: AddCommentReactionMutationRequest;
    },
    TContext
  >;

  return useMutation<
    AddCommentReactionMutationResponse,
    ResponseErrorConfig<
      | AddCommentReaction400
      | AddCommentReaction401
      | AddCommentReaction404
      | AddCommentReaction409
      | AddCommentReaction422
      | AddCommentReaction500
    >,
    {
      commentID: AddCommentReactionPathParams["commentID"];
      data: AddCommentReactionMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    AddCommentReactionMutationResponse,
    ResponseErrorConfig<
      | AddCommentReaction400
      | AddCommentReaction401
      | AddCommentReaction404
      | AddCommentReaction409
      | AddCommentReaction422
      | AddCommentReaction500
    >,
    {
      commentID: AddCommentReactionPathParams["commentID"];
      data: AddCommentReactionMutationRequest;
    },
    TContext
  >;
}
