/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  GetCommentReactionUsersQueryResponse,
  GetCommentReactionUsersPathParams,
  GetCommentReactionUsers400,
  GetCommentReactionUsers401,
  GetCommentReactionUsers404,
  GetCommentReactionUsers500,
} from "../../types/types.gen.ts";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getCommentReactionUsersSuspenseQueryKey = (
  commentID: GetCommentReactionUsersPathParams["commentID"],
  emoji: GetCommentReactionUsersPathParams["emoji"],
) =>
  [
    {
      url: "/api/v1/comments/:commentID/reactions/:emoji/users",
      params: { commentID: commentID, emoji: emoji },
    },
  ] as const;

export type GetCommentReactionUsersSuspenseQueryKey = ReturnType<
  typeof getCommentReactionUsersSuspenseQueryKey
>;

/**
 * @description Retrieves users who reacted with a specific emoji on a comment
 * @summary Get users who reacted with an emoji
 * {@link /api/v1/comments/:commentID/reactions/:emoji/users}
 */
export async function getCommentReactionUsersSuspense(
  commentID: GetCommentReactionUsersPathParams["commentID"],
  emoji: GetCommentReactionUsersPathParams["emoji"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetCommentReactionUsersQueryResponse,
    ResponseErrorConfig<
      | GetCommentReactionUsers400
      | GetCommentReactionUsers401
      | GetCommentReactionUsers404
      | GetCommentReactionUsers500
    >,
    unknown
  >({
    method: "GET",
    url: `/api/v1/comments/${commentID}/reactions/${emoji}/users`,
    ...requestConfig,
  });
  return res.data;
}

export function getCommentReactionUsersSuspenseQueryOptions(
  commentID: GetCommentReactionUsersPathParams["commentID"],
  emoji: GetCommentReactionUsersPathParams["emoji"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getCommentReactionUsersSuspenseQueryKey(commentID, emoji);
  return queryOptions<
    GetCommentReactionUsersQueryResponse,
    ResponseErrorConfig<
      | GetCommentReactionUsers400
      | GetCommentReactionUsers401
      | GetCommentReactionUsers404
      | GetCommentReactionUsers500
    >,
    GetCommentReactionUsersQueryResponse,
    typeof queryKey
  >({
    enabled: !!(commentID && emoji),
    queryKey,
    queryFn: async ({ signal }) => {
      if (!config.signal) {
        config.signal = signal;
      }
      return getCommentReactionUsersSuspense(commentID, emoji, config);
    },
  });
}

/**
 * @description Retrieves users who reacted with a specific emoji on a comment
 * @summary Get users who reacted with an emoji
 * {@link /api/v1/comments/:commentID/reactions/:emoji/users}
 */
export function useGetCommentReactionUsersSuspense<
  TData = GetCommentReactionUsersQueryResponse,
  TQueryKey extends QueryKey = GetCommentReactionUsersSuspenseQueryKey,
>(
  commentID: GetCommentReactionUsersPathParams["commentID"],
  emoji: GetCommentReactionUsersPathParams["emoji"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetCommentReactionUsersQueryResponse,
        ResponseErrorConfig<
          | GetCommentReactionUsers400
          | GetCommentReactionUsers401
          | GetCommentReactionUsers404
          | GetCommentReactionUsers500
        >,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ??
    getCommentReactionUsersSuspenseQueryKey(commentID, emoji);

  const query = useSuspenseQuery(
    {
      ...getCommentReactionUsersSuspenseQueryOptions(commentID, emoji, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetCommentReactionUsers400
      | GetCommentReactionUsers401
      | GetCommentReactionUsers404
      | GetCommentReactionUsers500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
