/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  GetCommentReactionsSummaryQueryResponse,
  GetCommentReactionsSummaryPathParams,
  GetCommentReactionsSummary400,
  GetCommentReactionsSummary401,
  GetCommentReactionsSummary404,
  GetCommentReactionsSummary500,
} from "../../types/types.gen.ts";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getCommentReactionsSummarySuspenseQueryKey = (
  commentID: GetCommentReactionsSummaryPathParams["commentID"],
) =>
  [
    {
      url: "/api/v1/comments/:commentID/reactions",
      params: { commentID: commentID },
    },
  ] as const;

export type GetCommentReactionsSummarySuspenseQueryKey = ReturnType<
  typeof getCommentReactionsSummarySuspenseQueryKey
>;

/**
 * @description Retrieves aggregated emoji reactions for a comment
 * @summary Get reactions summary for a comment
 * {@link /api/v1/comments/:commentID/reactions}
 */
export async function getCommentReactionsSummarySuspense(
  commentID: GetCommentReactionsSummaryPathParams["commentID"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetCommentReactionsSummaryQueryResponse,
    ResponseErrorConfig<
      | GetCommentReactionsSummary400
      | GetCommentReactionsSummary401
      | GetCommentReactionsSummary404
      | GetCommentReactionsSummary500
    >,
    unknown
  >({
    method: "GET",
    url: `/api/v1/comments/${commentID}/reactions`,
    ...requestConfig,
  });
  return res.data;
}

export function getCommentReactionsSummarySuspenseQueryOptions(
  commentID: GetCommentReactionsSummaryPathParams["commentID"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getCommentReactionsSummarySuspenseQueryKey(commentID);
  return queryOptions<
    GetCommentReactionsSummaryQueryResponse,
    ResponseErrorConfig<
      | GetCommentReactionsSummary400
      | GetCommentReactionsSummary401
      | GetCommentReactionsSummary404
      | GetCommentReactionsSummary500
    >,
    GetCommentReactionsSummaryQueryResponse,
    typeof queryKey
  >({
    enabled: !!commentID,
    queryKey,
    queryFn: async ({ signal }) => {
      if (!config.signal) {
        config.signal = signal;
      }
      return getCommentReactionsSummarySuspense(commentID, config);
    },
  });
}

/**
 * @description Retrieves aggregated emoji reactions for a comment
 * @summary Get reactions summary for a comment
 * {@link /api/v1/comments/:commentID/reactions}
 */
export function useGetCommentReactionsSummarySuspense<
  TData = GetCommentReactionsSummaryQueryResponse,
  TQueryKey extends QueryKey = GetCommentReactionsSummarySuspenseQueryKey,
>(
  commentID: GetCommentReactionsSummaryPathParams["commentID"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetCommentReactionsSummaryQueryResponse,
        ResponseErrorConfig<
          | GetCommentReactionsSummary400
          | GetCommentReactionsSummary401
          | GetCommentReactionsSummary404
          | GetCommentReactionsSummary500
        >,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ??
    getCommentReactionsSummarySuspenseQueryKey(commentID);

  const query = useSuspenseQuery(
    {
      ...getCommentReactionsSummarySuspenseQueryOptions(commentID, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetCommentReactionsSummary400
      | GetCommentReactionsSummary401
      | GetCommentReactionsSummary404
      | GetCommentReactionsSummary500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
