/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  CreateTripInviteMutationRequest,
  CreateTripInviteMutationResponse,
  CreateTripInvitePathParams,
  CreateTripInvite400,
  CreateTripInvite401,
  CreateTripInvite404,
  CreateTripInvite422,
  CreateTripInvite500,
} from "../../types/types.gen.ts";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const createTripInviteMutationKey = () =>
  [{ url: "/api/v1/trips/:tripID/invites" }] as const;

export type CreateTripInviteMutationKey = ReturnType<
  typeof createTripInviteMutationKey
>;

/**
 * @description Creates a shareable invite for the trip. Caller must be a trip member.
 * @summary Create a trip invite
 * {@link /api/v1/trips/:tripID/invites}
 */
export async function createTripInvite(
  tripID: CreateTripInvitePathParams["tripID"],
  data?: CreateTripInviteMutationRequest,
  config: Partial<RequestConfig<CreateTripInviteMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    CreateTripInviteMutationResponse,
    ResponseErrorConfig<
      | CreateTripInvite400
      | CreateTripInvite401
      | CreateTripInvite404
      | CreateTripInvite422
      | CreateTripInvite500
    >,
    CreateTripInviteMutationRequest
  >({
    method: "POST",
    url: `/api/v1/trips/${tripID}/invites`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function createTripInviteMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<CreateTripInviteMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = createTripInviteMutationKey();
  return mutationOptions<
    CreateTripInviteMutationResponse,
    ResponseErrorConfig<
      | CreateTripInvite400
      | CreateTripInvite401
      | CreateTripInvite404
      | CreateTripInvite422
      | CreateTripInvite500
    >,
    {
      tripID: CreateTripInvitePathParams["tripID"];
      data?: CreateTripInviteMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ tripID, data }) => {
      return createTripInvite(tripID, data, config);
    },
  });
}

/**
 * @description Creates a shareable invite for the trip. Caller must be a trip member.
 * @summary Create a trip invite
 * {@link /api/v1/trips/:tripID/invites}
 */
export function useCreateTripInvite<TContext>(
  options: {
    mutation?: UseMutationOptions<
      CreateTripInviteMutationResponse,
      ResponseErrorConfig<
        | CreateTripInvite400
        | CreateTripInvite401
        | CreateTripInvite404
        | CreateTripInvite422
        | CreateTripInvite500
      >,
      {
        tripID: CreateTripInvitePathParams["tripID"];
        data?: CreateTripInviteMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<CreateTripInviteMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? createTripInviteMutationKey();

  const baseOptions = createTripInviteMutationOptions(
    config,
  ) as UseMutationOptions<
    CreateTripInviteMutationResponse,
    ResponseErrorConfig<
      | CreateTripInvite400
      | CreateTripInvite401
      | CreateTripInvite404
      | CreateTripInvite422
      | CreateTripInvite500
    >,
    {
      tripID: CreateTripInvitePathParams["tripID"];
      data?: CreateTripInviteMutationRequest;
    },
    TContext
  >;

  return useMutation<
    CreateTripInviteMutationResponse,
    ResponseErrorConfig<
      | CreateTripInvite400
      | CreateTripInvite401
      | CreateTripInvite404
      | CreateTripInvite422
      | CreateTripInvite500
    >,
    {
      tripID: CreateTripInvitePathParams["tripID"];
      data?: CreateTripInviteMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    CreateTripInviteMutationResponse,
    ResponseErrorConfig<
      | CreateTripInvite400
      | CreateTripInvite401
      | CreateTripInvite404
      | CreateTripInvite422
      | CreateTripInvite500
    >,
    {
      tripID: CreateTripInvitePathParams["tripID"];
      data?: CreateTripInviteMutationRequest;
    },
    TContext
  >;
}
