/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type {
  GetAllTripsQueryResponse,
  GetAllTrips500,
} from "../../types/types.gen.ts";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getAllTripsSuspenseQueryKey = () =>
  [{ url: "/api/v1/trips" }] as const;

export type GetAllTripsSuspenseQueryKey = ReturnType<
  typeof getAllTripsSuspenseQueryKey
>;

/**
 * @description Retrieves all trips
 * @summary Get all trips
 * {@link /api/v1/trips}
 */
export async function getAllTripsSuspense(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetAllTripsQueryResponse,
    ResponseErrorConfig<GetAllTrips500>,
    unknown
  >({ method: "GET", url: `/api/v1/trips`, ...requestConfig });
  return res.data;
}

export function getAllTripsSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getAllTripsSuspenseQueryKey();
  return queryOptions<
    GetAllTripsQueryResponse,
    ResponseErrorConfig<GetAllTrips500>,
    GetAllTripsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getAllTripsSuspense(config);
    },
  });
}

/**
 * @description Retrieves all trips
 * @summary Get all trips
 * {@link /api/v1/trips}
 */
export function useGetAllTripsSuspense<
  TData = GetAllTripsQueryResponse,
  TQueryKey extends QueryKey = GetAllTripsSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetAllTripsQueryResponse,
        ResponseErrorConfig<GetAllTrips500>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? getAllTripsSuspenseQueryKey();

  const query = useSuspenseQuery(
    {
      ...getAllTripsSuspenseQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetAllTrips500>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
