/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { GetAllTripsQueryResponse, GetAllTripsQueryParams, GetAllTrips400, GetAllTrips401, GetAllTrips500 } from "../../types/types.gen.ts";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getAllTripsQueryKey = (params?: GetAllTripsQueryParams) => [{ url: '/api/v1/trips' }, ...(params ? [params] : [])] as const

export type GetAllTripsQueryKey = ReturnType<typeof getAllTripsQueryKey>

/**
 * @description Retrieves trips with cursor-based pagination. Use limit and cursor query params.
 * @summary Get all trips
 * {@link /api/v1/trips}
 */
export async function getAllTrips(params?: GetAllTripsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetAllTripsQueryResponse, ResponseErrorConfig<GetAllTrips400 | GetAllTrips401 | GetAllTrips500>, unknown>({ method : "GET", url : `/api/v1/trips`, params, ... requestConfig })  
  return res.data
}

export function getAllTripsQueryOptions(params?: GetAllTripsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getAllTripsQueryKey(params)
  return queryOptions<GetAllTripsQueryResponse, ResponseErrorConfig<GetAllTrips400 | GetAllTrips401 | GetAllTrips500>, GetAllTripsQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getAllTrips(params, config)
   },
  })
}

/**
 * @description Retrieves trips with cursor-based pagination. Use limit and cursor query params.
 * @summary Get all trips
 * {@link /api/v1/trips}
 */
export function useGetAllTrips<TData = GetAllTripsQueryResponse, TQueryData = GetAllTripsQueryResponse, TQueryKey extends QueryKey = GetAllTripsQueryKey>(params?: GetAllTripsQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetAllTripsQueryResponse, ResponseErrorConfig<GetAllTrips400 | GetAllTrips401 | GetAllTrips500>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getAllTripsQueryKey(params)

  const query = useQuery({
   ...getAllTripsQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<GetAllTrips400 | GetAllTrips401 | GetAllTrips500>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}