/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { Client, RequestConfig, ResponseErrorConfig } from "../client";
import type {
  GetAllTripsQueryResponse,
  GetAllTripsQueryParams,
  GetAllTrips400,
  GetAllTrips401,
  GetAllTrips500,
} from "../../types/types.gen.ts";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getAllTripsSuspenseQueryKey = (
  params: GetAllTripsQueryParams = {},
) => [{ url: "/api/v1/trips" }, ...(params ? [params] : [])] as const;

export type GetAllTripsSuspenseQueryKey = ReturnType<
  typeof getAllTripsSuspenseQueryKey
>;

/**
 * @description Retrieves trips with cursor-based pagination. Use limit and cursor query params.
 * @summary Get all trips
 * {@link /api/v1/trips}
 */
export async function getAllTripsSuspense(
  params?: GetAllTripsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetAllTripsQueryResponse,
    ResponseErrorConfig<GetAllTrips400 | GetAllTrips401 | GetAllTrips500>,
    unknown
  >({ method: "GET", url: `/api/v1/trips`, params, ...requestConfig });
  return res.data;
}

export function getAllTripsSuspenseQueryOptions(
  params?: GetAllTripsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getAllTripsSuspenseQueryKey(params);
  return queryOptions<
    GetAllTripsQueryResponse,
    ResponseErrorConfig<GetAllTrips400 | GetAllTrips401 | GetAllTrips500>,
    GetAllTripsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getAllTripsSuspense(params, config);
    },
  });
}

/**
 * @description Retrieves trips with cursor-based pagination. Use limit and cursor query params.
 * @summary Get all trips
 * {@link /api/v1/trips}
 */
export function useGetAllTripsSuspense<
  TData = GetAllTripsQueryResponse,
  TQueryKey extends QueryKey = GetAllTripsSuspenseQueryKey,
>(
  params?: GetAllTripsQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetAllTripsQueryResponse,
        ResponseErrorConfig<GetAllTrips400 | GetAllTrips401 | GetAllTrips500>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getAllTripsSuspenseQueryKey(params);

  const query = useSuspenseQuery(
    {
      ...getAllTripsSuspenseQueryOptions(params, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<GetAllTrips400 | GetAllTrips401 | GetAllTrips500>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
