package models

// PlacesSearchRequest represents the request to search for places
type PlacesSearchRequest struct {
	// Input is the text string on which to search (e.g., "Eiffel Tower", "Paris, France")
	Input string `json:"input" validate:"required,min=1"`

	// Language is the language code for the results (optional, defaults to English)
	Language string `json:"language,omitempty"`

	// Limit is the maximum number of results to return (optional, defaults to 5, max 20)
	Limit int `json:"limit,omitempty"`

	// Types restricts results to specific place types (optional)
	// Examples: "geocode", "address", "establishment", "(cities)", "(regions)"
	Types string `json:"types,omitempty"`
}

// PlacesSearchResponse contains the search results
type PlacesSearchResponse struct {
	Predictions []PlacePrediction `json:"predictions"`
	Status      string            `json:"status"`
}

// PlacePrediction represents a single place autocomplete result
type PlacePrediction struct {
	// PlaceID is the unique identifier for this place
	PlaceID string `json:"place_id"`

	// Description is the human-readable name for this place
	Description string `json:"description"`

	// StructuredFormatting contains the main text and secondary text
	MainText      string   `json:"main_text"`
	SecondaryText string   `json:"secondary_text,omitempty"`
	Types         []string `json:"types"`

	// MatchedSubstrings indicates which parts of the description match the input
	MatchedSubstrings []MatchedSubstring `json:"matched_substrings,omitempty"`
}

// MatchedSubstring represents a substring in the description that matches the input
type MatchedSubstring struct {
	Length int `json:"length"`
	Offset int `json:"offset"`
}

// PlaceDetailsRequest represents the request to get detailed information about a place
// Either PlaceID (from typeahead) or Input (text search) must be provided
type PlaceDetailsRequest struct {
	// PlaceID is the unique identifier for the place (from typeahead results)
	PlaceID string `json:"place_id,omitempty"`

	// Input is the text to search for if PlaceID is not provided
	// Example: "Eiffel Tower", "Paris, France"
	Input string `json:"input,omitempty"`

	// Language is the language code for the results (optional)
	Language string `json:"language,omitempty"`

	// Fields specifies which fields to return (optional)
	// If not specified, returns all available fields
	Fields []string `json:"fields,omitempty"`
}

// PlaceDetailsResponse contains detailed information about a specific place
type PlaceDetailsResponse struct {
	PlaceID string `json:"place_id"`
	Name    string `json:"name"`

	// Address information
	FormattedAddress  string             `json:"formatted_address"`
	AddressComponents []AddressComponent `json:"address_components,omitempty"`

	// Location coordinates
	Geometry PlaceGeometry `json:"geometry"`

	// Place types
	Types []string `json:"types"`

	// Contact information
	FormattedPhoneNumber     string `json:"formatted_phone_number,omitempty"`
	InternationalPhoneNumber string `json:"international_phone_number,omitempty"`
	Website                  string `json:"website,omitempty"`

	// Photos
	Photos []PlacePhoto `json:"photos,omitempty"`

	// Ratings and reviews
	Rating           float32 `json:"rating,omitempty"`
	UserRatingsTotal int     `json:"user_ratings_total,omitempty"`

	// Business information
	OpeningHours *OpeningHours `json:"opening_hours,omitempty"`
	PriceLevel   int           `json:"price_level,omitempty"`

	// Additional information
	UTCOffset int    `json:"utc_offset,omitempty"`
	Vicinity  string `json:"vicinity,omitempty"`
	Icon      string `json:"icon,omitempty"`
}

// AddressComponent represents a component of the address
type AddressComponent struct {
	LongName  string   `json:"long_name"`
	ShortName string   `json:"short_name"`
	Types     []string `json:"types"`
}

// PlaceGeometry contains the location and viewport information
type PlaceGeometry struct {
	Location LatLng  `json:"location"`
	Viewport *Bounds `json:"viewport,omitempty"`
}

// LatLng represents a latitude/longitude pair
type LatLng struct {
	Lat float64 `json:"lat"`
	Lng float64 `json:"lng"`
}

// Bounds represents a rectangular geographic area
type Bounds struct {
	Northeast LatLng `json:"northeast"`
	Southwest LatLng `json:"southwest"`
}

// PlacePhoto contains information about a place photo
type PlacePhoto struct {
	PhotoReference   string   `json:"photo_reference"`
	Height           int      `json:"height"`
	Width            int      `json:"width"`
	HTMLAttributions []string `json:"html_attributions,omitempty"`
	// PhotoURL is a generated URL to fetch the photo (optional, generated by backend)
	PhotoURL string `json:"photo_url,omitempty"`
}

// OpeningHours contains information about when the place is open
type OpeningHours struct {
	OpenNow     bool     `json:"open_now"`
	Periods     []Period `json:"periods,omitempty"`
	WeekdayText []string `json:"weekday_text,omitempty"`
}

// Period represents an open/close time period
type Period struct {
	Open  DayTime `json:"open"`
	Close DayTime `json:"close,omitempty"`
}

// DayTime represents a day and time
type DayTime struct {
	Day  int    `json:"day"`
	Time string `json:"time"`
}
