/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  UpdateUserMutationRequest,
  UpdateUserMutationResponse,
  UpdateUserPathParams,
  UpdateUser400,
  UpdateUser404,
  UpdateUser422,
  UpdateUser500,
} from "../../types/types.gen.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const updateUserMutationKey = () =>
  [{ url: "/api/v1/users/:userID" }] as const;

export type UpdateUserMutationKey = ReturnType<typeof updateUserMutationKey>;

/**
 * @description Updates an existing user by ID
 * @summary Update a user
 * {@link /api/v1/users/:userID}
 */
export async function updateUser(
  userID: UpdateUserPathParams["userID"],
  data?: UpdateUserMutationRequest,
  config: Partial<RequestConfig<UpdateUserMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    UpdateUserMutationResponse,
    ResponseErrorConfig<
      UpdateUser400 | UpdateUser404 | UpdateUser422 | UpdateUser500
    >,
    UpdateUserMutationRequest
  >({
    method: "PATCH",
    url: `/api/v1/users/${userID}`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function updateUserMutationOptions(
  config: Partial<RequestConfig<UpdateUserMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const mutationKey = updateUserMutationKey();
  return mutationOptions<
    UpdateUserMutationResponse,
    ResponseErrorConfig<
      UpdateUser400 | UpdateUser404 | UpdateUser422 | UpdateUser500
    >,
    {
      userID: UpdateUserPathParams["userID"];
      data?: UpdateUserMutationRequest;
    },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ userID, data }) => {
      return updateUser(userID, data, config);
    },
  });
}

/**
 * @description Updates an existing user by ID
 * @summary Update a user
 * {@link /api/v1/users/:userID}
 */
export function useUpdateUser<TContext>(
  options: {
    mutation?: UseMutationOptions<
      UpdateUserMutationResponse,
      ResponseErrorConfig<
        UpdateUser400 | UpdateUser404 | UpdateUser422 | UpdateUser500
      >,
      {
        userID: UpdateUserPathParams["userID"];
        data?: UpdateUserMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<UpdateUserMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? updateUserMutationKey();

  const baseOptions = updateUserMutationOptions(config) as UseMutationOptions<
    UpdateUserMutationResponse,
    ResponseErrorConfig<
      UpdateUser400 | UpdateUser404 | UpdateUser422 | UpdateUser500
    >,
    {
      userID: UpdateUserPathParams["userID"];
      data?: UpdateUserMutationRequest;
    },
    TContext
  >;

  return useMutation<
    UpdateUserMutationResponse,
    ResponseErrorConfig<
      UpdateUser400 | UpdateUser404 | UpdateUser422 | UpdateUser500
    >,
    {
      userID: UpdateUserPathParams["userID"];
      data?: UpdateUserMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    UpdateUserMutationResponse,
    ResponseErrorConfig<
      UpdateUser400 | UpdateUser404 | UpdateUser422 | UpdateUser500
    >,
    {
      userID: UpdateUserPathParams["userID"];
      data?: UpdateUserMutationRequest;
    },
    TContext
  >;
}
